### ISSUE TITLE
Require journals to have ISSNs

### ISSUE THREAD

**Issue by justgo129** [USGCRP/gcis#147]
All journals have ISSNs, whether they be eissns, regular ISSNs, or both.  Just as we require ISBNs for books, we should require ISSNs for journals.

**Comment by bduggan** [comment]
I [checked](https://github.com/USGCRP/gcis-scripts/blob/master/check-issns.pl) and found [these](https://gist.github.com/bduggan/b9c04354dcda448010d3) journals without ISSNs.

**Comment by rewolfe** [comment]
This is something that Brent could do.  Find the ISSNs for these journals and add them to GCIS.

**Comment by rewolfe** [comment]
Brent,

Could you add the ISSNs to GCIS for the journals (see Brain's list).

Thanks,

 -Robert

On Thu, May 28, 2015 at 8:29 AM, Brian Duggan <notifications@github.com>
wrote:

> I checked
> <https://github.com/USGCRP/gcis-scripts/blob/master/check-issns.pl> and
> found these <https://gist.github.com/bduggan/b9c04354dcda448010d3>
> journals without ISSNs.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGCRP/gcis/issues/147#issuecomment-106295512>.
>



-- 
Robert Wolfe, NASA GSFC @ USGCRP, o: 202-419-3470, m: 301-257-6966

**Comment by bduggan** [comment]
Adding Brent's username in a message: @BNewman2104 will cause a notification to be sent.

**Comment by rewolfe** [comment]
Cool.

On Fri, May 29, 2015 at 12:05 PM, Brian Duggan <notifications@github.com>
wrote:

> Adding Brent's username in a message: @BNewman2104
> <https://github.com/BNewman2104> will cause a notification to be sent.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGCRP/gcis/issues/147#issuecomment-106857832>.
>



-- 
Robert Wolfe, NASA GSFC @ USGCRP, o: 202-419-3470, m: 301-257-6966

**Comment by BNewman2104** [comment]
Sorry for the delay, I will take a look at this now.

**Comment by bduggan** [comment]
I am closing this issue since not all of our journals have ISSNs.  Feel free to re-open it if this changes.

**Comment by justgo129** [comment]
Could someone please inform about which journals don't have ISSNs?  I know of a few locations to check, beyond Worldcat.

**Comment by bduggan** [comment]
You can run the script in the above comment.

**Comment by justgo129** [comment]
That list is old as @BNewman2104 and @aulenbac have found ISSNs for most of the ones listed in that file.

**Comment by bduggan** [comment]
@justgo129 -- actually, there's a script there that you can run. which will update the list.

**Comment by justgo129** [comment]
I just found one more ISSN.  See the google doc for my comments about the lone remaining without -- I don't think it's a journal to begin with.

**Comment by rewolfe** [comment]
I added a link to more information on one of the references:

https://en.wikipedia.org/wiki/Annales_de_chimie_et_de_physique

The last issue was published in 1914.  The ISSN doesn't look correct.

On Tue, Jun 23, 2015 at 11:31 AM, justgo129 <notifications@github.com>
wrote:

> I just found one more ISSN. See the google doc for my comments about the
> lone remaining without -- I don't think it's a journal to begin with.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGCRP/gcis/issues/147#issuecomment-114547086>.
>



-- 
Robert Wolfe, NASA GSFC @ USGCRP, o: 202-419-3470, m: 301-257-6966

**Comment by justgo129** [comment]
Excellent find, Robert.

Indeed, Worldcat locates two journals with the same title (just as
wikipedia mentions):

http://www.worldcat.org/title/annales-de-chimie-et-de-physique/oclc/1481242&referer=brief_results
  This does not have an ISSN, presumably because the journal ended
publication in 1914.

http://www.worldcat.org/title/annales-de-chimie-et-de-physique/oclc/7077607&referer=brief_results
   This is for a journal that's been published from 1816-present.  ISSN =
0365-1444.

If indeed the age of a publication is a limiting factor, I'd be all right
removing the ISSN requirement but it would be nice for GCIS to have
functionality to link to other authoritative sources (e.g. Worldcat,
Library of Congress, Ullrichs) in addition to what we've done for datasets
(e.g. CEOS, crossfref). Doing that through an ISSN would be good since
journal titles can change, cease, etc. - just like here. Granted, none of
these "authoritative" sources are perfect since we've found errors in each.


On Tue, Jun 23, 2015 at 1:58 PM, Robert Wolfe <notifications@github.com>
wrote:

> I added a link to more information on one of the references:
>
> https://en.wikipedia.org/wiki/Annales_de_chimie_et_de_physique
>
> The last issue was published in 1914. The ISSN doesn't look correct.
>
> On Tue, Jun 23, 2015 at 11:31 AM, justgo129 <notifications@github.com>
> wrote:
>
> > I just found one more ISSN. See the google doc for my comments about the
> > lone remaining without -- I don't think it's a journal to begin with.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/USGCRP/gcis/issues/147#issuecomment-114547086>.
> >
>
>
>
> --
> Robert Wolfe, NASA GSFC @ USGCRP, o: 202-419-3470, m: 301-257-6966
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGCRP/gcis/issues/147#issuecomment-114590945>.
>



-- 
_________________________________
Justin Goldstein, Ph.D.
Advance Science Climate Data and Observing Systems Coordinator
US Global Change Research Program
1717 Pennsylvania Ave NW, Suite #250
Washington, DC 20006

O: (202) 419-3496
M: (202) 285-3005

e-mail: jgoldstein AT usgcrp Dot gov
http://www.globalchange.gov

**Comment by justgo129** [comment]
Oops - I forgot to ask @aulenbac what he thinks about this.


On Tue, Jun 23, 2015 at 2:14 PM, Justin Goldstein <jgoldstein@usgcrp.gov>
wrote:

> Excellent find, Robert.
>
> Indeed, Worldcat locates two journals with the same title (just as
> wikipedia mentions):
>
>
> http://www.worldcat.org/title/annales-de-chimie-et-de-physique/oclc/1481242&referer=brief_results
>   This does not have an ISSN, presumably because the journal ended
> publication in 1914.
>
>
> http://www.worldcat.org/title/annales-de-chimie-et-de-physique/oclc/7077607&referer=brief_results
>    This is for a journal that's been published from 1816-present.  ISSN =
> 0365-1444.
>
> If indeed the age of a publication is a limiting factor, I'd be all right
> removing the ISSN requirement but it would be nice for GCIS to have
> functionality to link to other authoritative sources (e.g. Worldcat,
> Library of Congress, Ullrichs) in addition to what we've done for datasets
> (e.g. CEOS, crossfref). Doing that through an ISSN would be good since
> journal titles can change, cease, etc. - just like here. Granted, none of
> these "authoritative" sources are perfect since we've found errors in each.
>
>
> On Tue, Jun 23, 2015 at 1:58 PM, Robert Wolfe <notifications@github.com>
> wrote:
>
>> I added a link to more information on one of the references:
>>
>> https://en.wikipedia.org/wiki/Annales_de_chimie_et_de_physique
>>
>> The last issue was published in 1914. The ISSN doesn't look correct.
>>
>> On Tue, Jun 23, 2015 at 11:31 AM, justgo129 <notifications@github.com>
>> wrote:
>>
>> > I just found one more ISSN. See the google doc for my comments about the
>> > lone remaining without -- I don't think it's a journal to begin with.
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> > <https://github.com/USGCRP/gcis/issues/147#issuecomment-114547086>.
>> >
>>
>>
>>
>> --
>> Robert Wolfe, NASA GSFC @ USGCRP, o: 202-419-3470, m: 301-257-6966
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/USGCRP/gcis/issues/147#issuecomment-114590945>.
>>
>
>
>
> --
> _________________________________
> Justin Goldstein, Ph.D.
> Advance Science Climate Data and Observing Systems Coordinator
> US Global Change Research Program
> 1717 Pennsylvania Ave NW, Suite #250
> Washington, DC 20006
>
> O: (202) 419-3496
> M: (202) 285-3005
>
> e-mail: jgoldstein AT usgcrp Dot gov
> http://www.globalchange.gov
>
>
>


-- 
_________________________________
Justin Goldstein, Ph.D.
Advance Science Climate Data and Observing Systems Coordinator
US Global Change Research Program
1717 Pennsylvania Ave NW, Suite #250
Washington, DC 20006

O: (202) 419-3496
M: (202) 285-3005

e-mail: jgoldstein AT usgcrp Dot gov
http://www.globalchange.gov

**Comment by BNewman2104** [comment]
I found a ISSN under "detailed information" here (
http://gallica.bnf.fr/ark:/12148/bpt6k34784b.image.r=Annales+de+chimie+et+de+physique.f4.langEN.pagination),
but have not found any other sources for the ISSN.











Brent Newman
Global Change Information System Student Assistant
U.S. Global Change Research Program
1717 Pennsylvania Avenue NW, Suite 250
Washington, DC 20006
Email: bnewman@usgcrp.gov

**Comment by justgo129** [comment]
Interesting find, Brent.  That page presents a good case of the use of
structured metadata.

I just queried for that ISBN in Worldcat.  Multiple items come up:
http://www.worldcat.org/search?qt=worldcat_org_all&q=03651444

Can we confirm that the version we think this is (the one that ended in
1914) is the entry in Worldcat without an ISBN?  Can we definitively tie
this article to a specific Worldcat entry?

On Tue, Jun 23, 2015 at 2:48 PM, Brent Newman <notifications@github.com>
wrote:

> I found a ISSN under "detailed information" here (
>
> http://gallica.bnf.fr/ark:/12148/bpt6k34784b.image.r=Annales+de+chimie+et+de+physique.f4.langEN.pagination
> ),
> but have not found any other sources for the ISSN.
>
>
>
>
>
>
>
>
>
>
>
> Brent Newman
> Global Change Information System Student Assistant
> U.S. Global Change Research Program
> 1717 Pennsylvania Avenue NW, Suite 250
> Washington, DC 20006
> Email: bnewman@usgcrp.gov
>
>
> On Tue, Jun 23, 2015 at 2:17 PM, justgo129 <notifications@github.com>
> wrote:
>
> > Oops - I forgot to ask @aulenbac what he thinks about this.
> >
> >
> > On Tue, Jun 23, 2015 at 2:14 PM, Justin Goldstein <jgoldstein@usgcrp.gov
> >
> > wrote:
> >
> >
> > > Excellent find, Robert.
> > >
> > > Indeed, Worldcat locates two journals with the same title (just as
> > > wikipedia mentions):
> > >
> > >
> > >
> >
> http://www.worldcat.org/title/annales-de-chimie-et-de-physique/oclc/1481242&referer=brief_results
> > > This does not have an ISSN, presumably because the journal ended
> > > publication in 1914.
> > >
> > >
> > >
> >
> http://www.worldcat.org/title/annales-de-chimie-et-de-physique/oclc/7077607&referer=brief_results
> > > This is for a journal that's been published from 1816-present. ISSN =
> > > 0365-1444.
> > >
> > > If indeed the age of a publication is a limiting factor, I'd be all
> right
> > > removing the ISSN requirement but it would be nice for GCIS to have
> > > functionality to link to other authoritative sources (e.g. Worldcat,
> > > Library of Congress, Ullrichs) in addition to what we've done for
> > datasets
> > > (e.g. CEOS, crossfref). Doing that through an ISSN would be good since
> > > journal titles can change, cease, etc. - just like here. Granted, none
> of
> > > these "authoritative" sources are perfect since we've found errors in
> > each.
> > >
> > >
> > > On Tue, Jun 23, 2015 at 1:58 PM, Robert Wolfe <
> notifications@github.com>
> > > wrote:
> > >
> > >> I added a link to more information on one of the references:
> > >>
> > >> https://en.wikipedia.org/wiki/Annales_de_chimie_et_de_physique
> > >>
> > >> The last issue was published in 1914. The ISSN doesn't look correct.
> > >>
> > >> On Tue, Jun 23, 2015 at 11:31 AM, justgo129 <notifications@github.com
> >
> > >> wrote:
> > >>
> > >> > I just found one more ISSN. See the google doc for my comments about
> > the
> > >> > lone remaining without -- I don't think it's a journal to begin
> with.
> > >> >
> > >> > —
> > >> > Reply to this email directly or view it on GitHub
> > >> > <https://github.com/USGCRP/gcis/issues/147#issuecomment-114547086>.
> > >> >
> > >>
> > >>
> > >>
> > >> --
> > >> Robert Wolfe, NASA GSFC @ USGCRP, o: 202-419-3470, m: 301-257-6966
> > >>
> > >> —
> > >> Reply to this email directly or view it on GitHub
> > >> <https://github.com/USGCRP/gcis/issues/147#issuecomment-114590945>.
> > >>
> > >
> > >
> > >
> > > --
> > > _________________________________
> > > Justin Goldstein, Ph.D.
> > > Advance Science Climate Data and Observing Systems Coordinator
> > > US Global Change Research Program
> > > 1717 Pennsylvania Ave NW, Suite #250
> > > Washington, DC 20006
> > >
> > > O: (202) 419-3496
> > > M: (202) 285-3005
> > >
> > > e-mail: jgoldstein AT usgcrp Dot gov
> > > http://www.globalchange.gov
> > >
> > >
> > >
> >
> >
> > --
> > _________________________________
> > Justin Goldstein, Ph.D.
> > Advance Science Climate Data and Observing Systems Coordinator
> > US Global Change Research Program
> > 1717 Pennsylvania Ave NW, Suite #250
> > Washington, DC 20006
> >
> > O: (202) 419-3496
> > M: (202) 285-3005
> >
> > e-mail: jgoldstein AT usgcrp Dot gov
> > http://www.globalchange.gov
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/USGCRP/gcis/issues/147#issuecomment-114595960>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGCRP/gcis/issues/147#issuecomment-114605656>.
>



-- 
_________________________________
Justin Goldstein, Ph.D.
Advance Science Climate Data and Observing Systems Coordinator
US Global Change Research Program
1717 Pennsylvania Ave NW, Suite #250
Washington, DC 20006

O: (202) 419-3496
M: (202) 285-3005

e-mail: jgoldstein AT usgcrp Dot gov
http://www.globalchange.gov

**Comment by justgo129** [comment]
I'm spinning up the Annales_de_chimie journal ISSN issue to:
https://github.com/USGCRP/gcis/issues/177

so that the rest of this "issue" can address the larger question of the ISSN requirement.

**Comment by justgo129** [comment]
@rewolfe @bduggan after some work with generics, I ran the code described above and confirmed that every journal on stage has an ISSN.  As such, I'd like to reopen this issue per the above discussion, and it seems that I don't have permissions to reopen the issue.  Thanks!

**Comment by bduggan** [comment]
There are two journals with invalid ISSNs-- once these are fixed I can use the postgres [isn](http://www.postgresql.org/docs/9.3/static/isn.html) module to add constraints to our data.  The two invalid ones (see [check-issns.pl](https://github.com/USGCRP/gcis-scripts/blob/master/check-issns.pl)) are:
```
Invalid online issn: 545-7885 for /journal/plos-biology
Invalid print issn: 2010-2244 for /journal/journal-water-climate-change
```

**Comment by justgo129** [comment]
Corrected.  Used ISSN provided by Worldcat for the former, and from the journal's website for the latter.

**Comment by bduggan** [comment]
This is done.
