### ISSUE TITLE
Usage of dcterms:InteractiveResource

### ISSUE THREAD

**Issue by zednis** [USGCRP/gcis#150]
We are using dcterms:InteractiveResource to describe the computing environment of an activity.

from [activity/object.ttl.tut](http://github.com/usgcrp/gcis/blob/master/lib/Tuba/files/templates/activity/object.ttl.tut)
```
## Computing environment
   dcterms:InteractiveResource "<%= $activity->computing_environment %>"^^xsd:string;
```

1) We are using InteractiveResource as a property here instead of as a class
2) InteractiveResource is not in the dcterms namespace.  It is in the dctype namespace.
3) The intended semantics of dctype:InteractiveResource do not match how we are intending to use it

from http://dublincore.org/documents/dcmi-terms/#dcmitype-InteractiveResource

*definition:* A resource requiring interaction from the user to be understood, executed, or experienced.
*examples:* Examples include forms on Web pages, applets, multimedia learning objects, chat services, or virtual reality environments.

examples of usage from the dublin core RDF user guide: (BTW - not a great example)

```
ex:myStuff dcterms:type dctype:InteractiveResource , 
                        dctype:Text .

dctype:InteractiveResource rdfs:label "Interactive Resource" .

dctype:Text rdfs:label "Text" .
```

I suggest we find an alternate property to represent the computing environment for the activity.

**Comment by justgo129** [comment]
I agree and can state for the record that I wasn't pleased with the selection of this term for the reasons provided.  It was however, the best of the bad choices.  Much time was spent using Sindice, and looking at various vocabularies to no avail.  Dbpedia wasn't much help here either.  So yes, any insights you have into this one are much appreciated, @zednis.

**Comment by zednis** [comment]
I know some people :sunglasses: 

I'll ask around

**Comment by bduggan** [comment]
I suggest we remove this from the RDF in order to make progress on usgcrp/gcis-ontology#12.  Once a better term is found or created, it can be used and we can create a new issue.

**Comment by zednis** [comment]
I believe we ended up also discussing this as part of USGCRP/gcis-ontology/issues/7 where the following suggestion was proposed:

For computing environment, I found the property dbpedia-owl:computingPlatform that I think is close to what we want to say - but it is an object property so we would need to use it with resources and not string values. Also, the domain of the property is dbpedia-owl:Software, so we would want to associate it not with the activity but with the software agent associated with the activity.

http://dbpedia.org/ontology/computingPlatform

edit: I think it would end up looking like this
```
<http://data.globalchange.gov/activity/0158fa86-nca3-ghcn-daily-r201305-process>
   dcterms:identifier "0158fa86-nca3-ghcn-daily-r201305-process";
   dcterms:description "..."^^xsd:string;

   prov:qualifiedAssociation [
      a prov:Association ;
      prov:agent [ 
         a prov:SoftwareAgent, gcis:Software, dbpedia-owl:Software ;
         rdfs:label "IDL (version 8.0)"^xsd:string ;
         dbpedia-owl:computingPlatform [ rdfs:label "Mac OS X (darwin x86_64 m64)"^^xsd:string; ] ;
      ] ;
      prov:hadPlan [
         a prov:Plan, meth:Methodology ;
         rdf:value "..."^^xsd:string;
      ] ;
   ] ;

   a prov:Activity .
```
note - I removed the fortran and linux values from the agent and computing platform descriptions.

I think to reliably capture multiple agents and their associated computing platforms we will have to collect this information in a more structured manner.

**Comment by bduggan** [comment]
On Tuesday, June 23, Stephan Zednik wrote: 
> I think to reliably capture multiple agents and their associated computing platforms we will have to collect this information in a more structured manner.
> 

Yes, and unfortunately until then, we can't break up fields like this; it's all
or nothing.

Brian

**Comment by zednis** [comment]
I assume there are no conventions for breaking up values by semicolons or other characters so it would be futile to make a 'best guess' attempt at parsing the values?

**Comment by bduggan** [comment]
On Tuesday, June 23, Stephan Zednik wrote: 
> I assume there are no conventions for breaking up values by semicolons or other characters so it would be futile to make a 'best guess' attempt at parsing the values?
 
Unfortunately not, this was collected as a free-form descriptive field.

Brian

**Comment by zednis** [comment]
ok, then I think our options (ordered by my preference) are:
1) Define a new datatype property in the GCIS ontology such as ``gcis:descriptionOfComputingEnvironmentsUsed``, associate it with the ``prov:Activity`.
2) Leave this information out of the RDF
3) Use ``dbpedia-owl:computingPlatform`` as suggested above and just live with the likelihood of several different platforms being included in the ``rdf:value`` value.

**Comment by justgo129** [comment]
I like the first option.

**Comment by bduggan** [comment]
I'm okay with any of those.

Brian

**Comment by zednis** [comment]
ok, I'll create pull requests in both gcis and gcis-ontology repos based on option 1.

**Comment by zednis** [comment]
Pull requested created for the ontology.  If there is agreement and that request can be merged then I will make a proposed update to the RDF-generating templates.

**Comment by justgo129** [comment]
Fine with me.


On Tue, Jun 23, 2015 at 1:33 PM, Stephan Zednik <notifications@github.com>
wrote:

> Pull requested created for the ontology. If there is agreement and that
> request can be merged then I will make a proposed update to the
> RDF-generating templates.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGCRP/gcis/issues/150#issuecomment-114582026>.
>



-- 
_________________________________
Justin Goldstein, Ph.D.
Advance Science Climate Data and Observing Systems Coordinator
US Global Change Research Program
1717 Pennsylvania Ave NW, Suite #250
Washington, DC 20006

O: (202) 419-3496
M: (202) 285-3005

e-mail: jgoldstein AT usgcrp Dot gov
http://www.globalchange.gov

**Comment by justgo129** [comment]
Given that https://github.com/USGCRP/gcis-ontology/pull/21 and https://github.com/USGCRP/gcis/issues/175
have been merged, are we good to close this specific (#150) issue?

**Comment by bduggan** [comment]
No, activity/object.ttl.tut has not been updated.

**Comment by zednis** [comment]
@bduggan do you want to commit/propose the template update, or shall I?

**Comment by bduggan** [comment]
Please feel free to go ahead with a pull request
