### ISSUE TITLE
skos concept references in 'also known as section'

### ISSUE THREAD

**Issue by zednis** [USGCRP/gcis#152]
from https://data.globalchange.gov/dataset/nasa-nsidcdaac-0032.ttl

```
## Also known as:
<http://data.globalchange.gov/dataset/nasa-nsidcdaac-0032>
   skos:altLabel "oai:nsidc/NSIDC-0032";
   gcis:hasURL "http://nsidc.org/api/dataset/2/oai?verb=GetRecord&metadataPrefix=dif&identifier=oai:nsidc/NSIDC-0032";
   skos:Concept <http://data.globalchange.gov/lexicon/nsidc> .
```

What are we trying to say with the statement that currently uses skos:Concept as a property?

skos:Concept is a class and should not be used as a property.

If we are 'tagging' this resource with a skos:Concept we should use dcterms:subject or similar.  The correct property to use here depends on the semantics of the tagging relationship.

dcterms:subject is a good general-purpose predicate to use in this case because it has the following definition:

*definition:* The topic of the resource.
*comment:* Typically, the subject will be represented using keywords, key phrases, or classification codes. Recommended best practice is to use a controlled vocabulary.

My guess is that we should replace skos:Concept here with dcterms:subject so the example above looks like
```
## Also known as:
<http://data.globalchange.gov/dataset/nasa-nsidcdaac-0032>
   skos:altLabel "oai:nsidc/NSIDC-0032";
   gcis:hasURL "http://nsidc.org/api/dataset/2/oai?verb=GetRecord&metadataPrefix=dif&identifier=oai:nsidc/NSIDC-0032";
   dcterms:subject <http://data.globalchange.gov/lexicon/nsidc> .
```
but I would like to know more about what we are attempting to say here.  Are we attempting to say that the NSIDC lexicon is a topic of this dataset?  I am not confident that is what we are trying to say.

**Comment by bduggan** [comment]
The nsidc lexicon is a set of identifiers which can be mapped to gcis URIs.  Closest is probably a [void:Linkset](http://www.w3.org/TR/void/#linkset), with the caveat that the NSIDC identifiers might not be in another RDF dataset.

**Comment by zednis** [comment]
Would it make sense to say that <http://data.globalchange.gov/lexicon/nsidc> is the topic of <http://data.globalchange.gov/dataset/nasa-nsidcdaac-0032>?

**Comment by bduggan** [comment]
No, that doesn't make sense to me.  Multiple organizations/communities may have lexicons which are groups of identifiers for a GCIS resource, so it's the other way around: a term associated with a lexicon has the dataset as a topic (though I may need to see a definition or some examples of the use of the phrase "topic" to say for sure).

**Comment by zednis** [comment]
Ok, we have a couple issues here then.

1) a lexicon would not be skos:Concept but a skos:ConceptScheme.

2) a term in a lexicon would definitely not have a dataset as a topic.

I think we have the modeling here backward.  Perhaps a few examples would help?

**Comment by bduggan** [comment]
On Tuesday, June  9, Stephan Zednik wrote: 
> 1) a lexicon would not be skos:Concept but a skos:ConceptScheme.

Excellent, sounds good.

> 2) a term in a lexicon would definitely not have a dataset as a topic.

Okay.

> I think we have the modeling here backward.  Perhaps a few examples would help?

For examples, you can take a look at

    http://data.globalchange.gov/lexicon

and click on the various identifiers to see the terms in the lexicon.

I tried to flush out some of the ideas in this paper:

    http://events.linkeddata.org/ldow2015/papers/ldow2015_paper_12.pdf

Brian

**Comment by zednis** [comment]
Okay, I think I understand what you are trying to say now.  

You are trying to establish equivalence between the dataset resource and the lexicon term (represented as a skos:Concept).

Does this look like what you are intending to say?

```
<http://data.globalchange.gov/dataset/nasa-nsidcdaac-0032>
  owl:sameAs <http://data.globalchange.gov/lexicon/nsidc/dataset/nasa-nsidcdaac-0032> .
```

**Comment by zednis** [comment]
``skos:exactMatch`` is an alternative to ``owl:sameAs`` that does not carry the same implications when an OWL reasoner is used.

```
<http://data.globalchange.gov/dataset/nasa-nsidcdaac-0032>
  skos:exactMatch <http://data.globalchange.gov/lexicon/nsidc/dataset/nasa-nsidcdaac-0032> .
```

The [SKOS Primer](http://www.w3.org/TR/skos-primer/) on skos:exactMatch vs owl:sameAs
> Note on skos:exactMatch vs. owl:sameAs: SKOS provides skos:exactMatch to map concepts with equivalent meaning, and intentionally does not use owl:sameAs from the OWL ontology language [OWL]. When two resources are linked with owl:sameAs they are considered to be the same resource, and triples involving these resources are merged. This does not fit what is needed in most SKOS applications. In the above example, ex1:animal is said to be equivalent to ex2:animals. If this equivalence relation were represented using owl:sameAs, the following statements would hold for ex:animal:

> ```ex1:animal rdf:type skos:Concept;```
> ```  skos:prefLabel "animal"@en;```
> ```  skos:inScheme ex1:referenceAnimalScheme.```
> ```  skos:prefLabel "animals"@en;```
> ```  skos:inScheme ex2:eggSellerScheme.```

> This would make ex:animal inconsistent, as a concept cannot possess two different preferred labels in the same language. Had the concepts been assigned other information, such as semantic relationships to other concepts, or notes, these would be merged as well, causing these concepts to acquire new meanings.

**Comment by zednis** [comment]
The more I think about it the more I like the idea of using ``skos:exactMatch`` so as to avoid possible label issues.

**Comment by bduggan** [comment]
On Wednesday, June 10, Stephan Zednik wrote: 
> The more I think about it the more I like the idea of using ``skos:exactMatch`` so as to avoid possible label issues.

Sounds good for most of our cases.  It actually generates owl:sameAs when the
term is also part of an RDF dataset (dbpedia is the only one)

http://data.globalchange.gov/platform/topex-poseidon.thtml

```
<http://data.globalchange.gov/platform/topex-poseidon>
   owl:sameAs <http://dbpedia.org/resource/TOPEX/Poseidon>;
```

**Comment by zednis** [comment]
I think to avoid potential issues with the property copying and transitivity of ``owl:sameAs`` we should use ``skos:exactMatch`` - which is the preferred property to use for mapping terms between skos vocabularies.

I will update the pull request use ``skos:exactMatch``.

**Comment by bduggan** [comment]
Most important to me is that we have solid examples to connect the GCIS resources to other places, whether with skos:exactMatch or owl:sameas.  One resource I noticed that does this is sameas.org, e.g. <http://sameas.org?uri=http://dbpedia.org/resource/Jason-1> -- I would like to see <http://data.globalchange.gov/platform/jason-1> appear in this list.  Is this a reasonable idea and/or does this require the use of skos:exactMatch and/or owl:sameAs?

**Comment by zednis** [comment]
The sameas.org site is an interesting use case but I do not think it affects our decision in this case.

In this case we are attempting to map different lexicon terms to GCIS resources.  For the reasons mentioned in the above quote from the SKOS Primer, owl:sameAs is not the best property to use to map terms from different lexicons/concept schemes.

I do see one issue with my current pull request that will need to be updated - I will make a comment on the pull request itself.

**Comment by bduggan** [comment]
I see, thanks, the example makes sense.  I see how mapping from terms to resources should use skos:exactMatch, since the term does not have, for instance, a launchDate, and a platform is not a concept.  With this in mind, does it still make sense to map from a gcis resource to a resource in another RDF dataset?

i.e.
```
@prefix gcisplatform <http://data.globalchange.gov/platform/>
@prefix ceosmission <http://data.globalchange.gov/lexicon/ceos/Mission/>
@prefix dbpedia <http://dbpedia.org/resource/>

gcisplatform:jason-1
   skos:exactMatch ceosmission:Jason-1
gcisplatform:jason-1
   owl:sameAs dbpedia:Jason-1
```
In this case it seems to me that the attributes of the owl:sameAs resources would be the same.

**Comment by zednis** [comment]
It can make sense to use ``owl:sameAs`` between resources in different RDF datasets (e.g. dbpedia and GCIS).  We will just want to be careful with since the semantics of sameAs are "all properties of A are properties of B and vice versa" and since sameAs is transitive.  So, it does make sense to use it but use it with caution when you do use it.

**Comment by bduggan** [comment]
Agreed, and

> [..] "all properties of A are properties of B and vice versa" [..]

applying Leibniz's law (or is it the converse?) we may say this is
true if A and B are the same physical entity, i.e. the dbpedia article
is about the same physical spacecraft as the platform identified in GCIS.
Given that these are the same physical thing, I would say it is not
necessary to enumerate the properties and ensure that they match:
if they don't match, then the error is in the properties, not in the
assertion of sameness.

**Comment by xgmachina** [comment]
So, would l say that, for the mapping between two skos concepts we recommend skos:exactMatch, for other cases we can use owl:sameAs.

**Comment by zednis** [comment]
note, the domain and range of ``skos:exactMatch`` is ``skos:Concept``.

If we use ``skos:exactMatch`` the following is inferable:
```
<http://data.globalchange.gov/dataset/nasa-nsidcdaac-0032>
  a skos:Concept .
```

I think this is fine.

**Comment by bduggan** [comment]
On Tuesday, June 16, Stephan Zednik wrote: 
> note, the domain and range of ``skos:exactMatch`` is ``skos:Concept``.
> 
> If we use ``skos:exactMatch`` the following is inferable:
> ```
> <http://data.globalchange.gov/dataset/nasa-nsidcdaac-0032>
>   a skos:Concept .
> ```
> 
> I think this is fine.

But would that mean owl:sameAs could not be used for this
resource because it would imply that another resource (in
another dataset) is also a skos:Concept?

**Comment by xgmachina** [comment]
Let's see the definition of those two properties in their original design:
From: http://www.w3.org/2002/07/owl# 
owl:sameAs a rdf:Property ;
     rdfs:label "sameAs" ;
     rdfs:comment "The property that determines that two given individuals are equal." ;
     rdfs:domain owl:Thing ;
     rdfs:isDefinedBy <http://www.w3.org/2002/07/owl#> ;
     rdfs:range owl:Thing . 

And, from: http://www.w3.org/2009/08/skos-reference/skos.rdf
<rdf:Description rdf:about="#exactMatch">
<rdfs:label xml:lang="en">has exact match</rdfs:label>
<rdfs:isDefinedBy rdf:resource="http://www.w3.org/2004/02/skos/core"/>
<skos:definition xml:lang="en">skos:exactMatch is used to link two concepts, indicating a high degree of confidence that the concepts can be used interchangeably across a wide range of information retrieval applications. skos:exactMatch is a transitive property, and is a sub-property of skos:closeMatch.</skos:definition>
<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#ObjectProperty"/>
<rdfs:subPropertyOf rdf:resource="#closeMatch"/>
<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#SymmetricProperty"/>
<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#TransitiveProperty"/>
<rdfs:comment xml:lang="en">skos:exactMatch is disjoint with each of the properties skos:broadMatch and skos:relatedMatch.</rdfs:comment>
<rdf:type rdf:resource="http://www.w3.org/1999/02/22-rdf-syntax-ns#Property"/>
</rdf:Description>

**Comment by zednis** [comment]
@bduggan If OWL reasoning was applied that would be the inference, but I am not sure that that means that ``owl:sameAs`` could not be used.  ``skos:Concept`` is not necessarily disjoint with the type information of resources from external RDF datasets.

That said, there are arguments in the literature calling for low to no use of ``owl:sameAs``.

``owl:sameAs`` has long-reaching implications.  It is symmetric and transitive.  It does not work well with skos concepts is because it would cause ``skos:inScheme`` and ``skos:prefLabel`` statements to be shared across terms in different controlled vocabularies.

``owl:sameAs`` is often used when a the linked data author wants to say that two or more resources represent the same thing (dataset, person, instrument), but what it actually means is that the informational resources in linked data are equivalent and have the same properties/values.  It is effectively that the description records of the thing are identical.

Here is a paper that provides some analysis of ``owl:sameAs`` in linked data:
http://www.w3.org/2009/12/rdf-ws/papers/ws21

**Comment by bduggan** [comment]
On Tuesday, June 16, Stephan Zednik wrote: 
> @bduggan If OWL reasoning was applied that would be the inference, but I am not sure that that means that ``owl:sameAs`` could not be used.  ``skos:Concept`` is not necessarily disjoint with the type information of resources from external RDF datasets.
> 

Okay, sounds good.

> Here is a paper that provides some analysis of ``owl:sameAs`` in linked data:
> http://www.w3.org/2009/12/rdf-ws/papers/ws21
> 

I actually referenced that one in my paper:

"The representation of linksets can be further refined with careful use
of “owl:sameAs” [6] and other relationships."
