### ISSUE TITLE
usage of places:Country

### ISSUE THREAD

**Issue by zednis** [USGCRP/gcis#153]
[lib/Tuba/files/templates/organization/object.ttl.tut](lib/Tuba/files/templates/organization/object.ttl.tut) uses the place:Country class as a property.

```
% if (my $country = $organization->country) {
   place:Country "<%= $country->name %>"^^xsd:string;
% }
```

We should update this so place:Country is used as a class.  We will need to determine the best property to use to relate the organization to a country.

I didn't see any properties in the GCIS ontology or dublin core that seemed like the right fit.

Likewise the W3C Organization Ontology did not have anything that looked promising.  (there is place:in - but that is intended to relate one place to another place).

Dbpedia has a country property that looks good, but it doesn't look like we are using dbpedia anywhere else at present.  

http://dbpedia.org/ontology/country
*comment*: The country where the thing is located.

```
% if (my $country = $organization->country) {
   dbpedia:country [ 
      a place:Country ;
      rdfs:label "<%= $country->name %>"^^xsd:string;
   ] ;
% }
```

I think from my (very cursory) search that the dbpedia:country property is the best candidate.

**Comment by justgo129** [comment]
I think I saw something in the FAO geopolitical ontology awhile back but no longer see it.
http://datahub.io/dataset/fao-geopolitical-ontology

Yes, I'm definitely fine with dbpedia.

**Comment by bduggan** [comment]
The list and [representation](https://github.com/USGCRP/gcis/blob/master/db/dist/docs/pod/table_country.pod) of countries in GCIS comes from [ISO 3166-1 alpha 2](http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2).  The two-letter codes are stored in the database.  We could certainly expose them (just call $country->code instead of $country->name).

**Comment by justgo129** [comment]
We also call "country" when referring to journals.
https://github.com/USGCRP/gcis/blob/master/db/dist/docs/pod/table_journal.pod

even though it doesn't show up in the html:
https://data.globalchange.gov/journal/geophysical-research-letters

**Comment by zednis** [comment]
What are the desired semantics of the relationship between a journal and country?

**Comment by rewolfe** [comment]
The country is the location where the journal is published.

The country does show up in the other serializations (e.g. yaml).

On Fri, May 29, 2015 at 6:01 PM, Stephan Zednik <notifications@github.com>
wrote:

> What are the desired semantics of the relationship between a journal and
> country?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGCRP/gcis/issues/153#issuecomment-106945802>.
>



-- 
Robert Wolfe, NASA GSFC @ USGCRP, o: 202-419-3470, m: 301-257-6966

**Comment by zednis** [comment]
```
dbpedia-owl:country
  rdfs:comment "The country where the thing is located" ;
  rdfs:subPropertyOf dul:hasLocation .
```

The definition of dull:hasLocation is available at http://www.loa.istc.cnr.it/ontologies/DUL.owl.

Based on the definition I would say dbpedia-owl:country is a good property to use when the subject is located in a country.  I believe this meets some but not all of our uses.

I think this does work for organizations but I am not sure for journals.

My suggestions for the organization template are as follows:
1) use dbpedia-owl:country to reference the country
2) Define resources for countries based on the ISO 3166-1 alpha 2 country code.
3) have the organization template reference the country resource URI.

```
% if (my $country = $organization->country) {
   dbpedia-owl:country <<%= $uri(country->code) %>>;
% }
```

**Comment by justgo129** [comment]
Could we create a variation of dbpedia-owl:country to use with journals, restricting dbpedia-owl to other gcis entities?

**Comment by zednis** [comment]
I believe the issue is that ``dbpedia-owl:country`` is a sub-property of ``dul:hasLocation`` so it inherits the semantics that the property is used to state the relative location of the resource.

What I think we want in this case is a property with the definition "country (or location) of publication".

I will spend some time looking for an appropriate property and if I can't find one in any common publication vocabularies we could create one for the GCIS ontology.

**Comment by justgo129** [comment]
Thanks, Stephan.

**Comment by justgo129** [comment]
@zednis were you able to locate an appropriate property?

**Comment by bduggan** [comment]
I've removed the invalid use of the class property, so that we can make progress on
https://github.com/USGCRP/gcis-ontology/issues/12
