### ISSUE TITLE
usage of dcterms:RightsStatement

### ISSUE THREAD

**Issue by zednis** [USGCRP/gcis#154]
[lib/Tuba/files/templates/figure/object.ttl.tut](lib/Tuba/files/templates/figure/object.ttl.tut) uses dcterms:RightsStatement as a property.

```
## Tags:
   dcterms:subject "<%= $image->attributes %>"^^xsd:string;
   dcterms:RightsStatement "<%= $image->usage_limits %>"^^xsd:string;
```

We should use the property [dcterms:rights](https://github.com/USGCRP/gcis/blob/master/lib/Tuba/files/templates/image/object.ttl.tut) which has the domain dcterms:RightsStatement.

This link provides an example of the usage of dcterms:rights in RDF
http://wiki.dublincore.org/index.php/User_Guide/Publishing_Metadata#dcterms:rights

I recommend changing the template to look like this
```
dcterms:rights [ rdf:value "<%= $image->usage_limits %>"^^xsd:string; ] ;
```

The instance data after this update would look like this:
```
  dcterms:rights [ rdf:value "Free to use with credit to the original figure source."^^xsd:string;  ] ;
```

**Comment by bduggan** [comment]
Sounds fine to me.

**Comment by justgo129** [comment]
Same here.

**Comment by justgo129** [comment]
See pull request #160

**Comment by justgo129** [comment]
Given #160, I am good to close this ticket.
