### ISSUE TITLE
spatial and temporal extent descriptions

### ISSUE THREAD

**Issue by zednis** [USGCRP/gcis#155]
We should update the dataset template to use dcterms:spatial and dcterms:temporal.

[lib/Tuba/files/templates/dataset/object.ttl.tut](http://github.com/usgcrp/gcis/blob/master/lib/Tuba/files/templates/dataset/object.ttl.tut)

```
## Projection and resolution:
   gcis:spatialExtents "<%= $dataset->spatial_extent %>";
   dwc:geodeticDatum "<%= $dataset->spatial_ref_sys %>";
   gcis:spatialResolution "<%= $dataset->spatial_res %>"^^xsd:string;
   gcis:TemporalExtents "<%= $dataset->temporal_extent %>";
   dcterms:verticalExtents "<%= $dataset->vertical_extent %>";
```

The GCIS ontology has several properties that can be used to describe a spatial or temporal extents.

Can we use the values from  ``<%= $dataset->spatial_extent %>`` and ``<%= $dataset->temporal_extent %>`` to extract the information for these properties?  

Also, are these the properties we want to use to describe the spatial and temporal extents?

```
gcis:extentTypeCode a owl:DatatypeProperty ;
	rdfs:label "Extent Type Code" ;
	rdfs:comment "The extent type code of a spatial extent." ;
	rdfs:domain gcis:SpatialExtents ;
	rdfs:range xsd:string .

gcis:westBoundLongitude a owl:DatatypeProperty ;
	rdfs:label "West Bound Longitude" ;
	rdfs:comment "The value of west bound longitude." ;
	rdfs:domain gcis:SpatialExtents ;
	rdfs:range xsd:float .

gcis:eastBoundLongitude a owl:DatatypeProperty ;
	rdfs:label "East Bound Longitude" ;
	rdfs:comment "The value of east bound longitude." ;
	rdfs:domain gcis:SpatialExtents ;
	rdfs:range xsd:float .

gcis:southBoundLatitude a owl:DatatypeProperty ;
	rdfs:label "South Bound Latitude" ;
	rdfs:comment "the value of south bound latitude." ;
	rdfs:domain gcis:SpatialExtents ;
	rdfs:range xsd:float .

gcis:northBoundLatitude a owl:DatatypeProperty ;
	rdfs:label "North Bound Latitude" ;
	rdfs:comment "The value of north bound latitude." ;
	rdfs:domain gcis:SpatialExtents ;
	rdfs:range xsd:float .

gcis:startedAt a owl:DatatypeProperty ;
	rdfs:label "Started At" ;
	rdfs:comment "The start date/time of a temporal extent." ;
	rdfs:domain gcis:TemporalExtents ;
	rdfs:range xsd:dateTime .

gcis:endedAt a owl:DatatypeProperty ;
	rdfs:label "Ended At" ;
	rdfs:comment "The end date/time of a temporal extent." ;
	rdfs:domain gcis:TemporalExtents ;
	rdfs:range xsd:dateTime .
```

**Comment by bduggan** [comment]
We store both descriptive and quantitative representations of spatial and temporal extent in the [dataset table](https://github.com/USGCRP/gcis/blob/master/db/dist/docs/pod/table_dataset.pod) i.e. there is lat/lon+min/max as well as "spatial_extent".  Also there is both start/end+time as well as "temporal_extent".

**Comment by zednis** [comment]
I made some comments about geosparql in USGCRP/gcis-ontology/issues/6.

I think we should evaluate using geosparql.  let's pick an example that has spatial coordinate information and prototype what it would look like if we used geosparql to describe the spatial geometry.

**Comment by xgmachina** [comment]
Some information from the GeoSparql document:
8.3.1.1 Property: geo:hasGeometry
The property geo:hasGeometry is used to link a feature with a geometry that represents its spatial extent. A given feature may have many associated geometries.
```
geo:hasGeometry a rdf:Property,
owl:ObjectProperty;
rdfs:isDefinedBy <http://www.opengis.net/spec/geosparql/1.0>;
rdfs:label "has Geometry"@en;
rdfs:comment "A spatial representation for a given feature."@en;
rdfs:domain geo:Feature;
rdfs:range geo:Geometry .
```

8.4 Standard Properties for geo:Geometry
Properties are defined for describing geometry metadata. Implementations shall allow the properties geo:dimension, geo:coordinateDimension, geo:spatialDimension, geo:isEmpty, geo:isSimple, geo:hasSerialization to be used in SPARQL graph patterns.

**Comment by justgo129** [comment]
Do we have a consensus to go with geosparql?

**Comment by zednis** [comment]
With geosparql we would be serializing location or polygon information using WKT or GML.

example from another project I am working on:
```
<http://woodshole.er.usgs.gov/data/coastal_features_and_waterways/1008296>
	a gnis:Bay, geo:Feature ;
	rdfs:label  "Albemarle Sound"^^xsd:string ;
	geo:hasGeometry [ 
		a sf:Polygon ;
		geo:asWKT "POLYGON ((-76.74 35.95, -76.66 35.92, -76.06 35.98, -75.85 35.96, -75.66 35.92, -75.72 36.04, -75.80 36.07, -75.86 36.13, -75.91 36.17, -76.64 36.04, -76.74 35.95))"^^geo:wktLiteral ;
	] .
```

A single point could be serialized like this:
```
ex:location
      a geo:Feature ;
      geo:hasGeometry [
            a sf:Point ;
           geo:asWKT “Point(33.95 -83.38)”^^geo:wktLiteral ;
      ] .
```

You can also embed coordinate systems in the geometry serialization like so:
```
ex:location
      a geo:Feature ;
      geo:hasGeometry [
            a sf:Point ;
            geo:asWKT “<http://www.opengis.net/def/crs/EPSG/0/4326>
Point(-83.38 33.95)”^^geo:wktLiteral ;
      ] .
```

**Comment by justgo129** [comment]
As I'm not as familiar with geosparql, I'll defer to @rewolfe, @aulenbac, and @bduggan.  Looks fine to me though.

**Comment by zednis** [comment]
I think the biggest question is whether we are willing to translate what we have in the postgres db to WKT or GML.  The big benefit of WKT and GML serializations over custom properties like we have right now is that they are well-known standards and mapping tools may be able to ingest them directly.

**Comment by justgo129** [comment]
@rewolfe shall we defer this discussion?

**Comment by bduggan** [comment]
If anyone wants to transform the existing templates to use geoSparql using the existing bounding box data that would be fine.  I am closing this issue and marking it as "wishlist" since nobody is taking it on.
