### ISSUE TITLE
Names containing first and middle initials vis-a-vis URLs

### ISSUE THREAD

**Issue by justgo129** [USGCRP/gcis#161]
As part of the last code update, support was added for contributors' names within URL, e.g.:
http://data.globalchange.gov/person/Andrew_Buddenberg

now resolves, redirecting to:
http://data.globalchange.gov/person/1948

Please advise as to the correct URL be for pages referring to contributors' who use their first initial, along with their middle and last names?  e.g. for C. Ben Beard:
http://data.globalchange.gov/person/903

as neither:
http://data.globalchange.gov/person/C_Ben_Beard
http://data.globalchange.gov/person/C%20Ben%20Beard
resolve.

and similarly for those who use "first name, middle initial, and last name"

e.g.:
http://data.globalchange.gov/person/2308
since http://data.globalchange.gov/person/elizabeth_a_ainsworth doesn't resolve.

Thanks.

**Comment by bduggan** [comment]
Both examples have a period in the name, which causes the redirect to not work.  There's no support for redirects for names with periods.  Periods in the URLs are reserved for suffixes (.json, .thtml, etc).
