### ISSUE TITLE
Lexicon RDF issues

### ISSUE THREAD

**Issue by zednis** [USGCRP/gcis#165]
I believe there may be errors in the RDF generated for http://data.globalchange.gov/lexicon/nsidc (and in other lexicons generated using the same template)

The RDF we are currently generating looks like this:
```
<http://data.globalchange.gov/lexicon/nsidc>
   dcterms:identifier "nsidc";
   dcterms:title "National Snow and Ice Data Center NASA DAAC lexicon"^^xsd:string;
   gcis:hasURL "http://nsidc.org/api/opensearch/index.html"^^xsd:anyURI;

   a skos:Concept, dbpedia:Lexicon .

</instrument/advanced-microwave-scanning-radiometer-eos>
   a skos:Concept;
   skos:altLabel "AMSR-E".
```

The </instrument/x> URI is not a HTTP URI and will be interpreted as the following when read by a RDF library.

```
<file:///instrument/advanced-microwave-scanning-radiometer-eos>
        <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>  skos:Concept ;
        skos:altLabel  "AMSR-E" .
```

Do we want this URI to instead be <http://data.globalchange.gov/lexicon/nsidc/instrument/advanced-microwave-scanning-radiometer-eos> ?

Also, the lexicon resource should have type **skos:ConceptScheme** instead of **skos:Concept**.

It is my guess that we want the generated RDF to look like this:
```
<http://data.globalchange.gov/lexicon/nsidc>
   dcterms:identifier "nsidc";
   dcterms:title "National Snow and Ice Data Center NASA DAAC lexicon"^^xsd:string;
   gcis:hasURL "http://nsidc.org/api/opensearch/index.html"^^xsd:anyURI;
   a skos:ConceptScheme, dbpedia:Lexicon .

<http://data.globalchange.gov/lexicon/nsidc/instrument/advanced-microwave-scanning-radiometer-eos>
   a skos:Concept;
   skos:inScheme <http://data.globalchange.gov/lexicon/nsidc> ;
   skos:altLabel "AMSR-E".
```

**Comment by bduggan** [comment]
Yes, your guess is correct :)

Brian

p.s. we may add void at some point too, but that's another issue.

**Comment by zednis** [comment]
Awesome, I will create a pull request with the edits to the template.

follow-up question - is there a prefLabel for the concepts?  I see we have a altLabel for all the terms in the NSIDC lexicon but no prefLabels

**Comment by rewolfe** [comment]
Isn't our prefLable the GCIS ID (GCID)?

 e.g. prefLabel is "/instrument/advanced-microwave-scanning-radiometer";
altLabel (from NSIDC Sensor lexicon) is "AMSR"

Is the NSIDC "Sensor" lexicon implied (vs. the NSIDC "Source" lexicon)?

On Tue, Jun 9, 2015 at 1:52 PM, Stephan Zednik <notifications@github.com>
wrote:

> Awesome, I will create a pull request with the edits to the template.
>
> follow-up question - is there a prefLabel for the concepts? I see we have
> a altLabel for all the terms in the NSIDC lexicon but no prefLabels
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGCRP/gcis/issues/165#issuecomment-110445484>.
>



-- 
Robert Wolfe, NASA GSFC @ USGCRP, o: 202-419-3470, m: 301-257-6966

**Comment by zednis** [comment]
The GCISID (which the lexicon paper informs me is the resource URI) is not a label.

We could update the RDF to look like this:
```
<http://data.globalchange.gov/lexicon/nsidc/instrument/advanced-microwave-scanning-radiometer-eos>
   a skos:Concept;
   skos:inScheme <http://data.globalchange.gov/lexicon/nsidc> ;
   skos:prefLabel "instrument/advanced-microwave-scanning-radiometer-eos" ;
   skos:altLabel "AMSR-E".
```

**Comment by bduggan** [comment]
I think if there were a prefLabel it would correspond to
a term created by the community associated with the lexicon,
(just as altLabel is a term created by the community associated
with the lexicon) not with an identifier created within GCIS.

At this point, we don't have any such terms, so I don't think
we have any prefLabels.

Brian

**Comment by bduggan** [comment]
An example would be multiple dbpedia URIs that all redirect to one common one: the common one would be the prefLabel, the others would be altLabels. (but we aren't harvesting that information)

**Comment by zednis** [comment]
So should we change altLabel to prefLabel in the template?

**Comment by rewolfe** [comment]
Brian, How about using the "name" of the Instrument as the preferred label?

**Comment by zednis** [comment]
@rewolfe That does make sense.

Would that make the prefLabel of our example "Advanced Microwave Scanning Radiometer - EOS"?

**Comment by bduggan** [comment]
If the "name" comes from GCIS this isn't "created by
the community associated with the lexicon".  The name
we have is a label for the GCIS resource, but not necessarily
a label for the term in the lexicon.

**Comment by bduggan** [comment]
By the way, one of the notions I put into the slides for the talk was that
an equivalent definition of a "term" for us is a skos [lexical label](http://www.w3.org/TR/skos-reference/#labels)
used as an identifier.  Not sure if I'm expressing that sentiment in RDF
or not, but that's in the back of my mind.

**Comment by zednis** [comment]
If you intend for the skos lexical label to be used to identify the term then it would make sense to use skos:prefLabel.

from http://www.w3.org/TR/skos-primer/#seclabel
> Following common practice in KOS design, the preferred label of a concept may also be used to unambiguously represent this concept within a KOS and its applications. So even though the SKOS data model does not formally enforce it, it is recommended that no two concepts in the same KOS be given the same preferred lexical label for any given language tag.

The skos:altLabel property is generally intended to be used with synonyms or abbreviations.

> The skos:altLabel property makes it possible to assign an alternative lexical label to a concept. This is especially helpful when assigning labels beyond the one that is preferred for the concept, for instance when synonyms need to be represented:

**Comment by zednis** [comment]
any new thoughts on this?

summary: we made updates to the SKOS templates so that they are now generating GCIDs with the correct URIs, but we have an open question on whether the SKSO concepts should have prefLabels or not.

**Comment by bduggan** [comment]
Yes, I think using prefLabel instead of altLabel in the example above makes sense.   Keeping in mind that it is a label for the "term" not for the GCIS resource.  (as the RDF says)

**Comment by justgo129** [comment]
skos:altLabel changed to skos:prefLabel.  Pull request submitted at:
https://github.com/USGCRP/gcis/pull/185

**Comment by justgo129** [comment]
With #185 merged, are we good to close this issue?

**Comment by bduggan** [comment]
Yes.
