### ISSUE TITLE
isCitedBy, isReferencedBy

### ISSUE THREAD

**Issue by justgo129** [USGCRP/gcis#166]
@zednis @bduggan @aulenbac @rewolfe @BNewman2104 I don't know whether this would be an ontology question or a dev one so I'm posting it here.  

Most pubs in GCIS have references for which their representation in endnote had only one UUID regardless of the quantity of identical references.  An example is at  http://data.globalchange.gov/report/federal-actions-climate-resilient-nation.thtml 
which, although cited in multiple chapters, had a reference in endnote with identical UUIDs in all instances.  Therefore, ``cito:isCitedBy <nca3>`` only appears once on this page.

However, there were a few instances of references repeated in multiple nca3 chapters which have multiple uuids, e.g.:
http://data.globalchange.gov/report/ceq-progrep-2010.thtml

This is because we were unable to catch 100% of the cases where a reference was cited by multiple chapters and consequently assign the same UUID to all instances of those references.  My point is that it's solely an endnote issue.

The point is that this results in identical triples.  For the second example provided above,
```
<http://data.globalchange.gov/report/ceq-progrep-2010>
   cito:isCitedBy <http://data.globalchange.gov/report/nca3>;
   biro:isReferencedBy <http://data.globalchange.gov/reference/1a73a6da-b3fb-4e34-aa3a-868579682b56>.

<http://data.globalchange.gov/report/ceq-progrep-2010>
   cito:isCitedBy <http://data.globalchange.gov/report/nca3>;
   biro:isReferencedBy <http://data.globalchange.gov/reference/37163c2c-5801-4702-9191-f32bf0f05b26>.
```

Is this a problem?  @zednis would it be easier to just locate an alternate term for biro:isReferencedBy and thus create something like the following (improper use of RDF)  pseudocode:
```
<report_URI> <CitedBy> <report> <inContextOf> <reference_UUID> .
```
where ``<inContextOf>`` would replace biro:isReferencedBy?

**Comment by justgo129** [comment]
Not showing over github, sending as e-mail.

**Comment by zednis** [comment]
@justgo129 I am not sure what you are suggesting with the pseudo RDF at the end.

I think I can address you question of whether identical triples are a problem.

The templates generating 'duplicate triples' is not a problem because an RDF graph is a set of triples.  Duplicate triples when loaded into a triplestore or in-memory RDF store are ignored and and no effect on the set.

The example you provided
```
<http://data.globalchange.gov/report/ceq-progrep-2010>
   cito:isCitedBy <http://data.globalchange.gov/report/nca3>;
   biro:isReferencedBy <http://data.globalchange.gov/reference/1a73a6da-b3fb-4e34-aa3a-868579682b56>.

<http://data.globalchange.gov/report/ceq-progrep-2010>
   cito:isCitedBy <http://data.globalchange.gov/report/nca3>;
   biro:isReferencedBy <http://data.globalchange.gov/reference/37163c2c-5801-4702-9191-f32bf0f05b26>.
```

is equivalent to 
```
<http://data.globalchange.gov/report/ceq-progrep-2010>
   cito:isCitedBy <http://data.globalchange.gov/report/nca3> ;
   biro:isReferencedBy <http://data.globalchange.gov/reference/1a73a6da-b3fb-4e34-aa3a-868579682b56> ;
   biro:isReferencedBy <http://data.globalchange.gov/reference/37163c2c-5801-4702-9191-f32bf0f05b26> .
```

**Comment by justgo129** [comment]
Great.  Question answered.
