### ISSUE TITLE
Allow multiple resources (e.g. datasets) to be associated with an activity

### ISSUE THREAD

**Issue by rewolfe** [USGCRP/gcis#176]
Allow multiple resources (e.g. datasets) to be associated with an activity.  Example: Activity for Figure 2.26 uses 4 different datasets.

**Comment by bduggan** [comment]
It is possible.

**Comment by bduggan** [comment]
To elaborate:
1. go to figure->edit->provenance
2. choose a relationship to a dataset (e.g. wasDerivedFrom), use autocomplete to find the activity.
3. click save
4. add a relationship to another dataset, use autocomplete to find the same activity
5. click save
6. done, this figure wasDerivedFrom two datasets

**Comment by rewolfe** [comment]
Thanks for explaining this. @saulenbach might also be interested.

**Comment by rewolfe** [comment]
I meant @aulenbac.
