### ISSUE TITLE
Annales_de_chimie

### ISSUE THREAD

**Issue by justgo129** [USGCRP/gcis#177]
Thread began at:
https://github.com/USGCRP/gcis/issues/147

I'm spinning off the subject of this particular journal into its own entry.

**Comment by rewolfe** [comment]
From Worldcat, it is pretty clear that this journal's ISSN is: 0365-1444

I updated the spreadsheet.  So, I am closing this issue.

**Comment by rewolfe** [comment]
I can't figure out how to close this issue.  Maybe it is a permission problem @bduggan?

**Comment by bduggan** [comment]
Please don't use the gcis github repo for data issues, maybe start another repo?  Issues here should only be related to the server software.

**Comment by bduggan** [comment]
On Tuesday, June 23, Robert Wolfe wrote: 
> I can't figure out how to close this issue.  Maybe it is a permission problem @bduggan?

Is it?  I think anyone can close an issue.
