### ISSUE TITLE
Journals

### ISSUE THREAD

**Issue by justgo129** [USGCRP/gcis#194]
Inspired by #191 , I am wondering whether we could relate  dbpedia:AcademicJournal
(http://dbpedia.org/page/Academic_journal) to gcis:Journal or rewrite the end of the code for journals to:

"a gcis:Journal, dbpedia:AcademicJournal."

Looking at dbpedia, I see many publication types which relate, at least at first glance, to those in gcis.

**Comment by bduggan** [comment]
Please just use the github gcis issues for well defined fixable server side issues.  This should be discussed on the mailing list or in the gcis-ontology repo.
