### ISSUE TITLE
Link journals with DBPedia

### ISSUE THREAD

**Issue by CurtTilmes** [USGCRP/gcis#211]
You've got journals such as:
    http://data.globalchange.gov/journal/science

some have wikipedia pages such as:
    https://en.wikipedia.org/wiki/Science_(journal)
and DBPedia pages:
    http://dbpedia.org/page/Science_(journal)

you could link to.

Where you have "bibo:issn", dbpedia has "dbo:issn" which appear to match..  A "sync" type script could look up matching ISSNs and establish the links automatically.

DBPedia also has "dbo:impactFactor" and "dbp:impact" from which you could determine Justin's "articles with a top journal ranking (e.g. Nature and Science) per an official citation metric of one's choice".

(Actually, it would be pretty cool and not too hard I think to dynamically pull in the JSON version of the DBPedia data from your HTML template on the client side and duplicate the wikipedia box of facts about the journal on your journal HTML page -- without sucking in all the data to your database.)

**Comment by bduggan** [comment]
This is an interesting idea, we should discuss it more (on the mailing list), it's a big architectural change and of course could be done not just with dbpedia but with any web service that supplies the right CORS headers and has either matching identifiers or lexicon entries.  I think we should figure out a way to do this in general, and also decide whether it belongs in the HTML produced by GCIS or something independent that uses the GCIS and other services as backends (or some combination of the two approaches?).  There's also the question of whether to use the REST API or the triple store (or at least the RDF representations), how to gracefully handle the case when other services are unavailable, etc I'm going to close this and markt it as an enhancement but we should re-open it if some of these details are worked out.
