### ISSUE TITLE
Link instruments with DBpedia

### ISSUE THREAD

**Issue by CurtTilmes** [USGCRP/gcis#213]
And, just for completeness, I'll note that
    http://data.globalchange.gov/instrument/moderate-resolution-imaging-spectroradiometer
could be linked to 
   http://dbpedia.org/page/Moderate-Resolution_Imaging_Spectroradiometer

Is there a good general way to automate such links?  Even just match the titles and offer a list of potential links to a curator?

**Comment by bduggan** [comment]
On Monday, August  3, Curt Tilmes wrote: 
> And, just for completeness, I'll note that
>     http://data.globalchange.gov/instrument/moderate-resolution-imaging-spectroradiometer
> could be linked to 
>    http://dbpedia.org/page/Moderate-Resolution_Imaging_Spectroradiometer
> 
> Is there a good general way to automate such links?  Even just match the titles and offer a list of potential links to a curator?

We've done this for some instruments, you can scan through the
dbpedia lexicon to see which ones:

    http://data.globalchange.gov/lexicon/dbpedia

Looks like we didn't get MODIS, good catch.  One of the hard parts is
that for many instruments, there is only a section of a wikipedia
page, but not a dedicated resource.

Brian

**Comment by bduggan** [comment]
I'm closing this issue since in general we do have a way to do this (and we'll add the missing link to MODIS).
