### ISSUE TITLE
Derreferencable URIs

### ISSUE THREAD

**Issue by CurtTilmes** [USGCRP/gcis#223]
From a comment on the METHOD paper review:

>Also, although the URIs are resolvable, they are not derreferenceable. For instance: curl -sH "Accept: text/turtle" -L http://data.globalchange.gov/report/nca3/chapter/our-changing-climate will return html. The same happens for the ontology; if I try to import it to Protege (http://data.globalchange.gov/gcis.owl), it will fail. These are small issues which difficult the reusability of the resources described in the paper.

GCIS seems to use "application/x-turtle" for the turtle type, but even when I try that with the Accept header, I still get text/html back:

    $ curl -svIH "Accept: application/x-turtle" http://data.globalchange.gov/report/nca3/chapter/our-changing-climate > /dev/null
    * About to connect() to data.globalchange.gov port 80 (#0)
    *   Trying 128.117.225.225...
    * connected
    * Connected to data.globalchange.gov (128.117.225.225) port 80 (#0)
    > HEAD /report/nca3/chapter/our-changing-climate HTTP/1.1
    > User-Agent: curl/7.24.0 (x86_64-apple-darwin12.0) libcurl/7.24.0 OpenSSL/0.9.8} zlib/1.2.5
    > Host: data.globalchange.gov
    > Accept: appication/x-turtle
    > 
    < HTTP/1.1 200 OK
    < Server: nginx/1.6.2
    < Date: Mon, 17 Aug 2015 18:39:53 GMT
    < Content-Type: text/html;charset=UTF-8
    < Content-Length: 13881
    < Connection: keep-alive
    < X-API-Version: 1.34
    < Access-Control-Allow-Origin: *
    < 
    * Connection #0 to host data.globalchange.gov left intact
    * Closing connection #0

**Comment by bduggan** [comment]
On Monday, August 17, Curt Tilmes wrote: 
>> For instance: curl -sH "Accept: text/turtle" -L
>> http://data.globalchange.gov/report/nca3/chapter/our-changing-climate
>> will return html.

We now support these accept headers for resources:

    application/x-turtle
    text/turtle
    application/n-triples
    text/n3
    text/rdf+n3
    application/ld+json
    application/rdf+xml
    application/rdf+json

>> The same happens for the ontology

We now support these accept headers for /gcis.owl:

    text/turtle
    application/x-turtle
    application/n-triples
    text/n3
    text/rdf+n3
    application/rdf+xml

>> ; if I try to import it to Protege (http://data.globalchange.gov/gcis.owl), it will
>> fail.

Hopefully one of the above is what Protégé wants.

Brian
