### ISSUE TITLE
API Reference links broken?

### ISSUE THREAD

**Issue by CurtTilmes** [USGCRP/gcis#227]
I'm using Chrome on a Mac.

I used to be able to go to the API Reference page http://data.globalchange.gov/api_reference and select the links on the "GET" methods and try out some of the items.  e.g. list reports with http://data.globalchange.gov/api_reference?try=list_report

Now it doesn't give me anything.

Not sure if it is related to the software or the instance.

I also tried Safari on Mac.

**Comment by bduggan** [comment]
Thanks.

In the meantime, a workaround is the swagger page:

    http://petstore.swagger.io/?url=http://data.globalchange.gov/api_reference.json

Click report + GET /report + "Try it out!"

Brian

**Comment by bduggan** [comment]
api_reference has been superceded by http://data.globalchange.gov/api
