### ISSUE TITLE
Enable Inferencing through RDFS in Virtuoso

### ISSUE THREAD

**Issue by zednis** [USGCRP/gcis#229]
I think we should start running inferencing so we can support queries that use super-classes and super-properties or type information that is inferred from property domain and range values.  Running inferencing will also put a spotlight on our class hierarchies and will potentially help expose class relationships that lead to confusion and should be re-evaluated (I consider this a good thing).

Right now I suggest we focus on RDFS inference.  We can evaluate different profiles of OWL2 inference later.

There are two different strategies we can use to implement RDFS reasoning
1) Configure Virtuoso to implement the RDFS reasoning [virtuoso documentation](http://docs.openlinksw.com/virtuoso/rdfsparqlrule.html)
2) Run the reasoning as part of our RDF load process, import the inferred triples into the triplestore - [Jena RIOT documentation](https://jena.apache.org/documentation/io/)

**Comment by zednis** [comment]
note -  I do not personally have experience with configuring virtuoso to do RDFS inferencing, but I suspect there are people in my lab who do.

**Comment by justgo129** [comment]
I agree with the idea of inferencing and will defer to @rewolfe @aulenbac and @bduggan about the technical components of virtuoso.

**Comment by bduggan** [comment]
I would also like to (or like someone to) evaluate blazegraph's capabilities
for this; we are undergoing various backend transitions, so now could be a
good time to change triple stores.

**Comment by zacharylandes** [comment]
Closing due to age and irrelavance
