### ISSUE TITLE
instance data for roles

### ISSUE THREAD

**Issue by zednis** [USGCRP/gcis#243]
References USGCRP/gcis-ontology/issues/128, USGCRP/gcis-ontology/issues/101, USGCRP/gcis-ontology/issues/102.

We have decided to store role types in the database instead of in the ontology.  As a result we will be removing the role instances from the ontology and building role instance RDF from the database using templates.

Role information should also be available via the RESTful API.  

http://data.globalchange.gov/role/{id}

Roles will be simple records composed of an identifier, label, and comment.

Role
- id TEXT
- label TEXT
- comment TEXT

**Comment by bduggan** [comment]
This is now supported in the database.  Note that the API is for role_type/{identifier}, rather than role, e.g. http://data.globalchange.gov/role_type/advisor
