### ISSUE TITLE
Enable redirects akin to Wikipedia / dbpedia "seeAlso"

### ISSUE THREAD

**Issue by justgo129** [USGCRP/gcis#291]
We'd like to utilize the dbpedia "seeAlso" field in GCIS.  For instance, a user searching for "U.C.L.A." and one searching for "UCLA" (or other values identical to those in the appropriate dbpedia:seeAlso field) should be both be directed to the GCIS page for the "University of California, Los Angeles."

**Comment by justgo129** [comment]
Assigned to @zednis and @rewolfe.  How would we implement this in the API?

**Comment by zednis** [comment]
I don't quite follow your example.  The example provided sounds like a standard search use case, what does that have to do with redirects?

Perhaps you can rephrase the request or provide a more in-depth example?

**Comment by justgo129** [comment]
Sure, this follow up on the use case we discussed earlier in which GCIS wishes to direct someone looking for information about "UCLA" to "University of California, Los Angeles," which is how we characterize UCLA in GCIS.

To make this happen, we earlier discussed using the rdfs:seeAlso and/or dbo:wikiPageRedirectsOf capabilities embedded within (dbpedia)[http://live.dbpedia.org/page/University_of_California,_Los_Angeles].  The question is how do we implement the capability in the interface?  How can we leverage the "... and ... redirects here" capabilities of wikipedia, see. e.g. the first line of (this page)[https://en.wikipedia.org/wiki/University_of_California,_Los_Angeles]?

**Comment by zednis** [comment]
> Sure, this follow up on the use case we discussed earlier in which GCIS wishes to direct someone looking for information about "UCLA" to "University of California, Los Angeles," which is how we characterize UCLA in GCIS.

To rephrase, The user does a search for "UCLA" ~somewhere~ in the interface and the search results contain a result that should link them to http://data.globalchange.gov/organization/university-california-los-angeles.

- where and how is the user executing the search?
- what do the results look like?

> To make this happen, we earlier discussed using the rdfs:seeAlso and/or dbo:wikiPageRedirectsOf capabilities embedded within dbpedia. The question is how do we implement the capability in the interface? How can we leverage the "... and ... redirects here" capabilities of wikipedia, see. e.g. the first line of this page?

I think it is premature to start suggesting technical changes until the use case is further developed.

**Comment by zednis** [comment]
PS - the search bar (center not top right) in https://data.globalchange.gov/organization seems broken.

**Comment by justgo129** [comment]
Sure.  Given my imminent departure from the GCIS team, I'm assigning @amruelama to develop this as she is the new data manager.  @zednis regarding the center searchbar, could you please provide an example of how it's now working?  It seems to be working fine here but I'm probably missing something.

**Comment by rewolfe** [comment]
- [ ] Add lexicons (and vocabularies) to search - short term
- [ ] Add automated federated searches using dbpedia
