### ISSUE TITLE
Create a "doi" field for books

### ISSUE THREAD

**Issue by justgo129** [USGCRP/gcis#293]
*Create a "DOI" (or “doi”)  field in the entries for books in GCIS.  The field can be populated by looking for the http://dx.doi.org/... string in the URL for some GCIS book entries.  This could probably be a quick coding task involving regular expressions.

**Comment by lomky** [comment]
@justgo129 do you have any examples of GCIS books that would benefit from this?

**Comment by justgo129** [comment]
yes, there are some URLs containing doi strings:

https://data.globalchange.gov/sparql?default-graph-uri=&query=select+distinct+*+FROM+%3Chttps%3A%2F%2Fdata.globalchange.gov%3E+where+%7B+%0D%0A++%3Fs+a+gcis%3ABook+.%0D%0A+++%3Fs+gcis%3AhasURL+%3Faurl%0D%0A+++filter+regex+%28%3Faurl%2C+%22%5Ehttp%3A%2F%2Fdx.doi.org%22%2C%22i%22%29%0D%0A%7D+&should-sponge=&format=text%2Fhtml&timeout=0&debug=on

Query results aren't aesthetically pleasing (e.g., I didn't use "str()", change the column names, etc) but the point's made.

**Comment by lomky** [comment]
Thank you @justgo129. Work will be done under #465.
