### ISSUE TITLE
Publication 'Publisher' as a related Contributor

### ISSUE THREAD

**Issue by justgo129** [USGCRP/gcis#294]
Migrate the values of the publication "publisher" field into that for the "publisher" as a "contributor" field for books (i.e., move value of "publisher" in "books" to that of "publisher" in "contributors").  Ignore where this has been done automatically.

Note: the subject of the level of granularity for publishers and the addressing of the various changes in the publisher market (e.g. Wiley or Elsevier has many divisions) is topic for discussion.

**Comment by rewolfe** [comment]
Example of the publisher linked through a relationship (the way we would like this to be): http://data.globalchange.gov/book/03826610-743d-4e51-a08e-8fe8d294fa83

**Comment by lomky** [comment]
So, instead of having the publisher in the column of the publication table, we want the publisher to exist as a contributor and relate it properly.

**Comment by lomky** [comment]
This is done! #548 #549 #553
