### ISSUE TITLE
Figure out the best way to handle middle names (internationalization)

### ISSUE THREAD

**Issue by justgo129** [USGCRP/gcis#298]
Permit middle names for authors to show up in the html, move middle initials from “first_Name” to “middle_Name” field, adjust Turtle templates accordingly.

**Comment by justgo129** [comment]
This would be best accomplished through a script.

**Comment by lomky** [comment]
This would be nice to have before the next assessment

**Comment by lomky** [comment]
Basic approach: create a script to handle this, with a way to flag entries for QA.

 - Where Middle is blank, no QA needed.
 - Where First and Middle are each one word, different than each other, very low priority QA.
 - Where the First Name had spaces already, high priority QA
 - Where the First Name seems to contain the middle, high priority QA
 - Where the First Name has a capital initial, high priority QA.

We can run the script on Stage and have it output the identifiers of the people who need QA, run the QA and correct any errors and then do a content push.

This involves an API deprecation of the middle name field.

**Comment by lomky** [comment]
Actually, we only have 50 people with middle names, so this might not be worth doing via script. 

SQL query to find the 50: `select id, first_name, middle_name, last_name from person where middle_name IS NOT null;`

**Comment by rewolfe** [comment]
Be careful because some reports (NCA, CCHHA) rely on the middle name being part (or not part) of the displayed name.  This is a "hidden" feature.  If the middle initial is part of the first name, it is displayed, otherwise not.

**Comment by amruelama** [comment]
As there are only 51 names with middle names, I am going to move those initials to the first names so as to be consistent with other names. We can move these initials (second part of the first name) to middle name field any time we wish. 

Hence middle name field will be NULL for all the 10K+ authors.

**Comment by amruelama** [comment]
This is done on stage. We can further discuss about naming convention in #503
