### ISSUE TITLE
Extend autocomplete

### ISSUE THREAD

**Issue by justgo129** [USGCRP/gcis#299]
Within dev and stage, extend autocomplete to encompass more components of the organization name.  Alternatively stated, only a smaller portion of an org with a really long name would show up in autocomplete, as the rest is stored as ...  Therefore, someone entering the really long name into GCIS would need to shorten it for the autocomplete to locate the existing org.  This should change.

**Comment by lomky** [comment]
@justgo129 Can you write or point out a couple examples?

**Comment by justgo129** [comment]
Sure.  On stage, try entering the following organization in the "organization" box under the "contributors" tab:

national environmental satellite data

The following should come up in the autocomplete:
[organization] {national-oceanic-atmospheric-administration-national-environmental-satellite-data-information-service} National Oceanic and Atmospheric Administration National Environmental Satell...

Should come up, but notice that everything after "satellite" in the title isn't read.  Presumably this is due to the length of the org name.

**Comment by amruelama** [comment]
Redundant to #542
