### ISSUE TITLE
Display contributors from parent and children organizations on the same screen

### ISSUE THREAD

**Issue by justgo129** [USGCRP/gcis#301]
Display contributors from parent and children organizations on the same screen.

E.g. the contributors from the US Environmental Protection Agency Office of Air and Radiation should show up on the page listing all contributors with affiliation "US Environmental Protection Agency."

**Comment by lomky** [comment]
@justgo129 could you link which screen you are talking about here?

**Comment by justgo129** [comment]
Sure, an example is here:
https://data.globalchange.gov/organization/us-environmental-protection-agency

If it helps, think "screen"="page".
