### ISSUE TITLE
Disambiguating authors when ORCiDs Not Available

### ISSUE THREAD

**Issue by justgo129** [USGCRP/gcis#302]
Permit a form of contributor disambiguation other than through ORCiDs.  We have a handful of examples in GCIS where individuals without ORCiDs share the same name.

**Comment by justgo129** [comment]
Here's an example of someone writing under two last names, although she has an ORCiD:
[](https://data-stage.globalchange.gov/person/6639url)
It would be great if we could indicate the multiple last names as well and not just rely on the ORCiD.

**Comment by lomky** [comment]
Currently, this is solved via the hidden middle name field. A final fix will have to wait on a new API version. Lowering priority.
