### ISSUE TITLE
Add field for “report series” to facilitate querying

### ISSUE THREAD

**Issue by justgo129** [USGCRP/gcis#305]
Add field for “report series” (e.g. IPCC AR6 volumes) to facilitate querying.
e.g.: the series "IPCC AR5," "IPCC AR6."  Right now this relation can only be identified through a regular expression search on their respective titles, not through a formal relationship in the database.

Adjust turtle templates appropriately to accommodate this addition.

**Comment by justgo129** [comment]
To clarify: for a report e.g. IPCC AR5 WG1, it would be nice to have a field called "report_series" in which we'd enter something akin to "Intergovernmental Panel on Climate Change 5th Assessment Report."

**Comment by lomky** [comment]
May relate to #434

**Comment by zacharylandes** [comment]
Closing due to age and irrelavance
