### ISSUE TITLE
Enhances to searchability

### ISSUE THREAD

**Issue by justgo129** [USGCRP/gcis#307]
Enhances to searchability: increased string distance, searchability by resource type, allowing of quotation marks

**Comment by rewolfe** [comment]
Searchability by resource type already exists.

**Comment by justgo129** [comment]
Increased string distance would be helpful for the search capabilities in stage and dev.

**Comment by lomky** [comment]
closing as redundant to #299 (enable these things in autocomplete will also create this functionality)
