### ISSUE TITLE
Org types and nature of org-org relationships

### ISSUE THREAD

**Issue by justgo129** [USGCRP/gcis#309]
This issue can fall into multiple categories and relate to many other issues, such as https://github.com/USGCRP/gcis/issues/229:
- [x] Update turtle templates to make the rdf representation (subject and predicate) for organization relationship type contingent on the nature of the relationship;
  Example: if org A is a department of org B, and org C is an affiliate of org D, relate through “org:unitOf” and “gcis:affiliateOf,” respectively within the turtle.
- [ ] allow searchability to be independent of relationship type.  
  Example: If someone wants to identify all the organizations related to a given organization without knowing the nature of the relationship or without knowing the semantically defined representation thereof, how would one code and implement?  This is an outgrowth of the Justin-Rama use case.

**Comment by rewolfe** [comment]
This may be related to #229.
