### ISSUE TITLE
Harmonize Organization Identifiers and Titles

### ISSUE THREAD

**Issue by justgo129** [USGCRP/gcis#310]
Harmonize organization identifiers and titles, e.g. look at the inconsistent org names and identifiers for those listed at:
    http://data.globalchange.gov/organization/us-department-agriculture
              http://data.globalchange.gov/organization/us-environmental-protection-agency
Also, we aren’t consistent about identifier or organization Titles for departments of University Medical Schools.  Sometimes, we provide “University School of Medicine Department of” and sometimes “University School of Medicine.”  This should be fixed.

**Comment by amruelama** [comment]
@justgo129 We have 373 organizations' names separated by commas (between affiliations and types). Do we have to consider eliminating the commas for consistency?

Example 1 - [University of California, Berkeley School of Public Health](http://data.globalchange.gov/organization/university-california-berkeley-school-public-health)

Example 2 - [University of Liverpool Division of Public Health](University of Liverpool Division of Public Health)

**Comment by justgo129** [comment]
I wouldn't.  The official name of UC Berkeley is:
University of California, Berkeley

Some university titles have "at" or other propositions, e.g.:
"The University of North Carolina at Chapel Hill."

As such we actually are being consistent:
official_Name_official dept/division title

**Comment by rewolfe** [comment]
Add best practices to the Wiki under conventions.
