### ISSUE TITLE
Update Organization metadata with new relationship type 

### ISSUE THREAD

**Issue by justgo129** [USGCRP/gcis#312]
Now that we have added the relationships of “center_of” and “unit_of,” use SPARQL queries to go back through and update relationship types for university centers which predated the entry of these new relationships in GCIS.

**Comment by justgo129** [comment]
Given the #361, selection of org type now has semantic/RDF implications.  I'm therefore somewhat elevating the priority on this issue.

**Comment by amruelama** [comment]
Could you give examples for 'center of' and 'unit of'? @justgo129

**Comment by rewolfe** [comment]
Also, we need definitions for these relationships.

**Comment by lomky** [comment]
The basic definitions are:

Center of - An organization within a college 

Unit of - For example, a National Park Service Unit

**Comment by amruelama** [comment]
Working on cleaning up organization types - #606
