### ISSUE TITLE
Adjust identifier scheme for articles without dois and PubMed Ids to ensure consistency

### ISSUE THREAD

**Issue by justgo129** [USGCRP/gcis#314]
Adjust identifier scheme for articles without dois and PubMed Ids to ensure consistency

**Comment by lomky** [comment]
@justgo129 adjust them to what?

**Comment by lomky** [comment]
Discussion with @justgo129 

Journal of Soil and Water Conservation, for example, didn't backfill their articles with DOIs. The decision may be to just allow articles with neither PubMed nor DOI to just have a GCIS identifier.

[Example articles](https://data.globalchange.gov/article?page=168)

Worth doing a QA pas to fill in any that Do have PubMed or DOI, and then work with @amruelama to decide the convention moving forward for those lacking either ID.

**Comment by lomky** [comment]
Corollary: May be worth running a QA on the articles of various identifiers.
