### ISSUE TITLE
Health Assessment Changes

### ISSUE THREAD

**Issue by rewolfe** [USGCRP/gcis#317]
Changes in the user interface to support the Climate Change and Human Health Assessment
1. Allow multiple, ordered featured reports.
2. Allow formatting tags (bold, html links, etc.) in captions and findings.
3. Always identify report when stating chapter numbers, figure numbers, etc.
4. Always display table when specifying cited by.

**Comment by rewolfe** [comment]
Plus, 
5. Add health-related Sparql query.
6. Add JPL folks to about page.

**Comment by rewolfe** [comment]
1 - done (hard coded); 2 - done; 5 - done; 6 - done;
3 and 4 still open

**Comment by lomky** [comment]
- [x] Allow multiple, ordered featured reports.
    - [ ] Less hard-coded
 - [x]  Allow formatting tags (bold, html links, etc.) in captions and findings.
 - [ ]  Always identify report when stating chapter numbers, figure numbers, etc.
 - [ ]  Always display table when specifying cited by.
 - [x]  Add health-related Sparql query.
 - [x]  Add JPL folks to about page.

**Comment by lomky** [comment]
Made the Featured Reports more extensible.

@rewolfe can you give some examples of where you meant the report should be shown for number 3?

**Comment by rewolfe** [comment]
Example of a report that is cited by many resources and it is difficult to know which report the figures/chapters/findings are associated with: 
    https://data.globalchange.gov/report/nca3

The "cited by" could be done as a table (if there is more than one entry).  The columns would be "reference" (biblio id), "publication" (report gcid), "item" (e.g. figure 10).

Also, the "is cited by" section also could be done as a similar table (including the biblio id).

Example of a reference where the findings and chapters are not report specific
    https://data.globalchange.gov/reference/61fd6e32-63d0-4f5a-bbbb-f68262376a37

Different issue: Citations of chapters are not mentioned:
    https://data.globalchange.gov/report/nca3/chapter/human-health

**Comment by lomky** [comment]
@rewolfe thanks!
