### ISSUE TITLE
Bug fix for book identifiers

### ISSUE THREAD

**Issue by justgo129** [USGCRP/gcis#324]
Fix bug which doesn’t permit one to delete the identifier for a book.  Rationale: all books have identifiers which are UUIDs, and are created by leaving the “identifier” field blank.  However, one wishing to delete an existing identifier generates an error message.

**Comment by lomky** [comment]
@justgo129 Books do not have a UUID out in the wild? Do you mean their ISBN? That field exists. We need to have an identifier for the book, even if it is only internal to GCIS.

**Comment by justgo129** [comment]
Yep, the decision to use UUIDs for books was a conscious one made by the group a few years ago; I don't recall why.  ISBNs aren't necessarily the best given ISBN-10s, ISBN-13s, and the variation by edition, etc.

**Comment by lomky** [comment]
@justgo129 Are you talking about the UUID we are creating for the books as the "identifier"?

**Comment by justgo129** [comment]
@lomky, yes

**Comment by lomky** [comment]
I think the answer here would be to ask GCID to [generate a UUID](https://data.globalchange.gov/uuid) for you rather than leaving it blank.

Since this is such a rare occurrence, I think that plus the #465 will take care of this problem.
