### ISSUE TITLE
References on chapters page - invalid link

### ISSUE THREAD

**Issue by justgo129** [USGCRP/gcis#325]
Fix bug which precludes references on GCIS page for chapters from showing up when clicking on the respective icon next to the chapter, e.g. when clicking on the "206" for the chapter "4: Impacts of Extreme Events."

**Comment by lomky** [comment]
Reference links:

 On [this page](https://data.globalchange.gov/report/usgcrp-climate-human-health-assessment-2016/chapter?thumbs=0) if you click the 206 you get a [404](https://data.globalchange.gov/report/usgcrp-climate-human-health-assessment-2016/list_chapter_references)

**Comment by lomky** [comment]
We fixed a similar problem with report list pages in #429 so this problem is likely in the chapter-specific handling for listing.
