### ISSUE TITLE
MMWR

### ISSUE THREAD

**Issue by justgo129** [USGCRP/gcis#326]
Look at the various instances of “Morbidity and Mortality Weekly Report” (MMWR) journals and relate to each other if possible, correct citations if needed.  If unsure about contributors, check the MMWR webpage for guidance.

**Comment by amruelama** [comment]
Added '[Centers for Disease Control and Prevention](https://data.globalchange.gov/organization/centers-disease-control-and-prevention)' as publisher for the journals listed [here](https://data.globalchange.gov/search?q=morbidity-mortality&type=journal&format=detailed).
