### ISSUE TITLE
Identifier scheme for non-US organizations

### ISSUE THREAD

**Issue by justgo129** [USGCRP/gcis#328]
We aren’t consistent about using non-English titles and identifiers for non-US orgs.  While we mostly use English equivalents, we sometimes use the non-English which is probably the preferred way.  e.g.:
    http://data.globalchange.gov/organization/universitat-bern
    http://data.globalchange.gov/organization/university-bern-institute-plant-sciences
    http://data.globalchange.gov/organization/universitat-bern-geographischen-institut
    http://data.globalchange.gov/organization/universitat-bern-astronomical-institute

```
http://data.globalchange.gov/organization/planbureau-voor-de-leefomgeving
http://data.globalchange.gov/organization/netherlands-agency-aerospace-programmes
http://data.globalchange.gov/organization/netherlands-space-office
```

Among others, such as the PIK in Germany.

Please adapt a strategy for attacking these and fix them.

**Comment by amruelama** [comment]
As @justgo129 mentioned, adding 'Aliases' field would be a good solution to this issue. Copying @lomky

**Comment by lomky** [comment]
@amruelama and I discussed, we see three parts to this:

 1. Establish the convention going forward
    1. This is done, we will use the Organization Country version as the ID base
 1. Implement a way to store the English version of the organization (Tech Task)
    1. Including the semantic representation?
 1. Fix existing non-US orgs with US-names to have their native name. (Content Task)
    1. This must also maintain the existing GCID path (automatic?)

**Comment by amruelama** [comment]
Thanks @lomky 
List of Non-U.S. Organizations and International Organizations (Country = Blank) is in the [Content Tracker](https://docs.google.com/spreadsheets/d/1tr68prMQSffCy4HjIg-szmpyNw0J1YtzJf3CSfDbdZg/edit#gid=346506704) for reference.
