### ISSUE TITLE
Webpages or Datasets?

### ISSUE THREAD

**Issue by justgo129** [USGCRP/gcis#329]
Many websites can actually be better described as datasets, e.g.:
    http://data.globalchange.gov/webpage/6cfff73e-1b3f-401d-a7ab-d0d8fd5a0ebc
    http://data.globalchange.gov/webpage/climate-at-a-glance-time-series-of-contiguous-us-average-temperature-1901-2000
and others.

Develop some criteria for differentiation, track down various websites which may be better suited as datasets, compare with GCIS datasets to see if meets those criteria, and if so, change accordingly.

**Comment by amruelama** [comment]
83 of them are not webpages but datasets (82) and findings (1) (Use filter Status = 'Yes' and 'Finding') under '[Webpages QA](https://docs.google.com/spreadsheets/d/1tr68prMQSffCy4HjIg-szmpyNw0J1YtzJf3CSfDbdZg/edit#gid=1699357652)' sheet. We should convert these into datasets and finding.

**Comment by amruelama** [comment]
Broken URLs are updated now
