### ISSUE TITLE
Add "province" or related term as an org type in the GCIS db

### ISSUE THREAD

**Issue by justgo129** [USGCRP/gcis#333]
For organization type, GCIS has, among others:
- city
- county
- municipal
- state
- territory
- Federal
- national (for non-US central government entities)

We have many instances of state/territory-level organizations in Australia, and examples of province-level organizations in Canada.  Therefore,
(1) adjust or add org types in the db
(2) apply to such organizations

**Comment by lomky** [comment]
#468 is going over the organization types as a whole and will make the judgement call on this.
