### ISSUE TITLE
Adjust identifier scheme for NCA3 and/or Health Assessment for consistency

### ISSUE THREAD

**Issue by justgo129** [USGCRP/gcis#334]
Also relates to #212, #314, and especially #311.  Regardless, we use a very short identifier without an org affiliation for the NCA3 (and NCA2 and related documents, and nca1) but a longer one which includes "USGCRP" for the health assessment.  If this is deemed an issue, please determine a course of action and adjust identifiers accordingly.  First though, @bakamine could you please check to ensure that a change in identifier in any one of these reports would not cause issues for collaborators outside the NCO? 

Also copying @amruelama

**Comment by lomky** [comment]
Worth considering as a convention going forward, but changing our major report identifiers would be very bad.
