### ISSUE TITLE
Incorporate Google Analytics logging into API service

### ISSUE THREAD

**Issue by justgo129** [USGCRP/gcis#336]
Incorporate Google Analytics logging into API service. Possibly  https://developers.google.com/analytics/devguides/collection/protocol/v1/

**Comment by lomky** [comment]
@justgo129 what does this do for us?

**Comment by justgo129** [comment]
It would allow us to be informed of API browsing habits, favored links, etc.  We talked about it at some point way back but haven't discussed it much since.

**Comment by rewolfe** [comment]
This may already be in Google Analytics although it isn't clear how to
extract and summarize the information.

On Wed, Jul 6, 2016 at 12:48 PM, justgo129 <notifications@github.com> wrote:

> It would allow us to be informed of API browsing habits, favored links,
> etc. We talked about it at some point way back but haven't discussed it
> much since.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/USGCRP/gcis/issues/336#issuecomment-230833766>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AHR7GYgc3qi4rKyUxaX5_H-1vw8KE_O7ks5qS9xPgaJpZM4INHuD>
> .
>



-- 
Robert Wolfe, NASA GSFC @ USGCRP, o: 202-419-3470, m: 301-257-6966

**Comment by bakamine** [comment]
Google Analytics currently only tracks HTML content. This is to facilitate tracking for JSON, etc.

**Comment by lomky** [comment]
Throwing things here for later:
https://www.quora.com/What-are-some-good-ways-to-track-API-usage
http://stackoverflow.com/questions/8464863/is-there-a-google-analytics-like-solution-to-track-rest-calls-to-a-web-service

**Comment by lomky** [comment]
More thoughts for later:

 - API Access Keys - Self managed or through [Amazon AWS](https://aws.amazon.com/api-gateway/)
