### ISSUE TITLE
Enhancing our use of the "USGS" lexicon

### ISSUE THREAD

**Issue by justgo129** [USGCRP/gcis#337]
Merging fields from USGS publications metadata (series + number) for purposes of USGS lexicon
See http://data.globalchange.gov/lexicon/usgs and note that we need info from both the "series" and "number" values found in the publications' respective xmls.

**Comment by justgo129** [comment]
Correction on the Url for the lexicon:
(http://data.globalchange.gov/lexicon/usgs_publications)[url]
Sample xml from which to extract the "series" and "number" values provided in the overview:
[http://pubs.er.usgs.gov/service/search/xml/advance?report_number=2012-1025](url)

**Comment by lomky** [comment]
@justgo129 would this be correct?

Today:

```
00-179     /report/usgs-openfilereport-00-179
2009-1291  /report/usgs-openfilereport-2009-1291
2009-3098  /report/usgs-factsheet-2009-3098
```

Desired State:

```
openfilereport-00-179     /report/usgs-openfilereport-00-179
openfilereport-2009-1291  /report/usgs-openfilereport-2009-1291
factsheet-2009-3098       /report/usgs-factsheet-2009-3098
```

**Comment by rewolfe** [comment]
@justgo129 - What is the purpose of this lexicon?

On Thu, Jun 23, 2016 at 9:31 AM, Kathryn Tipton <notifications@github.com>
wrote:

> @justgo129 <https://github.com/justgo129> would this be correct?
>
> Today:
>
> 00-179     /report/usgs-openfilereport-00-179
> 2009-1291  /report/usgs-openfilereport-2009-1291
> 2009-3098  /report/usgs-factsheet-2009-3098
>
> Desired State:
>
> openfilereport-00-179     /report/usgs-openfilereport-00-179
> openfilereport-2009-1291  /report/usgs-openfilereport-2009-1291
> factsheet-2009-3098       /report/usgs-factsheet-2009-3098
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/USGCRP/gcis/issues/337#issuecomment-228050478>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AHR7GU4NGkqq3wIGgorEuf5fj6EOU4DEks5qOorHgaJpZM4INH70>
> .
>



-- 
Robert Wolfe, NASA GSFC @ USGCRP, o: 202-419-3470, m: 301-257-6966

**Comment by justgo129** [comment]
@lomky - you're correct.
@rewolfe - no clue, I just noticed the lexicon when browsing.  @BNewman2104 do you know?

**Comment by rewolfe** [comment]
@justgo129 and @lomky - Unless there is a strong argument against, I
recommend that we remove this lexicon.  It would be good for Amrutha to
take a look at all of the lexicons to see if there other ones for which
there is not a strong argument for keeping.  Aka. unless a lexicon is
really useful we should remove it.

On Thu, Jun 23, 2016 at 9:53 AM, justgo129 <notifications@github.com> wrote:

> @lomky <https://github.com/lomky> - you're correct.
> @rewolfe <https://github.com/rewolfe> - no clue, I just noticed the
> lexicon when browsing. @BNewman2104 <https://github.com/BNewman2104> do
> you know?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/USGCRP/gcis/issues/337#issuecomment-228056939>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AHR7GeW_gA05jpakV1laxiTXK5XpyYOVks5qOo_QgaJpZM4INH70>
> .
>



-- 
Robert Wolfe, NASA GSFC @ USGCRP, o: 202-419-3470, m: 301-257-6966

**Comment by lomky** [comment]
@rewolfe & @amruelama I admit I do not quite understand where the lexicons fit into the larger gcis data scheme. I would appreciate any diagrams / explanations / linked to the wiki that would clarify.
