### ISSUE TITLE
Further fostering of data.gov assets

### ISSUE THREAD

**Issue by justgo129** [USGCRP/gcis#338]
Further fostering of data.gov assets

**Comment by justgo129** [comment]
@amruelama  @lomky  I'd check with @rewolfe to see what's already been done.

**Comment by rewolfe** [comment]
@justgo129 - please provide more details.

**Comment by justgo129** [comment]
Alternatively stated, continue importing data.gov material into GCIS.

**Comment by bakamine** [comment]
This can be a thing that's worked in the long term, but we'll need to think about priorities. Obviously, everything in the CDI comes first. After that, which topics make sense? Ocean, ecosystems, energy, agriculture?

**Comment by lomky** [comment]
@bakamine I imagine this particular task becomes an epic covering multiple smaller tasks of various priorities from high (CDI data) to medium & low (other topics)

**Comment by lomky** [comment]
I think the CDI part is underway in task #374 @rewolfe is that correct?

**Comment by rewolfe** [comment]
@lomky - Correct.

On Thu, Jul 14, 2016 at 10:21 AM, Kathryn Tipton <notifications@github.com>
wrote:

> I think the CDI part is underway in task #374
> <https://github.com/USGCRP/gcis/issues/374> @rewolfe
> <https://github.com/rewolfe> is that correct?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/USGCRP/gcis/issues/338#issuecomment-232679792>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AHR7GZrINp-P3RDX8J2fYMJEXSPHPy3vks5qVkXwgaJpZM4INH_Y>
> .
>



-- 
Robert Wolfe, NASA GSFC @ USGCRP, o: 202-419-3470, m: 301-257-6966

**Comment by amruelama** [comment]
@rewolfe is currently working on adding 500+ datasets on data-review

**Comment by amruelama** [comment]
CDI datasets have been added. To add more data.gov datasets please refer @rewolfe's scripts [here](https://github.com/USGCRP/gcis-scripts/tree/master/datagov).
