### ISSUE TITLE
PDF Thumbnails Generating as White or Incomplete

### ISSUE THREAD

**Issue by justgo129** [USGCRP/gcis#340]
Figure out why, and address if possible, why various report thumbnails show up as grey of as half-empty within GCIS.

See e.g. 
    https://data.globalchange.gov/report/who-vulnerability-assessment-2013
    https://data.globalchange.gov/report/ers-economicresreport-136

**Comment by amruelama** [comment]
An example of blank or white thumbnail - https://data.globalchange.gov/report/usgcrp-ocpfy2009

**Comment by amruelama** [comment]
@justgo129 - [This](https://data.globalchange.gov/report/ers-economicresreport-136) report's thumbnail is grey because the file doesn't exist anymore in the source webpage.

**Comment by rewolfe** [comment]
I think Justin answered this question - closed again.

**Comment by lomky** [comment]
Expected normal thumbnails:
 
 - Full color exact cover page
   - Normal, PDF exists for download
 - Greyscale exact cover page
   - Normal, PDF no longer exists for download
 - Fully grey thumbnail
   - Normal, PDF does not exist for download & did not at tiem of thumbnail creation.

Abnormal:

 - Full color or greyscale incomplete cover page
   - error in thumbnail generation
 - Fully white
  - error in thumbnail generation
