### ISSUE TITLE
Locate document and fix URL

### ISSUE THREAD

**Issue by justgo129** [USGCRP/gcis#342]
We don't have a URL for MATCH, see:
http://data.globalchange.gov/webpage/ff774480-fd44-4f30-baee-e741c3903661.

(1) Let's check with Mark to see if he can confirm that ocp 2014 is indeed referring to MATCH, and if not, find the website to which it is referring.
(2) Adjust this entry accordingly.

**Comment by amruelama** [comment]
The webpage for MATCH with URL is already available [here](http://data.globalchange.gov/webpage/9fc83809-8c01-4c29-bed0-ce9178c1fc7d) @justgo129

**Comment by justgo129** [comment]
Hmm so we might wish to merge these two GCIS entries, provided they are both meant to refer to the same URL.

**Comment by amruelama** [comment]
I may have to delete the duplicate and relate the webpage again instead of 'merging' since as for now, merging is restricted only to 'person'

**Comment by justgo129** [comment]
That works, and just reassociate the pubs citing/cited by for one of the two versions with that which isn't going to be deleted.

**Comment by amruelama** [comment]
Perfect! I've made these changes on [stage](http://data-stage.globalchange.gov/report/usgcrp-ocpfy2014).

**Comment by justgo129** [comment]
@amruelama, while we're on the subject, do we have a globalchange.gov URL for the document to which you just linked?  Right now, we link outside USGCRP for it.

**Comment by amruelama** [comment]
Here are the links 
Report - [http://data.globalchange.gov/report/usgcrp-ocpfy2014](http://data.globalchange.gov/report/usgcrp-ocpfy2014 )
Webpage - [http://data.globalchange.gov/webpage/9fc83809-8c01-4c29-bed0-ce9178c1fc7d](http://data.globalchange.gov/webpage/9fc83809-8c01-4c29-bed0-ce9178c1fc7d)

**Comment by justgo129** [comment]
The "URL" field in data.gc?

On Tue, Jun 7, 2016 at 1:54 PM, Amrutha Elamparuthy <
notifications@github.com> wrote:

> Here are the links
> Report - http://data.globalchange.gov/report/usgcrp-ocpfy2014
> Webpage -
> http://data.globalchange.gov/webpage/9fc83809-8c01-4c29-bed0-ce9178c1fc7d
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/USGCRP/gcis/issues/342#issuecomment-224361311>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AHSmYVUyCIROqvvGSIf6p3RZBQj3JMM5ks5qJbBsgaJpZM4INIrh>
> .
>



-- 
________________________________
Justin Goldstein, Ph.D.
Advance Science Coordinator
US Global Change Research Program
National Coordination Office
Contractor

1800 G Street NW, Suite 9100 (*Note New Address)*
Washington, D.C. 20006, U.S.A.
phone: (202) 419-3496
e-mail: jgoldstein AT usgcrp Dot gov

http://www.globalchange.gov

**Comment by amruelama** [comment]
Here is the data.globalchange URL for the linked document - [https://downloads.globalchange.gov/ocp/ocp2014/our-changing-planet-FY14-final-high-res.pdf](https://downloads.globalchange.gov/ocp/ocp2014/our-changing-planet-FY14-final-high-res.pdf)
