### ISSUE TITLE
New pub button for dataset provenance

### ISSUE THREAD

**Issue by justgo129** [USGCRP/gcis#344]
Within stage, under "dataset" -> "provenance," create a a new "new" button and juxtapose it with "other publication," similar to that set up for the "'activity" field in the same form.

**Comment by lomky** [comment]
@justgo129 do you have a solution to this for the time being, or is the lack of this button blocking a task?

**Comment by justgo129** [comment]
@lomky no solution at present.  The rationale for this issue is simply a matter of convenience.

**Comment by rewolfe** [comment]
Workaround is to create the new publication first and then just link it to
the dataset here.

On Wed, Jul 6, 2016 at 12:46 PM, justgo129 <notifications@github.com> wrote:

> @lomky <https://github.com/lomky> no solution at present. The rationale
> for this issue is simply a matter of convenience.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/USGCRP/gcis/issues/344#issuecomment-230833270>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AHR7GcyHI0sniSwU2NiUEKRXdgjXpCOYks5qS9vkgaJpZM4IQGSD>
> .
>



-- 
Robert Wolfe, NASA GSFC @ USGCRP, o: 202-419-3470, m: 301-257-6966
