### ISSUE TITLE
Simple HTML Formatting  of Extended Text Fields, e.g. Description

### ISSUE THREAD

**Issue by justgo129** [USGCRP/gcis#346]
Add formatting and other html formatting capabilities to the "notes" field under "activities."

**Comment by amruelama** [comment]
I think adding HTML formatting will also solve issue #354  or adding two URLs in same field

**Comment by lomky** [comment]
@justgo129 or @rewolfe what is the use care for this? HTML formatting might be nice on our HTML display, but having it embedded will only cause trouble for all of our other formats (yaml, turtle, json). I also can't see why we would want a URL in the description that shouldn't be stored somewhere else as a distinct entry.
