### ISSUE TITLE
org:linkedTo

### ISSUE THREAD

**Issue by justgo129** [USGCRP/gcis#351]
I've been attempting to modify [this ](https://github.com/justgo129/gcis/blob/master/lib/Tuba/files/templates/organization/object.ttl.tut)code in order to print something akin to

 "if something is a department of, division of, or branch of something else, 
    print: org:unitOf <item>
  elseif
    print: org:linkedTo <item>"

I've developed some code which I've been been subsequently testing.  However, I keep receiving error messages on line 23, indicating a syntax error at "department_of".  Line 23 initially contained an "if" statement of a "for" loop but perl only permits barewords in "for" loops. Removing the second nested "$map = " on that line doesn't change the nature of the error.

Note that Line 23 contains
 ($map = 
 in-lieu of 
(my $map = 

due to $map being defined outside of the nested loop on line 17.

Could you tell me what is wrong with my syntax?

NB:Clearly the "else" on line 25 no longer makes sense in a for loop, but that's for another topic.

**Comment by lomky** [comment]
@justgo129 which branch contains the code you are referencing?

**Comment by justgo129** [comment]
@lomky, good call:
The code to update is on my branch: [https://github.com/justgo129/gcis/blob/master/lib/Tuba/files/templates/organization/object.ttl.tut](url)

The code with the updates:
[https://gist.github.com/justgo129/1ccc8bdaca125ee252a7e4a55d6812ca](url)

**Comment by lomky** [comment]
@justgo129 are you trying to confirm if the map pulled from maps is either a division_of or department_of? If so, you will need to do an `if ( map.foo eq 'department_of' || map.foo eq 'division_of' ) rather than a for looping structure. 

My first impression is you need to:
 - evaluate where the $map object is storing the 'division_of' or 'department_of' information
 - assuming that is a string, you want to use the `eq` comparison operation, not `=`, which is assignment (numeric comparison is `==`)
 - in the if statement, use an `||` or to catch either option

**Comment by justgo129** [comment]
Indeed, but I'm not sure where $map is storing 'division_of' or 'department_of'

**Comment by lomky** [comment]
while debugging things, you can call the dumper function on it and output that to your terminal or a log. That will give you the internal structure.

simple example to dump the object to standard out:
`print dumper $map`

Alternately, you can examine the code where your object is defined: `lib/Tuba/Organization.pm`. At a quick skim, code around line 90 would lead me to believe you want `organization_relationship`

**Comment by justgo129** [comment]
Good call, but do I need to uncall the "use strict;" namespace?

    Bareword "division_of" not allowed while "strict subs" in use at template organization/object.ttl.tut line 23. 
    Bareword "department_of" not allowed while "strict subs" in use at template organization/object.ttl.tut line 23. 
    18: % if ($first) { 
    19: % $first = 0; 
    20: ## This organization is related to one or more others as follows: 
    21: % }  
    22: <<%= current_resource %>> 
    23: % if ((my $organization_relationship eq division_of) || (my $organization_relationship eq department_of)) {
    24: org:unitOf <<%= uri($map->other_organization) %>>; 
    25: % } else { 
    26: org:linkedTo <<%= uri($map->other_organization) %>>; 
     27: % }

**Comment by justgo129** [comment]
Never mind, I left off the quotation marks around division_of, etc.  It works now.  Thanks, @lomky!  I need to stop forgetting that = ne eq in perl.

**Comment by justgo129** [comment]
Resolved in #362.  Therefore closed #351.
