### ISSUE TITLE
Add 'College of' for university orgs

### ISSUE THREAD

**Issue by BNewman2104** [USGCRP/gcis#353]
To better link departments to universities, the addition of  'College of' for universities would help capture college-level relations for our organizations.

**Comment by justgo129** [comment]
This is a very intriguing idea.  Could you provide an example?  Right now, we use "division of" and "department of" to relate departments, schools, colleges within schools, and universities. Sometimes schools are related to universities directly, and sometimes schools reside within colleges which make up a university.  We also relate universities to their university systems (e.g. UT-Austin to the University of Texas System) through "branch of."

I'm afraid this may get a little too complicated; perhaps we should narrow down the list of existing choices from "department of," "division of," "branch of" to one "division of?"  That's what we are trying to accomplish semantically in https://github.com/USGCRP/gcis/issues/351.

**Comment by BNewman2104** [comment]
For now, I have been using  "division of" to represent colleges within a university, i.e., "The Pennsylvania State University College of Earth and Mineral Sciences" is within "The Pennsylvania State University" and has departments such as:  "The Pennsylvania State University Department of Geography", "The Pennsylvania State University Earth and Environmental Systems Institute" etc...

While I do not feel this update would be critical, I believe this would help with the current ambiguity of university systems, but I am welcome to hear your thoughts.

**Comment by justgo129** [comment]
and I've been using "branch of" to relate universities to their broader univ. systems, e.g. "University of Maryland, College Park" is a branch of the University of Maryland System.

**Comment by BNewman2104** [comment]
I agree with that case, but I was referring a case more like the University of Maryland College of Behavioral and Social Sciences that has departments within the College, i.e., Department of Geographical Sciences. What are your thoughts on these?

**Comment by justgo129** [comment]
I've been doing something akin to:
UMD Department of Geographical Sciences is a department of BSOS.
UMD Department of Geography is a predecessor of UMD Department of Geographical Sciences.
BSOS is a division of the University of Maryland, College Park.
