### ISSUE TITLE
Add "member of" as an org relationship type

### ISSUE THREAD

**Issue by justgo129** [USGCRP/gcis#355]
I feel that our db of relationship types would be enhanced if "memberOf" were added.  Use cases include "member" universities of consortia and membership in international entities.  Example:

Jackson State University is a member of the Mississippi-Alabama Sea Grant Consortium.
The University of Oregon is a member of the Association of American Universities.
NWS is a member of the WMO.

We currently use "affiliated with" in all of these circumstances.  That's fine if we define "affiliated with" to include membership as "affiliated with" can mean a number of different things.  Otherwise, I assume this addition to the db and subsequent patching would be in order.  For instance, saying "something is affiliated with a consortium" can be confusing and doesn't necessarily imply membership or being a part of it.

**Comment by lomky** [comment]
Redundant #366
