### ISSUE TITLE
ordering of "cited by" entries has bad sorting logic

### ISSUE THREAD

**Issue by justgo129** [USGCRP/gcis#356]
For [this article](https://data.globalchange.gov/article/10.1016/S0140-6736%2807%2961257-4), note that the NCA3 chapters in which this article is cited isn't arranged numerically.  The db seems to be reading 27 before 9 because of the 2 in 27.  If it's the broader issue, I'd consider this a bug to be fixed.  If it's not, I don't think it's worth spending any time on this.

**Comment by rewolfe** [comment]
Cited by could be displayed as a table instead of a list.

**Comment by lomky** [comment]
This will be solved as part of #317
