### ISSUE TITLE
Extra row while adding an organization to the author

### ISSUE THREAD

**Issue by amruelama** [USGCRP/gcis#357]
You may have noticed an extra row while associating an author with an organization. See examples - [https://data.globalchange.gov/person/7616](https://data.globalchange.gov/person/7616) and [https://data-stage.globalchange.gov/person/9005](https://data-stage.globalchange.gov/person/9005)
Its a minor priority but needs to be fixed eventually.

**Comment by justgo129** [comment]
I've corrected it for a few by going to stage->edit and clicking on "delete" next to rows not followed by publications.  I agree with @amruelama that this should be fixed in an automated manner given the 9000+ people in GCIS.

**Comment by lomky** [comment]
@amruelama Can you confirm if this is fixed on the data-review instance?

**Comment by amruelama** [comment]
Steps to delete extraneous contributors : (Thanks @lomky )
- [ ] Query the number of contributors listed under person that has no org or article associated 
   
      SELECT count(1)
      FROM contributor
      LEFT JOIN publication_contributor_map ON contributor.id = publication_contributor_map.contributor_id
      WHERE publication_contributor_map.contributor_id IS NULL
          AND  contributor.person_id IS NOT NULL
          AND  contributor.organization_identifier IS NULL;
- [ ] Query to delete those rows 

       DELETE FROM contributor 
       WHERE id IN (
          SELECT contributor.id
          FROM contributor
          LEFT JOIN publication_contributor_map ON contributor.id = publication_contributor_map.contributor_id
          WHERE publication_contributor_map.contributor_id IS NULL
             AND contributor.person_id IS NOT NULL
             AND contributor.organization_identifier IS NULL
            );
- [ ] Test the queries on Dev 
- [ ] Delete the extraneous rows on Dev
- [ ] Delete the extraneous rows on Stage
- [ ] Push the changes to Prod
