### ISSUE TITLE
Add two or more activities for same dataset associated with the figure

### ISSUE THREAD

**Issue by amruelama** [USGCRP/gcis#359]
Currently, it is not possible to associate two activities with the same webpage/dataset for any figure. 

There are instances, I tried to associate three activities where Activity 1 is processing a  satellite image, Activity 2 is subsetting the same satellite image and Activity 3 is adding markers on the subsetted satellite image. In this case, I have to use the same dataset (satellite product) or same webpage (where the product is available) to associate with the different activities. 

Since I couldn't associate with three different activities, I have combined the activities (methodologies) into a single activity for now. 

See example - [https://data.globalchange.gov/report/nca3/chapter/human-health/figure/wildfire-smoke-has-widespread-health-effects](https://data.globalchange.gov/report/nca3/chapter/human-health/figure/wildfire-smoke-has-widespread-health-effects)
It would be a good enhancement going forward.

**Comment by zacharylandes** [comment]
@amruelama multiple activities per relationship has been added on dev/stage. Please verify
