### ISSUE TITLE
Accommodate non UTF-8 entries in SPARQL query outputs

### ISSUE THREAD

**Issue by justgo129** [USGCRP/gcis#363]
For some reason, non-UTF8 characters show up as unreadable when returned in SPARQL query outputs.  For instance, the name of the person described at
    http://data.globalchange.gov/person/10419outputs 
is returned as Mats BjÃ¶rk in SPARQL outputs even though it is returned correctly in the turtle:
    https://data.globalchange.gov/person/10419.thtml

**Comment by lomky** [comment]
@justgo129 That first link does not load. Are you talking about when the person is returned from the data.globalchange.gov/sparql ? If not, can you show me where we return SPARQL data from the person page?

**Comment by justgo129** [comment]
weird, the initial issue seems to work now.
http://data.globalchange.gov/sparql?default-graph-uri=&query=select+*+FROM+%3Chttp%3A%2F%2Fdata.globalchange.gov%3E+where+%7B+%0D%0A+++%3Fs+a+gcis%3APerson+.%0D%0A+++%3Fs+foaf%3AlastName+%3Fln+.%0D%0A+++FILTER+REGEX+%28%3Fln%2C+%22Bj%22+%29%0D%0A%7D%0D%0A&should-sponge=&format=text%2Fhtml&timeout=0&debug=on

**Comment by lomky** [comment]
Closing for now. Reopen if it starts happening again, or you come across a repeatable example. Thanks!
