### ISSUE TITLE
Extend the organizational relationships to include "member of" relationship

### ISSUE THREAD

**Issue by justgo129** [USGCRP/gcis#366]
We have quite a few consortia in GCIS, such as: UCAR, MRLC, and the Arctic Research Consortium of the United States (ARCUS) to name a few.  We've been using "affiliated with" to describe a member relation, e.g.  the University of Alaska at Fairbanks is affiliated with ARCUS.

A similar example describes member national weather agencies to WMO.  For example, we currently have "NOAA is Affiliated With the WMO."

 I think it would be better if we added "member of" as an organizational relational type in the database, and automatically re-associate (with a script) these members with the consortia to which they belong using "member of."  "Member of" just seems more logical than "affiliated with" in such circumstances.

**Comment by lomky** [comment]
@justgo129 @amruelama Can you explain more strictly what qualifies something to be a "member" of something else? It feels more vague to me that the current association of "affiliated with", which is completely accurate if not very precise. Can you help me understand the contexts in which this ontological relationship would apply, and when it wouldn't?

This is our current list of relationships, for reference:

```
department of
funded by
division of
branch of
affiliated with
bureau of
program of
committee of
task force of
working group of
predecessor of
office of
subcommittee of
council of
agency of
commission of
managed by
operated by
unit of
center of
```

**Comment by justgo129** [comment]
https://github.com/USGCRP/gcis/wiki/Conventions -> "Adding organizations to
GCIS" should also help.

On Tue, Jun 21, 2016 at 9:44 AM, Kathryn Tipton <notifications@github.com>
wrote:

> @justgo129 <https://github.com/justgo129> @amruelama
> <https://github.com/amruelama> Can you explain more strictly what
> qualifies something to be a "member" of something else? It feels more vague
> to me that the current association of "affiliated with", which is
> completely accurate if not very precise. Can you help me understand the
> contexts in which this ontological relationship would apply, and when it
> wouldn't?
>
> This is our current list of relationships, for reference:
>
> department of
> funded by
> division of
> branch of
> affiliated with
> bureau of
> program of
> committee of
> task force of
> working group of
> predecessor of
> office of
> subcommittee of
> council of
> agency of
> commission of
> managed by
> operated by
> unit of
> center of
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/USGCRP/gcis/issues/366#issuecomment-227443714>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AHSmYXgn07kCu6r4Tww4aBT69Td00w5Jks5qN-qxgaJpZM4I35VC>
> .
>



-- 
________________________________
Justin Goldstein, Ph.D.
Advance Science Coordinator
US Global Change Research Program
National Coordination Office
Contractor

1800 G Street NW, Suite 9100 (*Note New Address)*
Washington, D.C. 20006, U.S.A.
phone: (202) 419-3496
e-mail: jgoldstein AT usgcrp Dot gov

http://www.globalchange.gov

**Comment by lomky** [comment]
@justgo129 that is a super useful page, thanks! I am still unsure how you would define and bound member_of specifically though? 

As in, I understand when something is a "department_of" (universities and colleges can have them, well defined in academia), and when something is a "agency_of" (well defined in the government sphere). 

But how do we distinguish "member_of" vs "unit_of", for example?

It's fully possible I am missing a larger picture, since this ontology is new to me. I appreciate any feedback & input.

**Comment by justgo129** [comment]
Sure.  We've been using "unit of" to describe National Park System "(NPS) units."  Each park in the NPS is officially called a "unit," just like each department in a university is officially called a "department."  

We can decide to just stick with "affiliated with;" we never formally defined it.  Semantically, we've mapped all these relationship types to just three - see https://github.com/USGCRP/gcis/pull/361 and https://github.com/USGCRP/gcis/pull/362.

**Comment by rewolfe** [comment]
Shouldn't we have a brief description of each of these relationships in
GCIS?

On Tue, Jun 21, 2016 at 9:44 AM, Kathryn Tipton <notifications@github.com>
wrote:

> @justgo129 <https://github.com/justgo129> @amruelama
> <https://github.com/amruelama> Can you explain more strictly what
> qualifies something to be a "member" of something else? It feels more vague
> to me that the current association of "affiliated with", which is
> completely accurate if not very precise. Can you help me understand the
> contexts in which this ontological relationship would apply, and when it
> wouldn't?
>
> This is our current list of relationships, for reference:
>
> department of
> funded by
> division of
> branch of
> affiliated with
> bureau of
> program of
> committee of
> task force of
> working group of
> predecessor of
> office of
> subcommittee of
> council of
> agency of
> commission of
> managed by
> operated by
> unit of
> center of
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/USGCRP/gcis/issues/366#issuecomment-227443714>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AHR7GZeP6mB50-buM289D4totNKCDchDks5qN-qxgaJpZM4I35VC>
> .
>



-- 
Robert Wolfe, NASA GSFC @ USGCRP, o: 202-419-3470, m: 301-257-6966

**Comment by justgo129** [comment]
I like that idea very much.  First, do we need all of these entries given
that we've narrowed the number of semantic relationships to 2 (3 when we
consider predecessor?)    I'm fine keeping both since the relational
database differs from the semantic one but I see merit in both perspectives.


On Tue, Jun 21, 2016 at 1:48 PM, Robert Wolfe <notifications@github.com>
wrote:

> Shouldn't we have a brief description of each of these relationships in
> GCIS?
>
> On Tue, Jun 21, 2016 at 9:44 AM, Kathryn Tipton <notifications@github.com>
> wrote:
>
> > @justgo129 <https://github.com/justgo129> @amruelama
> > <https://github.com/amruelama> Can you explain more strictly what
> > qualifies something to be a "member" of something else? It feels more
> vague
> > to me that the current association of "affiliated with", which is
> > completely accurate if not very precise. Can you help me understand the
> > contexts in which this ontological relationship would apply, and when it
> > wouldn't?
> >
> > This is our current list of relationships, for reference:
> >
> > department of
> > funded by
> > division of
> > branch of
> > affiliated with
> > bureau of
> > program of
> > committee of
> > task force of
> > working group of
> > predecessor of
> > office of
> > subcommittee of
> > council of
> > agency of
> > commission of
> > managed by
> > operated by
> > unit of
> > center of
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/USGCRP/gcis/issues/366#issuecomment-227443714>, or
> mute
> > the thread
> > <
> https://github.com/notifications/unsubscribe/AHR7GZeP6mB50-buM289D4totNKCDchDks5qN-qxgaJpZM4I35VC
> >
> > .
> >
>
>
>
> --
> Robert Wolfe, NASA GSFC @ USGCRP, o: 202-419-3470, m: 301-257-6966
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/USGCRP/gcis/issues/366#issuecomment-227517643>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AHSmYVzKEZMY0RFJ9ayg4ZxNOoUWsTMUks5qOCPSgaJpZM4I35VC>
> .
>



-- 
________________________________
Justin Goldstein, Ph.D.
Advance Science Coordinator
US Global Change Research Program
National Coordination Office
Contractor

1800 G Street NW, Suite 9100 (*Note New Address)*
Washington, D.C. 20006, U.S.A.
phone: (202) 419-3496
e-mail: jgoldstein AT usgcrp Dot gov

http://www.globalchange.gov

**Comment by rewolfe** [comment]
Consider adding a description for these fields (with an example of use).

**Comment by amruelama** [comment]
Add 'member of' relationship

**Comment by zacharylandes** [comment]
@amruelama verify updates on stage
https://data-stage.globalchange.gov/organization/aalborg-university/edit
