### ISSUE TITLE
Enable aliasing in searches, e.g. "udel" same results as "university+of+delaware"

### ISSUE THREAD

**Issue by justgo129** [USGCRP/gcis#367]
Performing the following search:
    https://data.globalchange.gov/search?q=university+of+delaware
in GCIS returns several datasets.  Is there a way we can formally relate UDel with these datasets within the db?  I see many examples of this type of question within GCIS, e.g., with the University of New Hampshire

**Comment by lomky** [comment]
- [ ] Create an exterm dataset for US colleges & associate them.
 - [ ] Enable searching by alias

**Comment by amruelama** [comment]
Alias search is implemented. As part of ROR API integration, we will pull acronyms and alternate names to org db.
