### ISSUE TITLE
Allow the user to query X items per page, including all, up to the technical limitation

### ISSUE THREAD

**Issue by amruelama** [USGCRP/gcis#368]
Since there are 9000+ authors in our database currently, querying all the authors using https://data.globalchange.gov/person?all=1 won't work and shows 'bad gateway' error.

[JSON](https://data.globalchange.gov/person.json?all=1) and [YAML](https://data.globalchange.gov/person.yaml?all=1) seem to work, but couldn't generate [CSV](https://data.globalchange.gov/person.csv?all=1) and [HTML](https://data.globalchange.gov/person.html?all=1) of all the authors.
Adding one or two 'Show All' button will help to fix this issue.

Any other suggestions @lomky?

**Comment by lomky** [comment]
I think you meant "https://data.globalchange.gov/person?all=1" ? The all parameter is actually working here, but we are running into the apache timeout when trying to display them.

As a workaround for the moment, you can download them from your command line like so:

`curl "https://data.globalchange.gov/person.FORMAT?all=1" >all_persons.FORMAT`

So to get the CSV file for all persons, you would run this:

`curl https://data.globalchange.gov/person.csv?all=1 >all_persons.csv`

An example when I pulled it:

```
Fri Jun 17 18:31:04 [master !]~/gcis $ curl https://data.globalchange.gov/person.csv?all=1 >all_persons.csv
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1010k  100 1010k    0     0   120k      0  0:00:08  0:00:08 --:--:--  321k
Fri Jun 17 18:31:26 [master !?]~/gcis $ wc -l all_persons.csv #Line count on the file
9443 all_persons.csv
Fri Jun 17 18:31:57 [master !?]~/gcis $ head -5 all_persons.csv
uri,href,first_name,id,last_name,middle_name,orcid,url
/person/932,http://data.globalchange.gov/person/932,Nicky,932,Sheats,,,http://www.tesc.edu/watson/institute/Meet-the-Director.cfm
/person/859,http://data.globalchange.gov/person/859,Elena,859,Shevliakova,,,http://www.gfdl.noaa.gov/elena-shevliakova-homepage
/person/1975,http://data.globalchange.gov/person/1975,Michael,1975,Brewer,,,
/person/826,http://data.globalchange.gov/person/826,Marc,826,Gaden,,,
```

To solve the underlying problem, I can add the "Show All" button (maybe labelled at "Show Max", since it won't always display all),  add a cap on how many "all" can actually give you through the web front end, maybe capped at a couple thousand. Better to get a few pages than a web error.

**Comment by justgo129** [comment]
This also relates to #256 and #345.

**Comment by amruelama** [comment]
@lomky Yes, it's https://data.globalchange.gov/person?all=1. I just corrected it. And the CSV also works now using https://data.globalchange.gov/person.csv?all=1. It's just the [HTML](https://data.globalchange.gov/person.html?all=1) (all authors) that has time-out issue.

**Comment by lomky** [comment]
@justgo129 what was the reasoning behind #256 ?

**Comment by justgo129** [comment]
@lomky it was to address an earlier bug but I don't remember the details.  @rewolfe?

**Comment by rewolfe** [comment]
I'm not sure.  I think there is an inconsistency where some places we use
"?show_all" and other places we use the "?all=1" switch.  I can't remember
the specific case that caused the bug that this fixes.

On Tue, Jun 21, 2016 at 9:40 AM, justgo129 <notifications@github.com> wrote:

> @lomky <https://github.com/lomky> it was to address an earlier bug but I
> don't remember the details. @rewolfe <https://github.com/rewolfe>?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/USGCRP/gcis/issues/368#issuecomment-227442832>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AHR7Ge0_Rx72KDVCyCZOk56fWKB1PHqaks5qN-nrgaJpZM4I4l2l>
> .
>



-- 
Robert Wolfe, NASA GSFC @ USGCRP, o: 202-419-3470, m: 301-257-6966

**Comment by lomky** [comment]
@rewolfe @justgo129 Okay, I just wanted to make sure there wasn't some reason to avoid the functionality behind a larger query option.

**Comment by lomky** [comment]
All list pages now respect the `per_page` parameter. Next up, code a selector into the HTML page.

**Comment by lomky** [comment]
- [x] List pages allow per_page parameter
- [ ] Allow selection of per_page in the HTML
- [ ] Update tests.

**Comment by lomky** [comment]
@amruelama Please review the changes on data-review. 

The per_page selectors should be visible on _every_ Resource's listing page, and they should work.

---

First Load:  
![screen shot 2018-01-03 at 2 14 50 pm](https://user-images.githubusercontent.com/6129479/34535691-b4b89560-f090-11e7-8551-43be67ff2dd0.png)
  
  
After hitting a button:  
![screen shot 2018-01-03 at 2 15 06 pm](https://user-images.githubusercontent.com/6129479/34535695-b8ed72cc-f090-11e7-8538-6cbc3af62a2f.png)

---

You can also type any number in you want into the URL param:  
![screen shot 2018-01-03 at 2 15 18 pm](https://user-images.githubusercontent.com/6129479/34535720-cdf82964-f090-11e7-9802-596895292982.png)

**Comment by amruelama** [comment]
@lomky Looks good in data-review! Is 100 the maximum limit?

**Comment by lomky** [comment]
@amruelama Nope. No limit is imposed. You can change the URL to have any number you want. 

I chose not to have those options prominent (as buttons), as they are very slow and would be a bad user interaction. I tested up to 500.

**Comment by lomky** [comment]
Putting a hold on this ticket until TravisCI is reliable again post-Meltdown.
