### ISSUE TITLE
Bug when download CSV on an Organization Contributing Authors List

### ISSUE THREAD

**Issue by amruelama** [USGCRP/gcis#371]
'CSV' doesn't work for the following links and needs fixed. HTML, YAML and JSON works fine.

1. https://data.globalchange.gov/organization/us-global-change-research-program/contributions/author/report.csv?all=1  
2. http://data.globalchange.gov/organization/us-global-change-research-program/contributions/distributor/report.csv?all=1

This issue is a part of [this](https://github.com/USGCRP/gcis-internal/issues/12) issue in @USGCRP/gcis-internal .

**Comment by lomky** [comment]
Going to dig into this a bit now that I am more familiar with the Tuba Mojolicious structure.

Tagging the issue @amruelama indicated: USGCRP/gcis-internal#12

**Comment by lomky** [comment]
Apparently Organizations simply lacked the CSV form, leading to this bug. Also added the mirror path to Persons.
