### ISSUE TITLE
GCIS Faceted Search Web Interface

### ISSUE THREAD

**Issue by rewolfe** [USGCRP/gcis#372]
Install, test and deploy JPL GCIS Faceted Search Web Interface - https://github.com/USGCRP/gcis-search

Should automatically sync with GCIS production database.

Link to GCIS main menu.

**Comment by lomky** [comment]
Got the servers up and running:

### GCIS-Search - Server

 - Clone the repo
 - Correct the requirements 
   - add `requests==2.1.0` to the requirements.txt
 - Properly install virtualenv & activate it
   - `sudo pip install virtualenv`
   - `sudo pip install virtualenvwrapper`
   - `mkvirtualenv gcis-search`
   - `workon gcis-search`
 - Run the deps install:
   - `make deps`
 - Run the server:
   - `./manage.py server`

### ElasticSearch

  - Download & install the 2.* version
  - run it: `./bin/elasticsearch`

**Comment by lomky** [comment]
Currently getting a `404` on searching. Looks like I need to load the data. Possibly via the scripts.

**Comment by lomky** [comment]
After getting an updated readme from @pymonger ( :100: !), I successfully have the system running on my local linux box with ES 1.7.6.

**Comment by lomky** [comment]
We are done with this as far as CSSR is concerned. Putting into the backlog behind CSSR-tasks, but should be an easy finish after that.

**Comment by lomky** [comment]
System is currently running, with proper reverse proxy on data-review.

Todo before final deployment:
  - [ ] test configuration on data-dev
  - [ ] design process for updating ES data
  - [ ] update content push process to update ES data, as decided above

**Comment by lomky** [comment]
Optional: The map is a little overbearing at the moment. The facet is much more useful to use than the spatial search. Consider modifying the design.
