### ISSUE TITLE
Link to Climate Data Sets in Data.gov

### ISSUE THREAD

**Issue by rewolfe** [USGCRP/gcis#374]
Link to Climate Data Sets in Data.gov.  Add sync scripts to automatically link to new climate data tagged in Data.gov.

**Comment by lomky** [comment]
@rewolfe what is the status of this ticket?

**Comment by rewolfe** [comment]
@lomky, @amruelama - I think that this ticket can be closed.  The scripts I wrote to do this are now in GitHub.  There are a few (~10) CDI datasets that have been added to data.gov since I did the ingest that should also be added.  However, we still need to add the CDI tags to the datasets which should be a new ticket.  This latter tickets is dependent on the vocabulary code (and CDI content) delivery from the CDI/GCIS team.
