### ISSUE TITLE
Increase the row limits to more than 10,000 (or max rows) in Virtuoso configuration

### ISSUE THREAD

**Issue by amruelama** [USGCRP/gcis#376]
[This](https://data.globalchange.gov/sparql?default-graph-uri=&query=%0D%0Aselect+%0D%0A+%3Fpub+as+%3FOrganization%0D%0A%0D%0A%0D%0A%3Fauthor+as+%3FAuthor%0D%0ACONCAT%28str%28%3Fln%29%2C+%22%2C+%22%2C+str%28%3Fgn%29%29+as+%3FName+%0D%0A+str%28%3Forg_name%29+as+%3FOrganizationName%0D%0A+++++++%0D%0A+FROM+%3Chttp%3A%2F%2Fdata.globalchange.gov%3E+where+%7B+%0D%0A%23%3Fpub+a++UNION+%7Bgcis%3AAcademicArticle+gcis%3AReport+%7D+.%0D%0A%3Fpub+a++gcis%3AReport+.%0D%0A%3Fpub+prov%3AqualifiedAttribution+%5B+prov%3AhadRole+%3Frole+%3B+prov%3Aagent+%3Fauthor+%3B+prov%3AactedOnBehalfOf+%3Forg+%5D+.%0D%0A%3Fauthor+foaf%3AgivenName+%3Fgn+.%0D%0A%3Fauthor+foaf%3AlastName+%3Fln+.%0D%0A%3Forg++skos%3AprefLabel+%3Forg_name%0D%0A%0D%0A%0D%0A%0D%0A%7D+%0D%0A&should-sponge=&format=text%2Fhtml&timeout=0&debug=on) is an example web query to show the list of authors with related organization(s). Right now, the limit is 10,000 rows. We may have to increase the limit to more than 10,000 or maximum rows.

**Comment by lomky** [comment]
@amruelama do you have a suggestion for a good upper limit to change to?

Grabbing the example SPARQL query used:

```
select 
 ?pub as ?Organization
 ?author as ?Author
CONCAT(str(?ln), ", ", str(?gn)) as ?Name 
 str(?org_name) as ?OrganizationName
 FROM <http://data.globalchange.gov> where { 
 # ?pub a  UNION {gcis:AcademicArticle gcis:Report } .
   ?pub a  gcis:Report .
   ?pub prov:qualifiedAttribution [ prov:hadRole ?role ; prov:agent ?author ; prov:actedOnBehalfOf ?org ] .
   ?author foaf:givenName ?gn .
   ?author foaf:lastName ?ln .
   ?org  skos:prefLabel ?org_name
} 
```

**Comment by amruelama** [comment]
Since 'person' or 'people' has highest number of datasets (9000 +),  and considering each author has an average of 5 related organizations, I would say let's increase it to 50,000? Any suggestion @justgo129 ?
Also, what would be the issue if we use 'max row limits'?

**Comment by lomky** [comment]
@amruelama we may run into performance issue or timeout issues at a higher number, but I will confirm that during implementation. We can solve that problem **if** it comes up.

**Comment by rewolfe** [comment]
50K sounds good.

On Tue, Jun 21, 2016 at 10:25 AM, Kathryn Tipton <notifications@github.com>
wrote:

> @amruelama <https://github.com/amruelama> we may run into performance
> issue or timeout issues at a higher number, but I will confirm that during
> implementation. We can solve that problem *if* it comes up.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/USGCRP/gcis/issues/376#issuecomment-227456211>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AHR7GY_NcpyDvvcfHGsX4F_K0SOEfdeLks5qN_RMgaJpZM4I6wf3>
> .
>



-- 
Robert Wolfe, NASA GSFC @ USGCRP, o: 202-419-3470, m: 301-257-6966

**Comment by lomky** [comment]
Is our production Virtuoso config stored anywhere in our repositories, or just maintained in production?

**Comment by lomky** [comment]
@amruelama I have made the change on our ICF dev instance. Can you check if it is reacting as you expect? The example query now gives me 10281 results.

**Comment by rewolfe** [comment]
I believe the Virtuoso config is just maintained in production.  Also, the
scripts for pushing to Virtuoso are maintained in production.  We should
find a place for them in GCIS.  Probably an example Virtuoso config in the
public repository and the actual one in the internal repository.

On Tue, Jun 28, 2016 at 11:48 AM, Kathryn Tipton <notifications@github.com>
wrote:

> @amruelama <https://github.com/amruelama> I have made the change on our
> ICF dev instance. Can you check if it is reacting as you expect? The
> example query now gives me 10281 results.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/USGCRP/gcis/issues/376#issuecomment-229092097>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AHR7GX2GJN8q3bqJ9hiZzXfu6XQta9Nnks5qQUJagaJpZM4I6wf3>
> .
>



-- 
Robert Wolfe, NASA GSFC @ USGCRP, o: 202-419-3470, m: 301-257-6966

**Comment by amruelama** [comment]
The example query still returns 10,000 rows for me @lomky. I tried [Yasgui](http://yasgui.org/#) editor as well.

**Comment by lomky** [comment]
@amruelama I forgot you don't have ICF dev access; I emailed you a CSV copy of the output for review.

**Comment by lomky** [comment]
Tasks on this ticket:

- [ ] Edit the dev config to increase max result rows to 50k & confirm functionality
- [ ] Edit the production config to increase max result rows to 50k
- [ ] Copy that config & the virtuoso release script(s) into our private repo
- [ ] Generalize the config and place that into our public repo

**Comment by lomky** [comment]
@amruelama @bakamine Is there a pressing need to change the current production environment to support 50k, or should I just update the new ICF instances and the functionality will enable when we finish the server migration?

**Comment by amruelama** [comment]
@lomky The table you sent me is fine for now. 
@bakamine Should we wait until the server migration? As of now, I think the list (10281 rows) generated using ICF's interface is fine for me.

**Comment by bakamine** [comment]
If 10k isn't presenting some major operational roadblock, I'd say hold off
until server migration.

On Tue, Jun 28, 2016 at 3:21 PM, Amrutha Elamparuthy <
notifications@github.com> wrote:

> @lomky <https://github.com/lomky> The table you sent me is fine for now.
> @bakamine <https://github.com/bakamine> Should we wait until the server
> migration? As of now, I think the list (10281 rows) generated using ICF's
> interface is fine for me.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/USGCRP/gcis/issues/376#issuecomment-229154256>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AQKQXewHHxMqx3czQmlRKBD74Ls6-AFFks5qQXQngaJpZM4I6wf3>
> .
>



-- 
Bradley Akamine
Chief Digital Officer
U.S. Global Change Research Program
National Coordination Office
Contractor
Office: (202) 419-3479
Mobile: (202) 812-0428

**Comment by lomky** [comment]
The Virtuoso install scripts live in the [gcis-rdf repo](https://github.com/USGCRP/gcis-rdf) already. I will add the sample config there as well.

**Comment by lomky** [comment]
As a note, that install script currently specifies the old servers and will need to be updated.

**Comment by lomky** [comment]
ICF RDF servers are properly configured to 50k rows in dev, test, and prod. The install scripts were already in-repo. Added the sample config to that repo, and the production-configured one to the private repo.

**Comment by lomky** [comment]
See commits gcis-rdf:9014ab3 and gcis-internal:25a45a3  for the work done.
