### ISSUE TITLE
Enhance wiki

### ISSUE THREAD

**Issue by justgo129** [USGCRP/gcis#377]
I think we can clean up the wiki a bit.  During the conversion from our previous host, various things seemed to have occurred:
  

- The locations of the # (comment) signs through-out are now juxtaposed within the text rather than in separate lines, making the text very difficult to read.  There are many examples under "org conventions."
- Some hyperlinks seem to have disappeared.  Example: the first item under "org conventions" (in the "conventions" page) should be a hyperlink.
- It would great if we used deep links to access wiki material from the main wiki page.  For instance, this would enable one to reach the "org conventions" material from the "conventions" page without scrolling down or using Ctrl+F.

**Comment by justgo129** [comment]
@lomky is this ready for closure?

**Comment by lomky** [comment]
Closing, as improving the wiki is now just a general task we are regularly doing.
