### ISSUE TITLE
Health Assessment Assets

### ISSUE THREAD

**Issue by bakamine** [USGCRP/gcis#379]
The figure images for the health assessment are currently stored as assets in GCIS ([example](http://data.globalchange.gov/file/ed23fed1-d8d1-4b54-badb-f1e0dccbc521)). They should, instead, point to remote images we now have stored in S3.
Bucket:

> https://climatehealth2016.s3.amazonaws.com/climatehealth2016/gcis-figures

Naming convention:

> Figure-c.n_s.png
> 
> where
> 
> c is the chapter
> n is the ordinal
> _s are sub-image index starting with “a”, “b”, etc

I'm told you should be able to use this as a starting point to script the operation:

> https://gist.github.com/abuddenb/2e5400ea20c5f2da79feb5df0ab7e55f

**Comment by lomky** [comment]
@bakamine could I get access to the AWS account? I have no plans on changing anything in the S3,  access will just allow me to test this more robustly.

**Comment by amruelama** [comment]
Referencing [this](https://github.com/USGCRP/gcis-internal/issues/12) issue to let you know I had been working on migrating PDF distributed reports from 'Assets' to [downloads.globalchange.gov](url) manually (by adding URL). Some of them had Amazon AWS links as well - I didn't migrate those URLs. 
The most recent CCHHG (2016) report I uploaded is saved in Assets but needs to be in downloads. 
@bakamine I think it's good to store them directly on downloads.globalchange.gov or Amazon AWS while we upload a file. This would reduce the time on uploading the files to downloads and then adding the URLs later to link them to the appropriate location. Do you think this approach is fine?

**Comment by lomky** [comment]
@bakamine there seems to be a missing asset in S3. We have [a figure](https://data.globalchange.gov/report/usgcrp-climate-human-health-assessment-2016/chapter/front-matter/figure/understanding-the-exposure-pathway-diagrams) in chapter 'front-matter', but in the S3 figures start with `Figure-0.1.png` being the first one in 'executive-summary', which the next chapter.

Did we miss adding that figure to the S3,  and may I add it manually myself or is there a process?

**Comment by lomky** [comment]
Actually, there seem to be a few figures missing from the S3.

This is what I find when I walk through the 2016 Health Report Figures right now. bolded are not represented in the S3. I have not yet checked the sub-image files.

|Chapter|Generated S3 ID|Figure ID|Assets Link|Note|
|---|---|---|---|---|
|front-matter|**Figure-*F*.1**|understanding-the-exposure-pathway-diagrams|[Current Location](https://data.globalchange.gov/assets/e9/cd/d12130edff0ab74c2a00c96e2775/about_exposure-path_v2_3.png)|Missing, No chapter represented.|
|executive-summary|Figure-0.1|examples-of-climate-impacts-on-human-health|[Current Location](https://data.globalchange.gov/assets/ce/fc/64f097ca623c76f81d31543a69a2/es_summary-exposure-path_v10.png)||
|executive-summary|Figure-0.2|es-climate-change-and-health|[Current Location](https://data.globalchange.gov/assets/84/1d/a76c0faffea0329333625f3adee0/es_intro-pathways_v3.png)||
|executive-summary|Figure-0.3|es-projected-changes-in-deaths-in-us-cities-by-season|[Current Location](https://data.globalchange.gov/assets/4c/85/16d7e941dcc15c7315e2994dceb6/es_2.png)||
|executive-summary|Figure-0.4|es-projected-change-in-temperature-ozone-and-ozone-related-premature-deaths-in-2030|[Current Location](https://data.globalchange.gov/assets/7e/a1/319080ca1f9f738a069fa98ad624/es_temp-ozone-deaths-2030_v1.png)||
|executive-summary|Figure-0.5|es-estimated-deaths-and-billion-dollar-losses-from-extreme-weather-events-in-the-u-s-2004-2013|[Current Location](https://data.globalchange.gov/assets/ac/30/20e63f751e8cd733c04aa2d3dc1f/es_10yr-avg-fatalities_v2.png)||
|executive-summary|Figure-0.6|es-changes-in-lyme-disease-case-report-distribution|[Current Location](https://data.globalchange.gov/assets/73/4e/99a9aad6a8b27cd6ca8beeeb5bed/Figure-5.2.png)||
|executive-summary|Figure-0.7|es-links-between-climate-change-water-quantity-and-quality-and-human-exposure-to-water-related-illness|[Current Location](https://data.globalchange.gov/assets/80/82/73fccfd8a513dca21f8115ef3085/es_water-related-illness-links_v1.png)||
|executive-summary|Figure-0.8|es-farm-to-table|[Current Location](https://data.globalchange.gov/assets/af/ce/be8c247c232a0956cb88b7553392/es_farm-to-table-v2.png)||
|executive-summary|Figure-0.9|es-the-impact-of-climate-change-on-physical-mental-and-community-health|[Current Location](https://data.globalchange.gov/assets/1d/9e/8e7dab83460fbf623f2c62dd59cc/es_climate-impacts-and-health_v3.png)||
|executive-summary|**Figure-0.10**|es-determinants-of-vulnerability|[Current Location](https://data.globalchange.gov/assets/a8/d2/31c91eae80cfa6b998bc9a9c2f5a/es_determinants-vulnerability_v1_0.png)|Just missing?|
|climate-change-and-human-health|Figure-1.1|major-us-climate-trends|[Current Location](https://data.globalchange.gov/assets/95/19/36a07fe379ff077779d5db8033d5/intro_observed-climate_v12.png)||
|climate-change-and-human-health|Figure-1.2|change-in-number-of-extreme-precipitation-events|[Current Location](https://data.globalchange.gov/assets/ba/b2/9c136ede9dd29bcc418f8a6a155a/intro_us_extreme_precip_index_v3.png)||
|climate-change-and-human-health|Figure-1.3|projected-changes-in-temperature-and-precipitation-by-mid-century|[Current Location](https://data.globalchange.gov/assets/be/60/1d17f05e6c42f30467c43408b6dc/intro_project-changes-temp-precip-mid-century_v2.png)||
|climate-change-and-human-health|Figure-1.4|projected-changes-in-hottest-coldest-and-wettest-driest-day-of-the-year|[Current Location](https://data.globalchange.gov/assets/62/40/2e25bf45683c2bd78a08bbf91d12/intro_project-changes-hot-cold-wet-dry_v4.png)||
|climate-change-and-human-health|Figure-1.5|climate-change-and-health|[Current Location](https://data.globalchange.gov/assets/28/bf/0ccfa481c5b6508d6e89765aa406/intr_-pathways_v9_0.png)||
|climate-change-and-human-health|Figure-1.6|sources-of-uncertainty|[Current Location](https://data.globalchange.gov/assets/28/84/b016a50d280a3d78d3f3c7a93817/intro_sources-of-uncertainty_v2.png)||
|temperature-related-death-and-illness|Figure-2.1|climate-change-and-health-extreme-heat|[Current Location](https://data.globalchange.gov/assets/d0/d3/ebfe50af7d89e0f75c106df2f4c4/thermal_heat-wave-pathways_v5.png)||
|temperature-related-death-and-illness|Figure-2.2|heat-related-deaths-during-the-1995-chicago-heat-wave|[Current Location](https://data.globalchange.gov/assets/5f/37/a6dc9592350692ac93f53e78ca29/thermal_heat-related-deaths-1995-chicago_v1.png)||
|temperature-related-death-and-illness|Figure-2.3|projected-changes-in-temperature-related-death-rates|[Current Location](https://data.globalchange.gov/assets/1e/83/25d15b22f7d82646b21c2b2a7c8d/figure-8-gfdl-city-2100-mortality-map-2015.png)||
|temperature-related-death-and-illness|Figure-2.4|projected-changes-in-deaths-in-us-cities-by-season|[Current Location](https://data.globalchange.gov/assets/4c/85/16d7e941dcc15c7315e2994dceb6/thermal_projected-changes-in-death_v2_0.png)||
|air-quality-impacts|Figure-3.1|climate-change-and-health-outdoor-air-quality|[Current Location](https://data.globalchange.gov/assets/62/e6/0b61ae5b59d4c01dd3a4ae57315b/air_outdoor-air-pathways_v6.png)||
|air-quality-impacts|Figure-3.2|projected-change-in-temperature-ozone-and-ozone-related-premature-deaths-in-2030|[Current Location](https://data.globalchange.gov/assets/b9/8b/7e5047105e25dc60611ecba1e9b4/air_temp-ozone-deaths-2030_v6_0.png)||
|air-quality-impacts|Figure-3.3|projected-change-in-ozone-related-premature-deaths|[Current Location](https://data.globalchange.gov/assets/5f/b4/7a4b43b68bed591d570ec25b6a19/Figure-3.3.png)||
|air-quality-impacts|Figure-3.4|ragweed-pollen-season-lengthens|[Current Location](https://data.globalchange.gov/assets/08/0c/6de54644c71de449c1b4d2e85933/air_ragweed-pollen-season-lengthens_v1.png)||
|extreme-events|Figure-4.1|estimated-deaths-and-billion-dollar-losses-from-extreme-weather-events-in-the-us-2004-2013|[Current Location](https://data.globalchange.gov/assets/ac/30/20e63f751e8cd733c04aa2d3dc1f/extreme_10yr-avg-fatalities_v6.png)||
|extreme-events|Figure-4.2|climate-change-and-health-flooding|[Current Location](https://data.globalchange.gov/assets/95/d9/b129972ff957cdb993b4281cec58/extreme_flooding-pathways_v6_1.png)||
|extreme-events|Figure-4.3|hurricane-induced-flood-effects-in-eastern-and-central-united-states|[Current Location](https://data.globalchange.gov/assets/0f/e2/23d9f7b1d62036dc696e2128c531/extreme_hurricane-induced-flood-effects_v2.png)||
|extreme-events|Figure-4.4|projected-increases-in-very-large-fires|[Current Location](https://data.globalchange.gov/assets/ab/ad/3f3fb3d1762ccd0fe683e33db11e/extremes_future-very-large-fires_v1.png)||
|vectorborne-diseases|Figure-5.1|climate-change-and-health-lyme-disease|[Current Location](https://data.globalchange.gov/assets/00/ab/61af4acbad91a7aeab8607ebd711/vector_lyme-disease-pathways_v7.png)||
|vectorborne-diseases|Figure-5.2|changes-in-lyme-disease-case-report-distribution|[Current Location](https://data.globalchange.gov/assets/73/4e/99a9aad6a8b27cd6ca8beeeb5bed/Figure-5.2.png)||
|vectorborne-diseases|Figure-5.3|life-cycle-of-blacklegged-ticks-ixodes-scapularis|[Current Location](https://data.globalchange.gov/assets/05/1d/4c994fb947dbd69c88f34cd3fe4c/vector_tick-life-cycle_v6.png)||
|vectorborne-diseases|Figure-5.4|projected-change-in-lyme-disease-onset-week|[Current Location](https://data.globalchange.gov/assets/62/1d/83c5f12d005012adb20ba36ba111/vector_lime-disease-onset_v2.png)||
|vectorborne-diseases|Figure-5.5|incidence-of-west-nile-neuroinvasive-disease-by-county-in-the-united-states|[Current Location](https://data.globalchange.gov/assets/56/58/f310e6065fb0dbf2e6ddc9026bc9/vector_wn-neuroinvasive-disease_v1.png)||
|vectorborne-diseases|Figure-5.6|climate-impacts-on-west-nile-virus-transmission|[Current Location](https://data.globalchange.gov/assets/74/71/f50b5b6df7058220204b3e6a6c9d/vector_climate-impacts-wnv-transmission_v3_0.png)||
|water-related-illnesses|Figure-6.1|climate-change-and-health-vibrio|[Current Location](https://data.globalchange.gov/assets/ee/47/d4bdc824f58f7d86617027492448/waterborne_vibrio-pathways_v4.png)||
|water-related-illnesses|Figure-6.2|links-between-climate-change-water-quantity-and-quality-and-human-exposure-to-water-related-illness|[Current Location](https://data.globalchange.gov/assets/33/61/eba491a8a0e572343d3ea6095c6f/waterborne_water-related-illness-links_v2.png)||
|water-related-illnesses|Figure-6.3|locations-of-livestock-and-projections-of-heavy-precipitation|[Current Location](https://data.globalchange.gov/assets/9a/aa/b81f1864aff389b660fd8c34d96b/waterborne_farms-and-heavy-precip_v5.png)||
|water-related-illnesses|Figure-6.4|projections-of-vibrio-occurrence-and-abundance-in-chesapeake-bay|[Current Location](https://data.globalchange.gov/assets/eb/49/3f57498563046f9244d8c42fcea9/waterborne_vibrio-chesapeakebay_v1_4.png)||
|water-related-illnesses|Figure-6.5|changes-in-suitable-coastal-vibrio-habitat-in-alaska|[Current Location](https://data.globalchange.gov/assets/5a/89/52cabef1ca2669f9874eaa6cf102/waterborne_range-model-projection-sst_v2_2.png)||
|water-related-illnesses|Figure-6.6|projected-changes-in-caribbean-gambierdiscus-species|[Current Location](https://data.globalchange.gov/assets/5a/b6/9ac3b14589691834057558fc90c7/waterborne_proj-changes-caribean-gambierdiscus-species_v2_4.png)||
|water-related-illnesses|Figure-6.7|projections-of-growth-of-alexandrium-in-puget-sound|[Current Location](https://data.globalchange.gov/assets/4d/44/57531e0718b57fc33ebc92cbe5a1/waterborne_alexandrium-pugetsound_v1_2.png)||
|food-safety-nutrition-and-distribution|Figure-7.1|farm-to-table|[Current Location](https://data.globalchange.gov/assets/7f/b7/8a370779099556852dbdd821dff0/food_farm-to-table_v4.png)|Correctly in S3|
|food-safety-nutrition-and-distribution|Figure-7.2|climate-change-and-health-salmonella|[Current Location](https://data.globalchange.gov/assets/02/45/02be885e30cf0e64dd0f8738c3ce/food_salmonella-pathways_v6.png)||
|food-safety-nutrition-and-distribution|Figure-7.3|seasonality-of-human-illnesses-associated-with-foodborne-pathogens|[Current Location](https://data.globalchange.gov/assets/23/1a/bba9e785e6004e3dcfbcc7deb0a6/food_seasonality-foodborne-illness_v5.png)||
|food-safety-nutrition-and-distribution|Figure-7.4|effects-of-carbon-dioxide-on-protein-and-minerals|[Current Location](https://data.globalchange.gov/assets/2b/a6/e0fb7b2148d3968323caa49277d5/food_carbon-dioxide-on-protein-minerals_v2_1.png)||
|food-safety-nutrition-and-distribution|Figure-7.5|mississippi-river-level-at-st-louis-missouri|[Current Location](https://data.globalchange.gov/assets/7a/4b/48c1f8772041a8acfb2081667aa9/food_mississippi-river-level_v3_0.png)||
|food-safety-nutrition-and-distribution|**Figure-7.1**|low-water-conditions-on-mississippi-river|[Current Location](https://data.globalchange.gov/assets/c5/93/d9460d447710118a795f39256b6b/mississippiriverlowflowdec52012_usace_stlouisdistrict.jpg)|Missing; Repeat ordinal 7.1 in GCIS?|
|food-safety-nutrition-and-distribution|**Figure-7.1**|mycotoxin-in-corn|[Current Location](https://data.globalchange.gov/assets/6d/b1/ab9ffa0690387bc39ab07ce76618/weaver_bcpru_web_image_3.jpg)|Missing; Repeat ordinal 7.1 in GCIS?|
|mental-health-and-well-being|Figure-8.1|climate-change-and-mental-health|[Current Location](https://data.globalchange.gov/assets/e2/2f/eeac5b4bdbbd4136d80a0ae40098/mental_pathways_v8_0.png)||
|mental-health-and-well-being|Figure-8.2|the-impact-of-climate-change-on-physical-mental-and-community-health|[Current Location](https://data.globalchange.gov/assets/2f/40/69f3bde000230132c378c869386a/mental_climate-impacts-and-health_v8.png)||
|populations-of-concern|Figure-9.1|determinants-of-vulnerability|[Current Location](https://data.globalchange.gov/assets/a8/d2/31c91eae80cfa6b998bc9a9c2f5a/poc_determinants-vulnerability_v5.png)||
|populations-of-concern|Figure-9.2|intersection-of-social-determinants-of-health-and-vulnerability|[Current Location](https://data.globalchange.gov/assets/18/27/67f139f06974baa86889e5651ad2/poc_social-determinants-vulnerability_v5.png)||
|populations-of-concern|Figure-9.3|vulnerability-to-the-health-impacts-of-climate-change-at-different-lifestages|[Current Location](https://data.globalchange.gov/assets/21/e1/476fcaaad0314db9fe0b47a1b3f4/poc_children-vulnerabilities_v5.png)||
|populations-of-concern|Figure-9.4|mapping-social-vulnerability|[Current Location](https://data.globalchange.gov/assets/bb/83/ca736ea4a283054c284b332ea6af/poc_mapping-social-vulnerability_v1.png)||
|populations-of-concern|Figure-9.5|mapping-communities-vulnerable-to-heat-in-georgia|[Current Location](https://data.globalchange.gov/assets/e0/d9/6554e9218408f23af87eaa420ddf/poc_mappingvulnerablecommunities.png)||
|appendix-1--technical-support-document|Figure-A1.1|scenarios-of-future-temperature-rise|[Current Location](https://data.globalchange.gov/assets/c8/e9/03e3a4338128bd531e2212036a43/tsd_average-annual-temp_global_v4.png)||
|appendix-1--technical-support-document|Figure-A1.2|example-increasing-spatial-resolution-of-climate-models|[Current Location](https://data.globalchange.gov/assets/1e/5a/761481b5ec6c691f68a756247e42/Figure-A1.2.png)||
|appendix-1--technical-support-document|Figure-A1.3|sensitivity-analysis-of-differences-in-modeling-approaches|[Current Location](https://data.globalchange.gov/assets/98/e2/638c51efc07dfa4c80c2577828ab/tsd_temp-diff-cmip5-rcp60_v1.png)||
|appendix-1--technical-support-document|Figure-A1.4|tsd-sources-of-uncertainty|[Current Location](https://data.globalchange.gov/assets/ff/67/d80340cbdf9c7ac3738e3810101e/tsd_sources-of-uncertainty_v3.png)||

**Comment by lomky** [comment]
SQL to adjust the file locations has been generated. Just waiting to here from Andrew on the status of the 4 missing Figures. I will then run the SQL on dev to confirm everything changes over correctly before coordinating with @amruelama to make changes on Stage.

**Comment by lomky** [comment]
Discovered some new content #444 and a bug fixes #445.

Waiting for the last two figures to be put into the S3

**Comment by lomky** [comment]
Last images are in the S3. I'm planning on running a test update on dev tomorrow and the real one on stage directly after, if successful.

**Comment by lomky** [comment]
File locations successfully updated in stage, reported in [the watch tab](https://data-stage.globalchange.gov/watch?view=details). 

It looks like I come through as unknown, either because I was in the DB directly, or under the ops user? Either way, going to file a ticket to address that so it reports the SQL user who made the changes rather than unknown.

@amruelama will spot check the changes. This will be in production after the next content push.

**Comment by lomky** [comment]
Useful SQL query used to find all images and figures associated with a report, and their file info:

```
select
    NULL as fig_id,
    image.identifier as img_id,
    figure.chapter_identifier as chptr_id,
    figure.report_identifier as rpt_id,
    file.identifier as file_id,
    file.file as file_uri,
    file.location as file_loc
from figure 
join image_figure_map as if_map
    on figure.identifier = if_map.figure_identifier
join image 
    on if_map.image_identifier = image.identifier
join publication as pub
    on image.identifier = pub.fk -> 'identifier'
join publication_file_map as pf_map
    on pub.id = pf_map.publication_id
join file
    on pf_map.file_identifier = file.identifier
where 
    figure.report_identifier = 'usgcrp-climate-human-health-assessment-2016'
GROUP BY fig_id, img_id, chptr_id, rpt_id, file_id
UNION
select
    figure.identifier as fig_id,
    NULL as img_id,
    figure.chapter_identifier as chptr_id,
    figure.report_identifier as rpt_id,
    file.identifier as file_id,
    file.file as file_uri,
    file.location as file_loc
from figure 
join publication as pub
    on figure.identifier = pub.fk -> 'identifier'
join publication_file_map as pf_map
    on pub.id = pf_map.publication_id
join file
    on pf_map.file_identifier = file.identifier
where 
    figure.report_identifier = 'usgcrp-climate-human-health-assessment-2016'
GROUP BY fig_id, img_id, chptr_id, rpt_id, file_id
ORDER BY chptr_id ASC, img_id DESC, fig_id DESC;
```

**Comment by amruelama** [comment]
Content push is done and you should be able to see these changes on prod @lomky

**Comment by lomky** [comment]
@amruelama @bakamine I spot checked a dozen of them files across the chapters, both figure and image linked, and everything looks good to me!

Closing as complete! Hurray!
