### ISSUE TITLE
Non nca3 references list

### ISSUE THREAD

**Issue by amruelama** [USGCRP/gcis#380]
The link to references - https://data.globalchange.gov/reference redirects to nca3 references - https://data.globalchange.gov/report/nca3/reference.
@rewolfe @justgo129 How important is to have either a 'reference' option in sidebar under 'publications' or a URL to a page that lists all the references (not just restricted to nca3)?

**Comment by rewolfe** [comment]
@amruelama - Thanks for writing this up.  I noticed this also.  Yes, we want /reference to show all of the references not just those associated with the nca3 report.

**Comment by lomky** [comment]
Apparently the system is currently set to redirect /reference to whatever the "current report" is, currently nca3. As best I can tell, this is not a documented behavior of the API, so I have no problem with removing that reroute.

**Comment by lomky** [comment]
Code changes complete. Going to hold on releasing this until post-migration, as @amruelama and I found a way to solve her immediate need on data-review.

**Comment by lomky** [comment]
Merged into master_ICF (the current master branch for post-ICF migration).
