### ISSUE TITLE
Update names and hierarchical structure of organizations

### ISSUE THREAD

**Issue by lomky** [USGCRP/gcis#386]
Since much of the org content was populated in GCIS, many of the orgs have been restructured and renamed. Additionally, most of the org structures in GCIS have been completed at inconsistent hierarchical levels. 

A prominent example of a restructuring is the [National Oceanic and Atmospheric Administration National Centers for Environmental Information.](https://data.globalchange.gov/organization/national-oceanic-atmospheric-administration-national-centers-environmental-information) The newly formed NCEI merges the National Oceanographic Data Center (NODC), the National Climatic Data Center (NCDC), and the National Geophysical Data Center (NGDC). Because content in GCIS is affiliated with these predecessors of the NCEI, it is important that we keep the correct org name that is affiliated with an activity (i.e., publication) when the activity occurred. 

We also need to systematically update how we refer to org names in GCIS. For an example, there are inconsistencies in how we refer to programs, divisions, offices, etc... of the [NOAA](https://data.globalchange.gov/organization/national-oceanic-atmospheric-administration) where have abbreviated, spelled out, and omitted 'NOAA' from these names in GCIS. Refer to the ORG Conventions section in our [wiki](https://github.com/USGCRP/gcis-internal/wiki/Conventions#org-conventions). Additionally, we need to determine whether the programs, divisions, offices, etc... accurately describe the hierarchical structure of organizations. 

To track our progress it would probably be best to record completed orgs in a shared Google spreadsheet.

**Comment by justgo129** [comment]
Duplicates
https://github.com/USGCRP/gcis/issues/310 .  

To date, we have not invoked a time component in GCIS other than through "predecessor of."  So, three organizations can be related to one even if two of those are no longer affiliated.  I know that Brent devised a scheme for working with NOAA/NCEI, recognizing just this issue.
