### ISSUE TITLE
Ability to Determine File Type for External Assets

### ISSUE THREAD

**Issue by lomky** [USGCRP/gcis#388]
Need to identify file types without extensions for external assets like downloadable reports.

**Comment by lomky** [comment]
@justgo129 why do we care why the file types are?

**Comment by justgo129** [comment]
no clue, that wasn't my decision

**Comment by rewolfe** [comment]
Kat, I don’t believe it is still necessary to store the file type in GCIS.  I expect that any new document will be a PDF and most of the old ones are PDF.  However, this is may have been in the context of generating the thumbnail image of the document.  I’m pretty sure that if a standard extension is not provided, a thumbnail can’t be generated.

**Comment by lomky** [comment]
@justgo129 @rewolfe Thank you very much. I'll investigate the thumbnail context and either update or close based on what I find.

**Comment by zacharylandes** [comment]
Closing due to age and irrelevance
