### ISSUE TITLE
Update of Dev Environment Packages & Modules

### ISSUE THREAD

**Issue by lomky** [USGCRP/gcis#392]
Our dev environment package versions are falling out of date. Update them.

Original description:

> Harmonization of software / IT versions. The following error message appears when pushing code from dev to stage, although the push still is successful. “versions of some packages differ, see above. Please resolve this and try again. Checking /opt/perl5/common”.
> 
> We also discussed the version of mojolicious during our weekly call.
> 
> This also includes updating Virtuoso.

**Comment by zacharylandes** [comment]
Closing due to age and irrelevance
