### ISSUE TITLE
Discover which Data.gov Topics Add Value to GCIS

### ISSUE THREAD

**Issue by lomky** [USGCRP/gcis#400]

**Comment by lomky** [comment]
We should look at what is in Data.gov and referenced in the NCA but not yet pulled into GCIS. 

@rewolfe is that a correct intepretation of what we discussed at the TagUp today?

**Comment by rewolfe** [comment]
+1

**Comment by lomky** [comment]
Created #404 for the NCA <-> Data.gov assets
