### ISSUE TITLE
Create Metric of GCIS Counts for Year One and Year Two

### ISSUE THREAD

**Issue by lomky** [USGCRP/gcis#405]

**Comment by lomky** [comment]
Would like this by end of month.

**Comment by lomky** [comment]
I grabbed a copy of the audit table & instructions for accessing via psql for @amruelama

**Comment by amruelama** [comment]
Generated values from the audit table for year one and two with available data. Need to find good and accurate measurable for [GCIS Evaluation](https://github.com/USGCRP/gcis/issues/407) and brainstorm [performance metrics.](https://github.com/USGCRP/gcis/issues/406) based on audit table data fields.
