### ISSUE TITLE
GCIS Metrics

### ISSUE THREAD

**Issue by lomky** [USGCRP/gcis#407]
Finding good measurables to judge GCIS

**Comment by amruelama** [comment]
List of measurable Quantitative Indicators (current) 

1. Number of articles added to the system 
  - in the 1st year
  - in the 2nd year

2. Number of figures added to the system
  -   in the 1st year
  -   in the 2nd year

3. Number of datasets added to the system
 - in the 1st year
 - in the 2nd year

4. Number of persons added in the system 
 - in the 1st year
 - in the 2nd year

5. Number of figures with provenance

 - with traceable data sources 
 - with traceable processes
 - with traceable references  (at least one each figure)
