### ISSUE TITLE
Update Search.pm with needed CDI Changes

### ISSUE THREAD

**Issue by lomky** [USGCRP/gcis#410]
This ticket covers the remaining changes needed for Search.pm to suport hte CDI effort.
- [x] Return the search counts
- [x] Tests are passing or updated
- [ ] Add paging interface to html page for search
- [ ] Optional: Fix existing incorrect messaging on edge case of exactly the $per_page results.
  - if we don't do this, file a follow up issue.

@rsindlin I think this covered everything, but feel free to add on.

**Comment by lomky** [comment]
This is follow up to Search.pm changes made in pull request #352

**Comment by rsindlin** [comment]
"Return the search counts" addressed in PR #414

**Comment by rsindlin** [comment]
Status update:
- Tests need additional work
- HTML paging interface work started

**Comment by lomky** [comment]
@rsindlin could you please let me know the status of this ticket when you get back?

**Comment by lomky** [comment]
@rsindlin could you please comment the state this is in, now that your contract is ended?

Thanks!

**Comment by rsindlin** [comment]
Paging interface is in Gist: https://gist.github.com/rsindlin/83b2079e7785aa70feb537f2cca9aee8

**Comment by zacharylandes** [comment]
Closing due to age and irrelevance
