### ISSUE TITLE
Chapters returned inside of Report should be properly sorted

### ISSUE THREAD

**Issue by lomky** [USGCRP/gcis#412]
See [BaseCamp Discussion](https://basecamp.com/2837444/projects/12249839/todos/262006055)

**Comment by lomky** [comment]
Sadly, the simple fix I tried did not work.

I tried:
 - adding a sorter to the Report controller's show function
 - adjusting the Chapter object to sort on sort_key

Shifting this to medium priority since my quick fix didn't work and the desc/title is higher priority.

**Comment by zacharylandes** [comment]
Closing due to age and irrelevance
