### ISSUE TITLE
Journal Pages should tag their articles with which of our reports has referenced them

### ISSUE THREAD

**Issue by justgo129** [USGCRP/gcis#413]
Per a request from Adam et al., could we provide some functionality that differentiates NCA3 content from that of the HA within GCIS?

e.g.: http://data.globalchange.gov/journal/climatic-change lists articles from both the NCA3 and HA (as well as from a union of both).  It would be great if we could see only the articles from the NCA3 for instance without needing to write a SPARQL query.

**Comment by lomky** [comment]
The path forward for this, in my mind, is to update the display of the Journal pages to have an footnote marker (*, †, etc). Does this distinction need to be made for any format other than web/html?
