### ISSUE TITLE
Rework Contributor JSON tree (count_only=1 does not work)

### ISSUE THREAD

**Issue by rsindlin** [USGCRP/gcis#417]
Because lib/Tuba/DB/Mixin/Object/Contributor.pm method `as_tree` does not call `SUPER::as_tree` in most cases, it does not work with recent enhancements of providing the JSON tag "type" for search results, nor provide a "results_count" tag when `/search` is invoked with the get parameter `count_only=1`

Leaving this as a low priority, unless [MindGrub](https://basecamp.com/2837444/projects/12249839/todos/260420840#comment_442480467) needs it fixed.

**Comment by zacharylandes** [comment]
Closing due to age and irrelevance
