### ISSUE TITLE
Improve code traceability with more logging

### ISSUE THREAD

**Issue by lomky** [USGCRP/gcis#423]
In many cases when our system is hit with API calls, we start off good with the controller logging out the initial code paths we hit, but then we go silent. It would enhance both future development and the debugging of issues if we had more of a log trail. It also doubles as documentation of intent of the code, in many cases.

My first thoughts on log levels:

Verbose, function-by-function - probably at a debug level
Higher level 'intentional' logs - probably at info
Things going wrong in a known way - warn
Things failing critically and requiring changes - errors

**Comment by rewolfe** [comment]
Sounds good. Check into Mojo's logging levels.
