### ISSUE TITLE
Private fields exposed in JSON of Figure items

### ISSUE THREAD

**Issue by rsindlin** [USGCRP/gcis#424]
In Search results for Figures, the JSON includes a "report" tag that shows all fields of the Report table, including the private fields (ie, beginning with "_").  Example URL: http://data.globalchange.gov/search.json?q=climate&type=figure&format=detailed, see _public field.

I suspect that in lib/Tuba/DB/Mixin/Object/Figure/Manager.pm in the dbgrep method that the "with_objects" passed to get_objects is getting a report (and a chapter) object that is blessed only as a **Rose**::DB::Object, and _not_ as a **Tuba**::DB::Object, therefore circumventing the Tuba::DB::Object::as_tree method that prunes out private fields.

There may be a similar issue in the Tuba::Figure controller in the else clause of the list method, but that is unconfirmed.

**Comment by zacharylandes** [comment]
Closing due to age and irrelevance
