### ISSUE TITLE
Add new CDI Tags to Datasets

### ISSUE THREAD

**Issue by lomky** [USGCRP/gcis#439]
Followup to #374 to add the CDI tags to the datasets. Dependent on the vocabulary code (and CDI content) delivery from the CDI/GCIS team.

**Comment by amruelama** [comment]
Any update on this ticket @lomky? Can you please add the link to the vocabulary code if it's been delivered already?

**Comment by lomky** [comment]
I am working this week on documenting the API path forward (mostly the deprecations), so that I can merge the CDI branch next week. Once it is merged in and pushed to Stage (tentatively, Nov 1) you can begin adding this content.

You can see all the pending code [here](https://github.com/USGCRP/gcis/tree/cdi) and the actual vocabulary code [routes here](https://github.com/USGCRP/gcis/blob/cdi/lib/Tuba.pm#L481) and [library here](https://github.com/USGCRP/gcis/blob/cdi/lib/Tuba/Vocabulary.pm)

**Comment by amruelama** [comment]
@lomky Thank you!
