### ISSUE TITLE
Create a Report-Specfic GCIS Instance for CIRA

### ISSUE THREAD

**Issue by lomky** [USGCRP/gcis#442]
We are considering standing up a report-specific GCIS instance for the new [CIRA](https://www.epa.gov/cira) report. 

This would serve during the development of the report, with the eventual goal of merging into the production GCIS instance before standing down the report-specific one.

This would also involve the metadata ingestion system built by TSU, so this ticket is dependent on that being something we can package up with GCIS.

**Comment by lomky** [comment]
@bakamine is this backburnered for the moment?

**Comment by amruelama** [comment]
EPA wants to use TSU's metadata tool. This issue can be closed because TSU is taking care of this task.
