### ISSUE TITLE
Allow alphabetical Chapter Number

### ISSUE THREAD

**Issue by amruelama** [USGCRP/gcis#447]
Right now, chapter Numbers are restricted to numeric type. But we also need alphabetical type. [Climate Change Global Food Security and the U.S. Food System](http://www.usda.gov/oce/climate_change/FoodSecurity2015Assessment/FullAssessment.pdf) has Executive Summary with [7 figures](https://data.globalchange.gov/report/usda-climate-change-global-food-security-us-food-system-2015/chapter/introduction-report-background/figure), which is currently added under [Chapter 1](https://data.globalchange.gov/report/usda-climate-change-global-food-security-us-food-system-2015/chapter/introduction-report-background), but this needs to migrated to 'Executive Summary' instead.   
Hence, the figure names would be ES-1, ES-2 etc., @lomky Let me know what you think.  
Note: There are no figures in Chapter 1. See Figures and Tables. Page VII [here](http://www.usda.gov/oce/climate_change/FoodSecurity2015Assessment/FullAssessment.pdf).

**Comment by lomky** [comment]
I've pinged Andrew at TSU to confirm letters appearing in the chapter number field won't break anything.

**Comment by lomky** [comment]
TSU is okay with this change, and doesn't expect it to cause any issues for them.

**Comment by amruelama** [comment]
I am working on adding required contents to list of chapters for this report (on stage). Then I can easily migrate the figures that are currently under Chapter 1 to Executive Summary.

Example - List of Chapters in Health Assessment - https://data.globalchange.gov/report/usgcrp-climate-human-health-assessment-2016/chapter

The figures under 'Executive Summary' is listed as Figure 1, Figure 2, Figure 3 etc., - see https://data.globalchange.gov/report/usgcrp-climate-human-health-assessment-2016/chapter/executive-summary/figure
