### ISSUE TITLE
Scripted Content Changes should credit the DB User, etc

### ISSUE THREAD

**Issue by lomky** [USGCRP/gcis#449]
When we make changes through scripts or directly in the DB, our audit log states the changes are made by "Unknown". I want to create a fall-back system where it will instead seek out other ways to ID a person or method. I.e. the DB user "psql user ktipton" or at least the context "direct SQL update" or "script"

This problem was highlighted during this change: #379

**Comment by zacharylandes** [comment]
To access the RDS db, all usernames must be the same- which is 'dbadmin'. This means there is no way to track the actual user editing the db. the only way make this more readable is to change the unknown or undefined username to a default name, in this case I changed it to 'zlandes@usgcrp.gov',
but could be changed to anything. 

On dev I updated empty users to be called zlandes@usgrcp.gov - verify here

https://data-dev.globalchange.gov/watch

@amruelama 
let me know if you'd like to change or update this. Thanks.

**Comment by amruelama** [comment]
@zacharylandes Updating unknown to your email sounds good. Is there are way to differentiate script based changes vs manual changes? (bulk vs manual update)

Also, please see this filter - https://data-dev.globalchange.gov/watch?model=&user=unknown&actions=&date=15-years&view=details

**Comment by amruelama** [comment]
Right now, sql update is tagged as 'admin' - but this is currently manual. Please make 'admin' default for any background script update for audit purposes.

**Comment by zacharylandes** [comment]
@amruelama this can be closed, admin is now the default for any background process
