### ISSUE TITLE
Track down reports and assessment with Non-Numeric Chapters and fix their ID

### ISSUE THREAD

**Issue by amruelama** [USGCRP/gcis#450]
Currently GCIS doesn't have the capability of adding alphabetical IDs to figures. Once @lomky add this capability #447 , we will have to track down various executive summaries of reports/assessments and replace the Ids with alphabetical IDS, say, ES for Executive Summary, A for Appendix etc.,  

For example, if its figure 1 of Executive Summary, it should display as ' ES.1', and 'A.1' for figure 1 in appendix and so on.

**Comment by lomky** [comment]
@amruelama I think we want to specify the appendix number, i.e. "Appendix 1" would be "A1", and thus it's figure will show as "A1.1". Appendix 2, "A2". Appendix 7, "A7".

Do you agree?

**Comment by amruelama** [comment]
Yes, that makes sense @lomky. But for Executive Summary, it would be ES.1, ES.2., correct? - because we are using "ES" to replace '1' for Chapter 1.

**Comment by lomky** [comment]
@amruelama correct. The schema is such:

[ChapterNumber].[FigureOrdinal]

Today that is restricted to the types {Numeric}.{Numeric}. #447 will extend the ChapterNumber to be AlphaNumeric, allowing {AlphaNumeric}.{Numeric}. By convention, we want to maintain the ChapterNumber to be very short, 1-2 characters. Maybe 3 if needed for uniqueness within a report.

So, as an example from the [2016 Health Report](https://data.globalchange.gov/report/usgcrp-climate-human-health-assessment-2016/chapter), the chapter 'numbers' _will become_:

```
FM, ES,
1, 2, 3, 4, 5, 6, 7, 8, 9, 
A1, A2, A3, A4
```

So a few example Figures will show on GCIS as:

```
FM.1,
ES.1, ES.2, ...,
1.1, 1.2, ..., 
3.1, ...,
...,
9.1, ...,
A1.1, A1.2, A1.3, A1.4
```

Not that the internally stored figure ordinals will not be changed by this chapter number extension. Only the display name as shown on GCIS will update to display their chapter 'number' as a prefix.

**Comment by lomky** [comment]
Here is a query to find the Chapters missing their number:

```
select identifier as chapter_identifier, title as chapter_title, report_identifier from chapter where number IS NULL;
```

I see 39 chapters total.

**Comment by amruelama** [comment]
Closing this ticket because we have decided not to add non-number chapters.
