### ISSUE TITLE
Track Down Figures without an Ordinal and Populate It

### ISSUE THREAD

**Issue by lomky** [USGCRP/gcis#452]
There is no reason a Figure in a report should not have an ordinal. We should track down any Figures, Tables, or Findings missing their ordinal and populate it.

We can find these with this query:

### Figures (227 total, 15 chapter-based)
```
select report_identifier, chapter_identifier, identifier as figure_identifier, title, ordinal from figure where ordinal IS NULL;
```

### Findings (0)
```
select report_identifier, chapter_identifier, identifier as finding_identifier, statement, ordinal from finding where ordinal IS NULL;
```

### Tables (14)
```
select report_identifier, chapter_identifier, identifier as table_identifier, title, ordinal from gcis_metadata.table where ordinal IS NULL;
```

We would populate them with the next ordinal in that Report's Chapter. In the case of no Chapter, it would be the next in the entire Report.

For the 227 Figures, I would concentrate on our own assessments first (the 15 chapter-based). After those are handled let's see if I can create a quick script to populate the rest from scratch.

**Comment by lomky** [comment]
This is **not blocked** by #445 so it can be started whenever needed.

**Comment by amruelama** [comment]
Added the listed of 227 figures with missing ordinals in [Content Issue Tracker](https://docs.google.com/spreadsheets/d/1tr68prMQSffCy4HjIg-szmpyNw0J1YtzJf3CSfDbdZg/edit#gid=760120770). Use the 'report identifier' to prioritize the reports.

**Comment by amruelama** [comment]
@lomky Can we make the 'ordinal' mandatory field?

**Comment by amruelama** [comment]
Also, for the figures with no figure numbers in a chapter, we have decided to add ordinals as consecutive numbers. Example - for chapter 1 with no figure numbers, the order would be 1,2,3 and so on, such that the figure numbers should display as Figure 1.1, 1.2, 1.3 and so on.

**Comment by lomky** [comment]
@amruelama I have no issue with making Ordinal a required field. I cannot do that until we complete adding them to the existing data.

**Comment by lomky** [comment]
Figure ordinal should follow this convention (by my understanding)

Reports with Chapters:
> Starting at 1 and incrementing for each entry in a chapter.  Resetting to 1 for each new chapter. Should roughly follow the order of appearance in the chapter, where possible.

Reports without Chapters:
> Starting at 1 and incrementing. Should roughly follow the order of appearance in the report, if possible.

--
As far as how the figures are displayed:
 
In our HTML front end, we currently show ChapterNumber.FigureOrdinal, with a '-' in place of either of those values, if null.

I will be changing this shortly to also always include a report identifier as a part of #317, as the report ID is required to uniquely distinguish the figure on a glance.

--
In the API, the only number belonging to the Figure itself is the Ordinal. If you query a figure you will not expect to get anything back about the chapter number. Report Identifier and Chapter Identifier will come back, though.

```
curl -X GET --header "Accept: application/json" "https://data.globalchange.gov/report/usda-climate-change-global-food-security-us-food-system-2015/figure/food-system-activities-feedbacks"
```
```
{
  "kindred_figures": [],
  "references": [],
  "contributors": [],
  "source_citation": null,
  "uri": "/report/usda-climate-change-global-food-security-us-food-system-2015/chapter/introduction-report-background/figure/food-system-activities-feedbacks",
  "usage_limits": null,
  "ordinal": 1,
  "lat_max": null,
  "identifier": "food-system-activities-feedbacks",
  "lon_max": null,
  "files": [
    {
      "identifier": "cc071c30-ea9c-4d42-885c-15533e1656c2",
      "landing_page": null,
      "sha1": "500696b2ba655f56f436314edb292beb627e1234",
      "url": "/assets/e1/d9/618e44d8399950cc53cce8d4bc4a/1.1.png",
      "thumbnail": "e1/d9/618e44d8399950cc53cce8d4bc4a/.thumb-cc071c30-ea9c-4d42-885c-15533e1656c2.png",
      "href": "https://data.globalchange.gov/assets/e1/d9/618e44d8399950cc53cce8d4bc4a/1.1.png",
      "thumbnail_href": "https://data.globalchange.gov/assets/e1/d9/618e44d8399950cc53cce8d4bc4a/.thumb-cc071c30-ea9c-4d42-885c-15533e1656c2.png",
      "size": 122822,
      "location": null,
      "uri": "/file/cc071c30-ea9c-4d42-885c-15533e1656c2",
      "file": "e1/d9/618e44d8399950cc53cce8d4bc4a/1.1.png",
      "mime_type": "image/png"
    }
  ],
  "submission_dt": null,
  "href": "https://data.globalchange.gov/report/usda-climate-change-global-food-security-us-food-system-2015/chapter/introduction-report-background/figure/food-system-activities-feedbacks.json",
  "time_end": null,
  "parents": [],
  "chapter": {
    "number": "1",
    "report_identifier": "usda-climate-change-global-food-security-us-food-system-2015",
    "title": "Introduction and Report Background",
    "doi": null,
    "identifier": "introduction-report-background",
    "url": null,
    "sort_key": 10
  },
  "report_identifier": "usda-climate-change-global-food-security-us-food-system-2015",
  "caption": "Food-system activities include the production of raw food materials, transforming the raw material into retail products, marketing those products to buyers and product consumption. Food transportation, storage and waste disposal play a role in each of these activities. ",
  "title": "Food system activities and feedbacks",
  "create_dt": null,
  "lon_min": null,
  "time_start": null,
  "lat_min": null,
  "attributes": null,
  "cited_by": [],
  "chapter_identifier": "introduction-report-background",
  "url": null
}
```

**Comment by amruelama** [comment]
All the blank ordinals are now populated with consecutive numbers.
