### ISSUE TITLE
Fix 'model' lexicons and redirect to right page

### ISSUE THREAD

**Issue by amruelama** [USGCRP/gcis#460]
All the 'model' lexicons show 404 error. Is there a way to fix these lexicons to redirect them to correct URLs @lomky?

Examples:
1. https://data.globalchange.gov/model/cnrm-cm3
2. https://data.globalchange.gov/model/echam5_mpi-om

Looks like the following lexicons are broken
1. https://data.globalchange.gov/lexicon/esg
2. https://data.globalchange.gov/lexicon/cmip3

**Comment by amruelama** [comment]
@rasherman Let me know if you have any suggestion on where to find these lexicons ([esg](https://data.globalchange.gov/lexicon/esg), [cmip3](https://data.globalchange.gov/lexicon/cmip3)) since the current link is broken

**Comment by rewolfe** [comment]
Amrutha, I believe that they may have changed the API for getting model metadata.

The links are something like this: https://esg.llnl.gov:8443/metadata/advancedDatasetSearch.do?d_scenario=any&d_frequency=any&d_offset=0&d_model=cccma_cgcm3_1

On this page

https://pcmdi.llnl.gov/projects/esgf-llnl/

I found this link to the “new” api:

https://github.com/ESGF/esgf.github.io/wiki/ESGF_Search_REST_API

I’ve tried some of their examples and they time out.  You may have to contact them (https://www.earthsystemcog.org/projects/cog/contactus/) directly to see if they can help.

**Comment by amruelama** [comment]
@rewolfe Thank you! This is very helpful. I'll contact them directly.

**Comment by amruelama** [comment]
Looks like lexicon 'cmip3' doesn't have hyperlink, but 'esg' does. 
**Example** - https://data.globalchange.gov/model/cgcm31_t47 - You can notice that cmip3 has hyperlink to URL that doesn't work anymore. Can we remove all the hyperlinks for lexicon- esg? @lomky https://data.globalchange.gov/lexicon/esg

**Comment by lomky** [comment]
@amruelama yes, but the lexicon doesn't do much for us if we can't trace it to somewhere. Has the lexicon been pulled offline completely?
