### ISSUE TITLE
Springer locations QA

### ISSUE THREAD

**Issue by amruelama** [USGCRP/gcis#461]
[This](https://data.globalchange.gov/search?q=SPRINGER&type=organization&format=detailed) is the list of 'Springer' branches/location. 

The following QA needs to be done
- [x] Make sure all the publications listed are actually related to the right springer location in our database
- [x] Make sure the organization name and identifier is identical to the name in the website.
- [x] Make sure the URLs are listed - point it to the contact page of that location in their website 
- [x] Add countries
- [x] Relate it to the main springer page - https://data.globalchange.gov/organization/springer
- [x] Delete / replace duplicates

**Comment by Zullmira** [comment]
There are totally 7 Springer items on the website after the QA. And all the books were attributed to the correct Springer items.

**Comment by amruelama** [comment]
After QA, there are currently 4 Springer organizations in our database - Germany (HQ), Netherlands, U.S. and Vienna. All the duplicates were merged into the appropriate organization.
