### ISSUE TITLE
Create Distinct Onilne ISBN, Print ISBN, and DOI fields on Books

### ISSUE THREAD

**Issue by lomky** [USGCRP/gcis#465]
Books can have distinct ISBN for online vs print and can also have a completely different DOI. We should support those different identifiers to help avoid duplication in our system when the same book is referenced by various identifiers.
- [x] Implement the three fields
- [x] Move all existing 'ISBN' fields to one of the new fields
- [x] Delete previous 'ISBN' field
- [x] Deprecate the API field 'ISBN'
  - Establish fall through for what appears in the field for the moment (print -> online -> blank?)
- [x] File a QA ticket to correctly assign the relocated existing ISBN field values into their proper online vs print location (probably manually)
- [x] File a QA ticket to populate the DOI & blank ISBNs (probably via an automated script)

**Comment by lomky** [comment]
Supersedes #293.

**Comment by lomky** [comment]
Examples of Books with distinct DOI, ISBN Print and ISBN Online: [1](https://data.globalchange.gov/book/dacf775c-b83f-4e40-bffe-5db7b659ee1c) [2](https://data.globalchange.gov/book/df012039-4e97-4aeb-87db-6b6d380dd9bf) [3](https://data.globalchange.gov/book/ec8b859e-abe4-49bf-b82f-a693527c8cda). 

[SPARQL Results of DOI Books](https://data.globalchange.gov/sparql?default-graph-uri=&query=select+distinct+*+FROM+%3Chttps%3A%2F%2Fdata.globalchange.gov%3E+where+%7B+%0D%0A++%3Fs+a+gcis%3ABook+.%0D%0A+++%3Fs+gcis%3AhasURL+%3Faurl%0D%0A+++filter+regex+%28%3Faurl%2C+%22%5Ehttp%3A%2F%2Fdx.doi.org%22%2C%22i%22%29%0D%0A%7D+&should-sponge=&format=text%2Fhtml&timeout=0&debug=on)

**Comment by amruelama** [comment]
- [ ] Add new fields:

              1. Online ISBN
              2. Print ISBN
              3. DOI

- [ ] Move existing ISBNs to relevant field
- [ ] QA and populate remaining fields
- [ ] Remove ISBN field

**Comment by amruelama** [comment]
[Worksheet](https://docs.google.com/spreadsheets/d/1MPxHvg11KdWuRA1-X0uK2DIyUKhB_Mxc9yjGrTHAmjk/edit#gid=0)
