### ISSUE TITLE
Create an API Specification for GCIS

### ISSUE THREAD

**Issue by lomky** [USGCRP/gcis#467]
In the past our API Specification has been completely auto-generated. While this has served well for the first stage of Tuba & GCIS, it creates trouble when we want to move to a more stable API versioning with deprecations, paths forward, etc.

Starting from the [existing API output](https://data.globalchange.gov/api/)
- [ ] Document the public facing routes (mostly done already by Swagger)
- [ ] Document any 'secret' public routes (possible to convince Swagger to output?)
- [ ] Document the actual objects being returned (not done)
  - might be inconsistent in list vs direct query?

This effectively blocks #443, #465, #434, #381 and any other task that relies on a stable, documented API

**Comment by lomky** [comment]
Current Progress viewable [here](https://docs.google.com/a/usgcrp.gov/spreadsheets/d/1UfZeyu0_1mcdVexd3HnrufZ-XUdddD9oxeRPf0mARfU/edit?usp=sharing)

Major issues encountered:
 - Contributor gives back different responses depending on whether a person is associated with it or not.
 - Lexicon appears to be able to give back every other API structure in the system, ish

**Comment by zacharylandes** [comment]
Closing due to age and irrelevance
