### ISSUE TITLE
Replace 'international' with the relevant org type

### ISSUE THREAD

**Issue by amruelama** [USGCRP/gcis#468]
Currently 'international' is a type of organization. Now that we have added international flag feature ( #448 ), there is no reason to have this type listed as an option under 'Organization type' drop down list. To replace this type with the relevant org type :
- [x] Generate a list of organizations that are currently listed as Organization type = 'International' ( @amruelama )
- [x] Perform QA to replace all these organizations' type with relevant organization type ( @Zullmira )
- [x] Delete 'international' as a type under 'Organization type' drop down list ( @lomky )

**Comment by amruelama** [comment]
Currently there are **61 organizations** that are '**international**' type and 172 are NULL. 

List of organization types in the drop down list (current):

1.  academic/federal (cooperative agreement)
2.  regional
3.  municipal
4.  federally funded research and development center
5.  independent_scholar
6.  consortium
7.  research
8.  professional society/organization
9.  commercial
10.  ngo
11.  territory
12.  tribal
13.  foundation
14.  academic/research
15.  academic-federal (managed private)
16.  state
17.  private
18.  intergovernmental
19.  academic
20.  federal corporation
21.  county
22.  federal (managed academic)
23.  federal
24.  international
25.  state/housed w/in academic
26.  federal (managed private)
27.  academic/operated by fed. government
28.  national
29.  city
30.  non-profit

Types based on geographical regions:

1. Regional - 54
2. Municipal  - 2
3. State - 203
4. International - 61
5. National - 222
6. City - 47
7. County - 19



We should also think about the usage of 'independent scholar' as an organization.

**Comment by lomky** [comment]
Tech work ready to go. Please move this to "Next Release" once the content changes are done.

**Comment by amruelama** [comment]
Content QA is not done yet @lomky

**Comment by lomky** [comment]
We discussed this offline, but to sum up:

 - the 61 `international` type orgs are recorded for change at a later date
 - stage has been updated to reassign those to type blank (empty string)
 - @amruelama will do a content push tomorrow
 - @lomky will do the code push either Wed PM or Thursday

**Comment by amruelama** [comment]
@Zullmira and I will research to update the 61 organizations' organization type and populate them on stage and push to prod next week. Tomorrow's push is only for replacing the 'international' type to blanks.

**Comment by amruelama** [comment]
Replaced all the 61 organizations' types with relevant types.
