### ISSUE TITLE
Determine the semantic relationship between NCA3 and NCA4 Regions

### ISSUE THREAD

**Issue by lomky** [USGCRP/gcis#469]
We will be changing the regions moving into the NCA4. So far the regions look like so.

We need to decide two things:

  - [x] how to relate the four new NCA4 regions to the two previous NCA3 regions. (semantic)
  - [x] a distinct label for US Southeast to distinguish the NCA3 region vs the new NCA4 region.
 

 - Unchanged:
   - Alaska (Alaska)
   - Northwest (Oregon, Washington, Idaho)
   - Southwest (Arizona, California, Colorado, Nevada, New Mexico, Utah)
   - Hawai'i (Commonwealth of the Northern Mariana Islands, Federated States of Micronesia, Hawai‘i,Republic of the Marshall Islands, Republic of Palau, Territory of American Samoa, Territory of Guam)
   - Midwest (Illinois, Indiana, Iowa, Michigan, Minnesota, Missouri, Ohio, Wisconsin)
   - Northeast (Connecticut, Delaware, District of Columbia, Maine, Maryland, Massachusetts, New Hampshire, New York, Pennsylvania, Rhode Island, Vermont, West Virginia)
 - Split into two:
   - Great plains (Kansas, Montana, Nebraska, North Dakota, Oklahoma, South Dakota, Texas, Wyoming)
       - Northern Plains (Montana, Nebraska, North Dakota, South Dakota, Wyoming)
       - Southern Plains (Kansas, Oklahoma,  Texas)
   - Southeast (Alabama, Arkansas, Florida, Georgia, Kentucky, Louisiana, Mississippi, North Carolina, Puerto Rico, Tennessee, South Carolina, U.S. Virgin Islands, Virginia)
       - Southeast (Alabama, Arkansas, Florida, Georgia, Kentucky, Louisiana, Mississippi, North Carolina,  Tennessee, South Carolina, Virginia
       - US Carribean (Puerto Rico, U.S. Virgin Islands)

**Comment by lomky** [comment]
@justgo129 do you have any advice for current semantic relationship definitions we could use in relating these geographic regions?

**Comment by lomky** [comment]
Discussion with @justgo129 

[W3C Geospatial Ontologies](https://www.w3.org/2005/Incubator/geo/XGR-geo-ont-20071023/)
[GeoNames](http://www.geonames.org/)
[Places Ontology](http://lov.okfn.org/dataset/lov/vocabs/place)

**Comment by lomky** [comment]
@rasherman You mentioned some research you had done on this on our Tag Up, could you comment here?

**Comment by rasherman** [comment]
I was thinking of the cito:updates term (http://www.sparontologies.net/ontologies/cito/source.html#d4e1449) but that says it is for things where new information is added, so it's better used for, say, a chapter in NCA4 "updating" the related chapter in NCA3.

But I think prov:wasRevisionOf (https://www.w3.org/TR/2013/REC-prov-o-20130430/#wasRevisionOf) sounds like it fits here. The new region is a revised version of the old region, in that it contains substantially the same material but was altered.

Thoughts? Haven't found anything closer, at least so far.

**Comment by lomky** [comment]
@amruelama pointed out these older tickets relating to regions & semantic:

1.    Describe the linkage between region and publication - https://github.com/USGCRP/gcis-ontology/issues/62
2.    Inform whether a region should be a subclass of prov:Entity - https://github.com/USGCRP/gcis-ontology/issues/61
3.    Creating a property for region - https://github.com/USGCRP/gcis-ontology/issues/60

**Comment by lomky** [comment]
De-prioritizing to focus on other improvements pre-NCA4.

**Comment by amruelama** [comment]
[NCA regions relationship](https://docs.google.com/spreadsheets/d/1fMc7LfK91lysolsCQ1fDDTf_yjGpRlydRe9BMgWltAg/edit#gid=0)
@R-Aniekwu

**Comment by amruelama** [comment]
@zacharylandes Please add [prov:wasRevisionOf](https://www.w3.org/TR/2013/REC-prov-o-20130430/#wasRevisionOf) relationship

**Comment by zacharylandes** [comment]
@amruelama [prov:wasRevisionOf](https://www.w3.org/TR/2013/REC-prov-o-20130430/#wasRevisionOf) relationship has been added on dev/stage
