### ISSUE TITLE
Associate the NCA 2 & 3 with Regions

### ISSUE THREAD

**Issue by lomky** [USGCRP/gcis#470]
In our system, the NCA3 and NCA2 are not associated with their regions.

Compare the turtle `## Region(s):` section for the [NCA1](https://data.globalchange.gov/report/nca1.thtml) to the turtle for the [NCA2](https://data.globalchange.gov/report/nca2.thtml) and the [NCA3](https://data.globalchange.gov/report/nca3.thtml). The GCIS NCA2 and NCA3 have never been associated with the GCIS regions.

 - [x] QA if the regions in the gcis are the same as the regions from the NCA1 assessment (they claim to be)
 - [x] QA if the regions in the assessment are the same from NCA1 -> NCA2.*
 - [x] Associate the NCA2 with regions covered in its regional chapters
 - [x] QA if the regions in the assessments are the same from NCA2 -> NCA3.*
 - [x] Associate the NCA3 with the regions covered in its regional chapters

\* If we discover any of the regions needed to add in NCA2 or NCA3 do not exist or do not match the regions in our system, create a new regions & relation between them following the conventions we set up for the NCA3 -> NCA4 regional changes set up in #469

**Comment by Zullmira** [comment]
I sent out an Excel document on all the QAs mentioned for this ticket. Just to let all of you have an overall idea that all the NCAs are different (probably includes NCA4) when it comes to sorting the regional divides. For more detailed information, please see the Excel document.

**Comment by amruelama** [comment]
[NCA regions comparison worksheet](https://docs.google.com/spreadsheets/d/1w5IaRvmCBCZ4MBt8qR5L30PXMGZl8zr6xJbiE2NcogM/edit#gid=579718652)
