### ISSUE TITLE
Support Creation of Alternate Names for Organization

### ISSUE THREAD

**Issue by lomky** [USGCRP/gcis#471]
In support of #462 

 - [x] Create a data table to store organization aliases with multi-language support

Something like:

```
organization_identifier   - FK to organization table, must exist there. Required. 
alternative_name          - the organization alternate name. varchar. Required.
language                  - the language used in the alternative name. varchar 2-3. Required.
deprecated                - if the name is still used. Boolean. Required. Default false.
```

 - [x] Update org creation to support adding organization aliases.

**Comment by lomky** [comment]
The second half of this is more in-depth than expected. Going to push the initial table support out so we can populate it and continue for the editing.

**Comment by lomky** [comment]
Proceeding nicely, breaking this into two steps for the data load in:


 1) Organizations `name`d in English with foreign `alternate_name`s will be loaded in now.
    - Organizations `name`d in another language (not our convention) will be left alone.
 2) Organizations with `name` in a foreign language will be rchanged their english `name` (easy)
    - their current name will be moved to an `alternate_name` (easy)
    - Unknown: Do we want to redo the organization `identifier` to be based on the english `name` (unknown difficulty) 
        - if so, what effect does that have on the system? On URIs?
        - @amruelama what are your thoughts on the `identifier` change? Is this a necessary thing or just nice to have for convention?

**Comment by amruelama** [comment]
@lomky I don't think there will be a problem if we retain the same identifiers (foreign language) considering the extra efforts we need to put in creating new english identifiers. Our goal is just to have the aliases listed to increase accessibility.

**Comment by lomky** [comment]
Last code changes completed. Will go out with the next release.

Still to do, on followup tickets:
 - [ ] Load in the alternate organization names on stage
   - must be AFTER the code push!
 - [ ] Rename organizations that currently have a foreign name listed as their primary
   - slightly differing from the above plan.
   - no changes to their alternate names required.
   - identifiers will be left alone.
