### ISSUE TITLE
Error building GCIS under Perl 5.22+

### ISSUE THREAD

**Issue by abuddenb** [USGCRP/gcis#476]
```
Can't load 'blib/arch/auto/Algorithm/Permute/Permute.so' for module Algorithm::Permute: blib/arch/auto/Algorithm/Permute/Permute.so: undefined symbol: PUSHBLOCK at /usr/local/lib/perl5/5.24.0/x86_64-linux/DynaLoader.pm line 193.
 at test.pl line 13.
Compilation failed in require at test.pl line 13.
BEGIN failed--compilation aborted at test.pl line 13.
```

Possibly related to using Perl 5.24. See [this issue](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=825012).

**Comment by lomky** [comment]
@abuddenb are we running on perl 5.24? I was under the impression we were developed for 5.20 with back support for 5.16.

Can you give me a bit more system context for where you are building GCIS so I can recreate?

**Comment by lomky** [comment]
Spoke with Andrew, this is something we'll have to address prior to porting to Perl 5.22+, but until then is not an issue.

**Comment by zacharylandes** [comment]
Closing due to age and irrelevance
