### ISSUE TITLE
Add new field 'Pages' to Chapter

### ISSUE THREAD

**Issue by amruelama** [USGCRP/gcis#480]
We have added chapters to only few reports in GCIS based on priority. And some of the reports have chapters added but only name and numbers populated in the chapter metadata with front page thumbnail added as a file - See [Chapters in Our Changing Planet](https://data.globalchange.gov/report/usgcrp-ocpfy2016/chapter). Adding page numbers would make it convenient to search and view the chapters in a report.

We don't have to go back and add chapters /page numbers to all the reports we are adding, but we can make it mandatory going forward. 

Note: Only for the reports added by USGCRP.

**Comment by lomky** [comment]
Moved to wiki: https://github.com/USGCRP/gcis-internal/wiki/Conventions-In-Progress

**Comment by lomky** [comment]
Reminder for future us: this ticket covers the technical implementation, and possibly the data entry. Convention is handled in the linked gcis-conventions issue.

**Comment by amruelama** [comment]
Pages field - Range. Example 10-20, 35-70
Type - Text

**Comment by amruelama** [comment]
Populate chapter pages for USGCRP publications
