### ISSUE TITLE
Add relationship and provenance for OCP 2017

### ISSUE THREAD

**Issue by amruelama** [USGCRP/gcis#481]
The latest OCP can be found [here.](https://data-stage.globalchange.gov/report/usgcrp-ocpfy2017) 
Things need to the added  
- [x] Chapters  
- [x] Figures  
- [x] Images
- [x] Tables 
- [x] References

**Comment by Zullmira** [comment]
The References are added.

**Comment by amruelama** [comment]
All the authors for the referenced articles are added.
