### ISSUE TITLE
Unique Key Error while Merging Organizations with Shared Contributor

### ISSUE THREAD

**Issue by amruelama** [USGCRP/gcis#482]
[university-queensland-australia-global-change-institute](https://data-dev.globalchange.gov/organization/university-queensland-australia-global-change-institute)
and
 [university-queensland-global-change-institute](https://data-dev.globalchange.gov/organization/university-queensland-global-change-institute)
are same institutions of University of Queensland. So while I tried to merge these organizations, it shows the following error:

> ERROR: duplicate key value violates unique constraint "contributor_person_id_role_type_organization_identifier_key" DETAIL: Key (person_id, role_type_identifier, organization_identifier)=(6189, author, university-queensland-global-change-institute) already exists. at /opt/perl5/common/libs/perl-5.20.1@gcis/lib/perl5/Tuba/Organization.pm line 189.

This may be because of the conflict between same author ([Ove Hoegh-Guldberg](https://data.globalchange.gov/person/6189)) listed in both, but note that the author is related to two different publications in each. Merging should be done such that the authors should also merge as the organizations merge. 

For now, this issue could be temporarily resolved by deleting the author/pub and adding it after the organizations are merged. But the bug should be fixed eventually.

**Comment by lomky** [comment]
Go ahead with fixing the Publications & Contributors with the workaround for now. I can reference the current state in dev to replicate the bug.

**Comment by lomky** [comment]
Discussion with @amruelama: it is unclear if this problem is due to the Organizations have the same Contributor, or if it is connected to having the same Contributor but through different Publications. (Both are true in the same case).

**Comment by lomky** [comment]
Fixed in #531
