### ISSUE TITLE
Figure/Finding/Table should sort properly

### ISSUE THREAD

**Issue by lomky** [USGCRP/gcis#487]
Figure & Table sort improperly based on assumptions about their chapter number & ordinals. Finding sorts based on identifier.  All sort Lexicographically (1, 10, 2, 20)

All of these should sort properly (1, 2, 10, 20). It would be preferable if they sorted according to their chapter number followed up their ordinal.

Adding a sort key to these tables is the likely way forward.

This is a followup to changes made in #484

**Comment by amruelama** [comment]
@zacharylandes Please see [#213](https://github.com/USGCRP/gcis_rails/issues/213)
