### ISSUE TITLE
Merge duplicate datasets

### ISSUE THREAD

**Issue by amruelama** [USGCRP/gcis#497]
- [x] Determine a criteria to QA duplicate datasets
- [x] Create a list of duplicate datasets
- [x] Make sure we don't lose any data, provenance and relationship while merging those datasets

Example:
1. https://data.globalchange.gov/dataset/noaa-ncdc-cag-us-temperature-nclimdiv
2. https://data.globalchange.gov/dataset/noaa-ncdc-c00005

**Comment by R-Aniekwu** [comment]
Possible steps for sorting duplicates:

Step 1: Distinguish between manually created datasets, and those imported from "data.gov" - sort them out.

Step 2: Review manually created datasets - sort them by identifier.

Step 3: Focus on similarities between identifiers; contributors; (and were feasible, URLs).

**Comment by R-Aniekwu** [comment]
A spreadsheet containing all GCIS data-sets, and a document detailing important notes, were created and uploaded to the GCIS google Team drive. 

The link to the document is here: https://docs.google.com/document/d/1P5zzpg917_NGI6fXbVY0DNrQ-nm2bj--sHEXx_bYF4A/edit

The link to the spreadsheet is here: https://docs.google.com/spreadsheets/d/1JWUGE1ZtZFuwIg9fBBDcK1Bjh7brkVSZQ9OY164LuLE/edit?pli=1#gid=0

The goal is to address the following questions:
1.) How many linked and unlinked datasets are there?
2.) How many datasets are versioned? 
3.) How do we version the datasets going forward?
4.) Are there any versioning related duplicates or conflict with current datasets?

The questions above have not been finalized and are subject to modification.

**Comment by R-Aniekwu** [comment]
All duplicate datasets have been successfully merged. https://docs.google.com/spreadsheets/d/1QGAR95bzoGreNd45YX4LmWhCosyWSKyAq1hMU8k6MKI/edit?ts=5e2b11b1&pli=1#gid=0
