### ISSUE TITLE
2017 CSSR Real: Create References & Child Publications

### ISSUE THREAD

**Issue by lomky** [USGCRP/gcis#501]
Once we are ready to move forward on CSSR 2017 Real Ingest:

Automated Process:
 - [x] Creating the CSSR References
 - [x] Creating the Publications in the CSSR References
 - [x] Linking the publications to their References
 - [x] Creating the Resources ( Articles, reports, Web Pages) under the publication.
 - [x] Asserting the publications are linked to their resource

Manual Process:
 - [x] Creating the non-automatic publications (anything not an Article, Report, WebPage).

**Comment by lomky** [comment]
Articles, Reports, and Web Pages will automatically create along with their References. This ticket covers the remaining ~30 references of other types.

**Comment by lomky** [comment]
All references created. About ~1550 child publications created.

**Comment by amruelama** [comment]
Non-automatic publications are created and currently under review by @rasherman ([#564)](https://github.com/USGCRP/gcis/issues/564). Closing this issue.
