### ISSUE TITLE
2017 CSSR Real: Populate Contributors

### ISSUE THREAD

**Issue by lomky** [USGCRP/gcis#502]
Following on from #500 & #501, this ticket covers the following in relation to the CSSR References

 - [x] Create the Persons  
 - [x] Create the Organizations
 - [x] Create the Contributor link between Person, Organization, and Publication.

**Comment by lomky** [comment]
@amruelama we talked about this a bit in the tag up. Would you like me to set up a new instance of GCIS where you can populate the Contributors against a dummy CSSR? Then for go-live on the CSSR we can transfer the info to stage.

**Comment by lomky** [comment]
Are we done with this @amruelama  ?

**Comment by amruelama** [comment]
We are done with CSSR first-level contributor population and closed the ticket #504. This ticket is meant for references' child publications' contributors, correct? @lomky

**Comment by lomky** [comment]
Nope, this was the Contributors section versus the Authors. So we have done this one too!
