### ISSUE TITLE
Update CSSR Authors in GCIS

### ISSUE THREAD

**Issue by lomky** [USGCRP/gcis#504]
Ticket currently pending feedback from Dave D. when he hears confirmation from the CSSR authors on how they would like their names to appear.

-- 
Authors for the upcoming CSSR are mostly in GCIS, but do not have their names formatted as in the report or according to either [our current conventions](https://github.com/USGCRP/gcis/wiki/Conventions#adding-people-to-gcis) nor the new proposed conventions in #503

**Comment by lomky** [comment]
@amruelama - I'm filing this ticket after discussion with Dave D. We'll eventually want to update the names of ~25 `Person`s, at most. He's emailing the authors to confirm how they would like to be cited and will get back to us with the info.

**Comment by lomky** [comment]
Info is being gathered on [CSSR Authors here](https://docs.google.com/spreadsheets/d/1daH3hDPidPJPHXR5FLAYl4eYpLuIq0XrxFdJ4cdbrHI/edit#gid=1643535396)

 - Things to be done: 
   - [ ] Update names to match OrcID (or other requested format)
   - [ ] Add any missing persons
   - [ ] Find any OrcIDs we are missing
   - [ ] Find the organization for this report contribution

Following this ticket's info gathering is the actual Contributor creation in #502 after the publication is created.

**Comment by amruelama** [comment]
@rasherman Contributors are added on data-review instance. Could you review this before closing this ticket?
Note : Volume Editors are considered as 'Executive Editors' and Review Editors are 'Editors' in GCIS.

**Comment by rasherman** [comment]
Some comments:
In the spreadsheet linked to above I don't see any listing for John Bruno, C. Taylor Armstrong, Boyin Huang, Laura Stevens, or Eugene Takle. But they're in the CSSR record as Contributing Authors. Where did those names come from?

**Comment by lomky** [comment]
@rasherman my bad, that spreadsheet is far out of date. We have been using the final CSSR draft version as the author reference list. I'll email you it.

**Comment by rasherman** [comment]
Ah, makes sense. It's actually really close to what's in the record, which made the small changes confusing.

**Comment by rasherman** [comment]
Ok, with that cleared up, I only notice one thing:
The report lists Ruby Leung as "L. Ruby Leung", but her ORCID profile just says Ruby Leung. I'm guessing for our GCIS record the judgment is that she gets the name on her ORCID profile, even if it says different in the report?

**Comment by amruelama** [comment]
@rasherman As we have many publications of author 'Ruby Leung' in GCIS and not just CSSR, we are using her OrcID name to avoid confusion. In case, there is an objection from author side, we can certainly change it.

**Comment by rasherman** [comment]
Ok, that's what I figured. Everything looks good, approval to call this completed!

**Comment by amruelama** [comment]
Thanks, Reid. Closing the ticket.
