### ISSUE TITLE
Create new Swagger API Page Test

### ISSUE THREAD

**Issue by lomky** [USGCRP/gcis#508]
The [previous test](https://github.com/USGCRP/gcis/blob/803e2ba3a9a761468f894cdc2c76040208c39976/t/019_swagger.t) for our [API page](https://data.globalchange.gov/api/) relied on a [deprecated Swagger module](https://metacpan.org/pod/Swagger2#DEPRECATION-WARNING) that [has begun critically failing](https://github.com/jhthorsen/swagger2/issues/99). Only the former test used this module, no actual code and the page is still working just fine. 

  - [x] Remove the failing test.
  - [ ] Create a new test for the API page

**Comment by zacharylandes** [comment]
Closing due to age and irrelevance
