### ISSUE TITLE
Make editing possible for org names without affecting the table relationship

### ISSUE THREAD

**Issue by amruelama** [USGCRP/gcis#510]
While testing alternate names, I encountered the following error. This basically happened while I tried to edit/update the names of Organizations that had alternate names : 

`ERROR: update or delete on table "organization" violates foreign key constraint "organization_alternate_name_organization_identifier_fkey" on table "organization_alternate_name" DETAIL: Key (identifier)=(university-utrecht-department-physical-geography) is still referenced from table "organization_alternate_name"..`

**Comment by lomky** [comment]
I don't get any error when updating an Organization Name on review. Do you mean changing the Organization Identifier?

**Comment by amruelama** [comment]
Yes, I am trying to change both identifier and name for an organization without affecting the alternate name (relationship). Do we already have this capability or we need to delete and re-add the alternate name each time we edit an identifier and name?

**Comment by lomky** [comment]
This should work, it's a bug. I'll look into it.

**Comment by amruelama** [comment]
Sure, thanks!

**Comment by lomky** [comment]
Found it! Simple fix (I forgot to set the Alternate Name foreign key to cascade changes). I'll add the code and make a 1.48.1 release, and we can have this go out shortly.

**Comment by lomky** [comment]
There is an existing bug as well, where after you update an identifier the redirect fails (tries to go to the old identifer)

**Comment by lomky** [comment]
Fixed in release 1.48.1
