### ISSUE TITLE
Make adding publications to authors possible

### ISSUE THREAD

**Issue by amruelama** [USGCRP/gcis#511]
Adding publications to authors is not possible. This may be a bug. Typically, we add authors directly under articles (publications). But when I tried to add articles under an author, the feature does not work.

Ex: I need to add the article "Monitoring and reducing exposure of infants to pollutants in house dust." to the author - https://data-stage.globalchange.gov/person/8939

**Comment by lomky** [comment]
I think this is working. @amruelama can you test the paths to see if they all work, and update the ticket?

**Comment by amruelama** [comment]
@lomky This isn't working for me. Can you tell me if you could add the article "Monitoring and reducing exposure of infant..." under relationship>publication - https://data-stage.globalchange.gov/person/form/update_rel/8939?

**Comment by lomky** [comment]
@amruelama Yes, I did? You need to have an organization, publication, and role, but then it works.

**Comment by amruelama** [comment]
Oh, sorry-my fault! I've been adding it without organization. Closing this issue.
