### ISSUE TITLE
Remove bullet symbol where organization is blank

### ISSUE THREAD

**Issue by amruelama** [USGCRP/gcis#512]
[This](https://data-stage.globalchange.gov/article/10.1007/978-1-4419-0032-6_1) article's authors affiliations are not listed in the publication page. In this case, the organization should be left blank as per GCIS conventions. So we should change the default template to make sure we don't have bullet symbol for blank organizations.

**Comment by lomky** [comment]
@amruelama given we don't want to have authors without orgs in our system in the long run, do you still want this change?

**Comment by amruelama** [comment]
@lomky Yes, because we do not want to keep just the bullets where affiliations are null. Also, let's decide this after we come up with ideas on how to denote unlisted affiliations on the article's front page in GCIS.

**Comment by lomky** [comment]
How's this look, @amruelama 

<img width="1032" alt="screen shot 2017-04-21 at 11 55 28 am" src="https://cloud.githubusercontent.com/assets/6129479/25285795/7cbf63c2-2689-11e7-8216-b181f3e17db3.png">

**Comment by amruelama** [comment]
@lomky Perfect. This is what I need.
