### ISSUE TITLE
Swap Organization Names to English-Based Versions

### ISSUE THREAD

**Issue by lomky** [USGCRP/gcis#517]
Now that we support alternate names, we want to go through the organization that  are named in their original language, set their name to the English version, and then set their alternate_name appropriately.

**Comment by lomky** [comment]
@amruelama this is complete for all but two of the provided entries, which will need to be handled by hand:

 - `technische-universitat-munchen` : Another `technical-university-munich` already exists. Will need to be merged, I think?
 - `consejo-superior-de-investigationes-cientificas-institute-marine-sciences` : This just keeps throwing errors when I try to update via script. As it's only one entry, can you update this one by hand?

[Here is the reference sheet](https://docs.google.com/spreadsheets/d/107ifDh-nHYt4mn1l4VxBjSMglUrNn_PlvjVmO7gYwHo/edit#gid=0)

**Comment by amruelama** [comment]
I may have another list of organizations to swap identifiers/titles. Sorry @lomky. But it can wait until next content push.

**Comment by lomky** [comment]
@amruelama No issue at all. Just ping me the spreadsheet with the current identifier, the new english name, the foreign name, the foreign language, and the new english/ascii identifier.

**Comment by amruelama** [comment]
@lomky Will do

**Comment by amruelama** [comment]
I've fixed the above two organizations on stage manually. I am also creating the new list of organizations to swap aliases.

**Comment by amruelama** [comment]
@lomky - New list of organizations to swap is currently on the same reference sheet (sheet - update_0927)

**Comment by lomky** [comment]
@amruelama the `update_0927` sheet has been run. All but three went in automatically. These three look as though there are duplicate named orgs to deal wtih:

```
leibniz-institut-fur-meereswissenschafte-an-der-universitat-kiel
max-planck-institut-fur-meteorologie
museum-national-dhistorie-naturelle
```

Sheet has been updated to reflect all but those three run. Many of these actually already had the alternate name set, but I updated the script to handle that case.

**Comment by amruelama** [comment]
Thanks! Let me go ahead and fix those three redundancies.

**Comment by amruelama** [comment]
Fixed three organizations on stage.

**Comment by amruelama** [comment]
Complete and changes pushed to prod.
