### ISSUE TITLE
Allow to enter sort key while entering/relating data in edit mode 

### ISSUE THREAD

**Issue by amruelama** [USGCRP/gcis#518]
Currently we can enter the sort key only after saving the changes (adding/ relating the person or organization). Allow to add the sort key as we enter contributor data for an article.

**Comment by lomky** [comment]
Doing a first-pass on this to see how hard it'll be to front this

**Comment by lomky** [comment]
this is doable @amruelama 

It will be on a per-object basis, can you give me the ones you want this the most on? All of them or just a subset?

**Comment by amruelama** [comment]
Great! Basically, I need this feature while adding contributors for any article. Is that possible?

**Comment by lomky** [comment]
@amruelama This should now be functional on data-review for Contributors on Articles. Can you test it out?

Let me know of any other high-priority places you'd like to get the sort_key on.

**Comment by amruelama** [comment]
@lomky Just tested. Works perfect!
