### ISSUE TITLE
Handle article identifier redundancy in GCIS and fix the duplicates

### ISSUE THREAD

**Issue by amruelama** [USGCRP/gcis#536]
The following articles are redundant, queried by similar name, similar journal, but different article identifiers. The two possible reason for this redundancy are upper case/ lower case differences and PMID/PMC differences in identifiers, i.e., the differences in alphabet characters only. Although the article identifiers are created by DOIs/PMIDs/PMCs the system doesn't warn about duplicate identifiers due to the above reasons. 

1. https://data.globalchange.gov/search?q=Incidence+and+trends+of+infection+with+pathogens+transmitted+commonly+through+food--Foodborne+Diseases+Active+Surveillance+Network%2C+10+U.S.+sites%2C+2006-2013
2. https://data.globalchange.gov/search?q=Temporal+variations+in+frost-free+season+in+the+United+States%3A+1895–2000&type=all&format=detailed
3. https://data.globalchange.gov/search?q=Global+Climate+Change+and+Children%27s+Health+&type=all&format=detailed

Going forward, we should make sure the system should handle /warn the redundancy in this case.

**Comment by lomky** [comment]
@amruelama

 - I plan on making the article identifier case insensitive.
 - I can have the system reject PMC/PMID if their numeric parts match. 
 - The last pair are actually distinct IDs - differing by one number. I don't see anything to do for them?

**Comment by lomky** [comment]
@amruelama here are the articles that have multiple entries:


| count |           DOI 1 | link | DOI 2 | link 2 |
|--|--|--|--|--|
|     2 | 10.1175/bams-d-13-00085.1 | https://data-stage.globalchange.gov/article/10.1175/bams-d-13-00085.1 | 10.1175/BAMS-D-13-00085.1 | https://data-stage.globalchange.gov/article/10.1175/BAMS-D-13-00085.1  |
|     2 | 10.1029/2003gl018624      | https://data-stage.globalchange.gov/article/10.1029/2003gl018624      | 10.1029/2003GL018624      | https://data-stage.globalchange.gov/article/10.1029/2003GL018624       |
|     2 | 10.1175/2008jcli2561.1    | https://data-stage.globalchange.gov/article/10.1175/2008jcli2561.1    | 10.1175/2008JCLI2561.1    | https://data-stage.globalchange.gov/article/10.1175/2008JCLI2561.1     |
|     2 | 10.1186/1476-069x-8-40    | https://data-stage.globalchange.gov/article/10.1186/1476-069x-8-40    | 10.1186/1476-069X-8-40    | https://data-stage.globalchange.gov/article/10.1186/1476-069X-8-40     |
|     2 | 10.1175/jcli-d-14-00656.1 | https://data-stage.globalchange.gov/article/10.1175/jcli-d-14-00656.1 | 10.1175/JCLI-D-14-00656.1 | https://data-stage.globalchange.gov/article/10.1175/JCLI-D-14-00656.1  |
|     2 | 10.5751/es-04543-170110   | https://data-stage.globalchange.gov/article/10.5751/es-04543-170110   | 10.5751/ES-04543-170110   | https://data-stage.globalchange.gov/article/10.5751/ES-04543-170110    |
|     2 | 10.1175/jcli-d-12-00593.1 | https://data-stage.globalchange.gov/article/10.1175/jcli-d-12-00593.1 | 10.1175/JCLI-D-12-00593.1 | https://data-stage.globalchange.gov/article/10.1175/JCLI-D-12-00593.1  |

**Comment by lomky** [comment]
@amruelama I can't put the code fix in until we remove the existing duplicate entries. Delaying this until next release.

**Comment by amruelama** [comment]
@lomky Do you want me to fix these manually while you update the system to handle case sensitivity?

**Comment by amruelama** [comment]
All the duplicates are removed! @lomky

**Comment by lomky** [comment]
@amruelama the DOI case insensitive change is live on data-review, please confirm it works like you would like it to.

**Comment by amruelama** [comment]
Tested. Looks good to me @lomky
