### ISSUE TITLE
Establish Provenance Weights

### ISSUE THREAD

**Issue by lomky** [USGCRP/gcis#538]
Following on the discussions last year of metrics. #406 

 - [x] Finalize scores for the various Resources in GCIS.

[The rating criteria](https://github.com/USGCRP/gcis-provenance-evaluator/blob/master/docs/initial_design/initial_design.md#provenance-rating)  
[Internal scores](https://github.com/USGCRP/gcis-provenance-evaluator/blob/master/scores/internal_score.yaml)  
[Connection scores](https://github.com/USGCRP/gcis-provenance-evaluator/blob/master/scores/connection_score.yaml)  
[Component links](https://github.com/USGCRP/gcis-provenance-evaluator/blob/master/config/components.yaml)

**Comment by rasherman** [comment]
Comments on internal scoring (my opinion! happy to debate if you disagree):

Array - unless I'm misreading, it looks like the "very poor" is what should be "very good" (additional info on the header). Did it get misplaced?

Chapter - I think there's a typo, the "very good" criteria asks for number twice. Was one of those supposed to be something else?

Dataset - The "good" criteria second option should be reduced to just the most citation-relevant info and the rest (e.g. scope, access_dt, release_dt) can be moved to the "very good" criteria

Instrument - I'm a bit confused by how this works, nothing is required for acceptable, but poor requires a description?

Journal - shift to reflect no publisher field, which will eventually happen in the system. Should we require a title to be acceptable? I kind of think so.

Model - name should be required along with website for "good". Not sure I really understand the difference between website and reference url.

Organization - very good requires international, but isn't that field left blank unless it's an international organization (which would mean only international organizations could be classified as very good)

Report - Acceptable should need a doi or url, is the "files:0:identifier" saying that the alternative is having the file of the report attached to the record?

Scenario - what is in "poor" should be in "good", I think, and "acceptable" should need a name or at least an attribution or some additional info

Table - swap the importance of caption and url

Webpage - swap the importance of title and access date.

**Comment by lomky** [comment]
> Array - unless I'm misreading, it looks like the "very poor" is what should be "very good" (additional info on the header). Did it get misplaced?

Array is a weird object in our system. Arrays will *always* have `identifier` and `rows_in_header` (db requirement). Then we are saying they should have `rows` - i.e. any data. - to be acceptable.

> Chapter - I think there's a typo, the "very good" criteria asks for number twice. Was one of those supposed to be something else?

Good catch. I don't see any other field that I think would make a 'very good' rating.
 
> Dataset - The "good" criteria second option should be reduced to just the most citation-relevant info and the rest (e.g. scope, access_dt, release_dt) can be moved to the "very good" criteria

Which things do you feel should be moved from here? I was unsure on them.

```
        - access_dt
        - data_qualifier
        - cite_metadata
        - scope
        - version
        - native_id
        - release_dt
        - publication_year
        - description_attribution
```

> Instrument - I'm a bit confused by how this works, nothing is required for acceptable, but poor requires a description?

Going on the criteria of 'provenance', it seemed to be that our object is not very sufficient (no unique  external identifier, no URL). So I didn't create an acceptable level. We can have a description_attribution, which is at least an external source of the description, so I put that in for good. I think it would also be reasonable to have 'very poor', 'poor' and 'acceptable' (where 'acceptable' has description_attribution), if you think that makes more sense.

> Journal - shift to reflect no publisher field, which will eventually happen in the system. Should we require a title to be acceptable? I kind of think so.

Good call on `publisher`. For this script the "connections" path will find it and the grading script can penalize for lacking a "publisher" role type contributor.  

In my mind, the existence of unique external identifiers (`issn`) makes the `title` not required for 'acceptable' provenance. For example, if we have a `title` but no `issn` or `URL`, I don't think that should count as 'acceptable', whereas if we have the `ISSN`, you can get a `title` from that with minimal effort from the official ISSN lookup.  
I do think it's better to have a `titl`e, hence why it's a qualifier for 'good' provenance.  
Definitely interested to hear more thoughts on this.

> Model - name should be required along with website for "good". Not sure I really understand the difference between website and reference url.

Sounds good wrt the `name` required with `website` for 'good'.  
This object is a bit wonky. Here are the details on the fields:

```
 identifier                        | A unique descriptive identifier.
 project_identifier           | A project associated with this model.
 name                              | A brief name.
 version                           | A version.
 reference_url                 | A URL to find publiations with details about this model.
 website                          | A public website with high level descriptions about this model.
 description                    | A description.
 description_attribution | A URL containing the description of this model.
```

You can find this info for any given table here:  
https://github.com/USGCRP/gcis/tree/master/db/dist/docs/pod

> Organization - very good requires international, but isn't that field left blank unless it's an international organization (which would mean only international organizations could be classified as very good)

'very good' only requires *either* `international` or `country code` to be filled in.

> Report - Acceptable should need a doi or url, is the "files:0:identifier" saying that the alternative is having the file of the report attached to the record?

Correct, that's how to find if it has the report attached.  
To get 'acceptable' the object **must** have **any one of**:  
a `url` to the report,  
the `doi` of the report, or  
a downloadable file _of the report itself_

> Scenario - what is in "poor" should be in "good", I think, and "acceptable" should need a name or at least an attribution or some additional info

Same uncertainty here on my part as with the 'instrument' object earlier.  
We should probably just have a 15 minute chat with @amruelama about scenarios/models/model_runs and instruments/platforms. These object sets are both later additions to the GCIS data model and underrepresented in the actual production data, so they're harder to judge.

> Table - swap the importance of caption and url

I don't quite understand. I feel as though a `url` to the table adds provenance value, but isn't necessary (not all tables have stand alone websites). `Caption`s are good information, but don't seem related to provenance to me. Am I missing context?

> Webpage - swap the importance of title and access date.

I can get behind `title` in the 'good' category. Does the `access date` not improve the citation of a website, though? 

---

Updated the internal score as follows:  
  - chapter: removed redundant 'very_good' `number` qualifier.
  - journal: removed `publisher` fields from consideration.
  - model: added `name` to 'good' qualifier with `website`
  - webpage: moved `title` to 'good' level.

**Comment by rasherman** [comment]
Thanks. I can't answer all your questions immediately, but here's my answers to a few:

Dataset - move scope, access_dt, release_dt, and description attribution to very good. Rest should stay.

Journal - you're very right that title is not absolutely necessary to follow the provenance, and can be found if you have the ISSN, but as your navigating, knowing the title makes it much easier to know what's going on and what you're looking at. Without it you can still follow provenance but it adds some annoyance, making me think that should be the "poor" level.

Table - similarly, you're right that the URL is higher traceability value than the caption, but we do have to balance with ease of understanding and use, and a caption helps a user significantly in knowing that the table they're looking at is, in fact, the one they're interested in. Anyway that's my thinking.
