### ISSUE TITLE
Read Only Admin Access

### ISSUE THREAD

**Issue by lomky** [USGCRP/gcis#539]
Create a read-only access level that allows access to the admin watch activity pages, but does not allow access to the Update forms / POST methods.

**Comment by lomky** [comment]
@Zullmira You should now have the ability to view the watch page on the `dev` server (not yet released to `stage`). Could you test this for me? You'll need to be in the office to access `dev`.

  1. Connect to the ICF VPN.
  1. Log in here with your @usgcrp.gov email: https://data-dev.globalchange.gov/login
  1. Check that this page loads: https://data-dev.globalchange.gov/watch
  1. Confirm that you see the `Admin` link on the bottom of the left panel menu.

If it works to your satisfaction, it will go out next week.

**Comment by lomky** [comment]
Assigned read-only access on dev to @amruelama temporarily for testing purposes.

**Comment by amruelama** [comment]
I can view the watch activity/summary via admin page now with read-only access.

**Comment by Zullmira** [comment]
I can view "watch activity" from the "stage" domain finally.
