### ISSUE TITLE
Do we need 'publisher' field in GCIS Journals?

### ISSUE THREAD

**Issue by amruelama** [USGCRP/gcis#545]
In GCIS, we can add publisher as an organization and relate them to the journal as a contributor. But we also have a field called 'publisher' under journal. Basically we need to add the same publisher name in the field. We can totally get rid of this field, if there is no specific importance to it. If we populate publisher field and also add the publisher as a contributor, it appears twice on journal page display. See CDC - https://data.globalchange.gov/journal/morbidity-mortality-weekly-report

If we get rid of this field, we need to make sure all the publishers listed under their journals are already available in GCIS organizations, if not we need to add them and relate them as publisher. 

@rasherman Do you have any suggestions?

**Comment by lomky** [comment]
I'm a fan of removing the field on Journal, instead using the contributor relationship.

**Comment by rasherman** [comment]
As I mentioned when we talked recently, I agree. We may need a script to make sure that any organization listed in the publisher field is appropriately linked as a contributor so we don't lose data, but it's much better if it is stored as a relationship rather than a field in the journal metadata.

**Comment by amruelama** [comment]
Closing this issue and will follow up on #548
