### ISSUE TITLE
Warn if a title is typed with extra space(s)

### ISSUE THREAD

**Issue by amruelama** [USGCRP/gcis#547]
As organization identifiers are automatically created from titles and according to identifier convention spaces are replaced with hyphens, while copy/pasting titles that starts with a space (accidentally), the identifiers will be prefixed with hyphens. So to follow GCIS org convention, either don't allow titles with prefixed or suffixed with space(s) or display error message to delete extra spaces.

**Comment by lomky** [comment]
@amruelama this is live on data-dev for your review.

**Comment by amruelama** [comment]
@lomky Looks good on dev! Basically, instead of warning, it ignores extra spaces, correct?

**Comment by lomky** [comment]
@amruelama Correct!

**Comment by amruelama** [comment]
Can we also make sure to replace ' - ' with '-' instead of '--'

For instance,  **Public Assistance - Paris Hospitals** (title) should be  **public-assistance-paris-hospitals** (identifier) instead of **public-assistance--paris-hospitals**
