### ISSUE TITLE
Fix 'remove alternate name' button

### ISSUE THREAD

**Issue by amruelama** [USGCRP/gcis#550]
'Remove alternate name' button doesn't seem to work. Check - https://data-stage.globalchange.gov/organization/organisation-economic-co-operation-development-publishing-oecd and try to remove the alternate name 'Les Editions de l'OCDE '

See log below:

> [Wed Aug  2 14:09:21 2017] [debug] POST "/organization/rel/organisation-economic-co-operation-development-publishing-oecd"
[Wed Aug  2 14:09:21 2017] [debug] Routing to a callback
[Wed Aug  2 14:09:21 2017] [info] user: aelamparuthy@usgcrp.gov
[Wed Aug  2 14:09:21 2017] [debug] Routing to controller "Tuba::Organization" and action "update_rel"
[Wed Aug  2 14:09:21 2017] [debug] 302 Found (0.010573s, 94.581/s)
[Wed Aug  2 14:09:21 2017] [debug] GET "/organization/form/update_rel/organisation-economic-co-operation-development-publishing-oecd"
[Wed Aug  2 14:09:21 2017] [debug] Routing to a callback
[Wed Aug  2 14:09:21 2017] [info] user: aelamparuthy@usgcrp.gov
[Wed Aug  2 14:09:21 2017] [debug] Routing to controller "Tuba::Organization" and action "update_rel_form"
[Wed Aug  2 14:09:21 2017] [debug] Rendering template "organization/update_rel_form.html.ep"
[Wed Aug  2 14:09:21 2017] [debug] Rendering template "update_tabs.html.ep"
[Wed Aug  2 14:09:21 2017] [debug] Rendering template "messages.html.ep"
[Wed Aug  2 14:09:21 2017] [debug] Rendering template "controls/autocomplete.html.ep"
[Wed Aug  2 14:09:21 2017] [debug] Rendering cached template "controls/autocomplete.html.ep"
[Wed Aug  2 14:09:21 2017] [debug] Rendering cached template "controls/autocomplete.html.ep"
[Wed Aug  2 14:09:21 2017] [debug] Rendering template "modal.html.ep"
[Wed Aug  2 14:09:21 2017] [debug] Rendering template "layouts/default.html.ep"
[Wed Aug  2 14:09:21 2017] [debug] Rendering template "menu.html.ep"
[Wed Aug  2 14:09:21 2017] [debug] 200 OK (0.131737s, 7.591/s)

**Comment by lomky** [comment]
Found the bug. We're not properly escaping the `'` in `l'OCDE`. Fixing.

**Comment by lomky** [comment]
@amruelama this is fixed. You can test it [on dev](https://data-dev.globalchange.gov/organization/form/update_rel/organisation-economic-co-operation-development-publishing-oecd)

**Comment by amruelama** [comment]
Tested on dev. It works! @lomky
