### ISSUE TITLE
Arrays not linked to datasets for Indicators

### ISSUE THREAD

**Issue by rasherman** [USGCRP/gcis#551]
Currently in Indicators' provenance, the image has a semantic link to the dataset, but the array does not, even though the array was directly derived from the dataset.

Both image and array should have the same "wasDerivedFrom" link to the dataset that provided the information.

**Comment by amruelama** [comment]
List of indicators to be linked to dataset through image and array:

- [ ] [Indicator: Annual   Greenhouse Gas Index](https://data-stage.globalchange.gov/report/indicator-annual-greenhouse-gas-index)
- [ ] [Indicator: Annual Greenhouse Gas Index-2016](https://data-stage.globalchange.gov/report/indicator-annual-greenhouse-gas-index-2016)
- [ ] [Indicator: Arctic Glacier Mass Balance-2016](https://data-stage.globalchange.gov/report/indicator-arctic-glacier-mass-balance-2016)
- [ ] [Indicator: Arctic Sea Ice Extent](https://data-stage.globalchange.gov/report/indicator-arctic-sea-ice-extent)
- [ ] [Indicator: Arctic Sea Ice Extent-2016](https://data-stage.globalchange.gov/report/indicator-arctic-sea-ice-extent-2016)
- [ ] [Indicator: Atmospheric Carbon Dioxide](https://data-stage.globalchange.gov/report/indicator-atmospheric-carbon-dioxide)
- [ ] [Indicator: Atmospheric Carbon Dioxide-2016](https://data-stage.globalchange.gov/report/indicator-atmospheric-carbon-dioxide-2016)
- [ ] [Indicator: Frost-Free Season](https://data-stage.globalchange.gov/report/indicator-frost-free-season)
- [ ] [Indicator: Frost Free Season-2016](https://data-stage.globalchange.gov/report/indicator-frost-free-season-2016)
- [ ] [Indicator: Global Surface Temperatures](https://data-stage.globalchange.gov/report/indicator-global-surface-temperature)
- [ ] [Indicator: Global Surface Temperatures-2016](https://data-stage.globalchange.gov/report/indicator-global-surface-temperature-2016)
- [ ] [Indicator: Heating and Cooling Degree Days](https://data-stage.globalchange.gov/report/indicator-heating-cooling-degree-days)
- [ ] [Indicator: Heating and Cooling Degree Days-2016](https://data-stage.globalchange.gov/report/indicator-heating-cooling-degree-days-2016)
- [ ] [Indicator: Ocean Chlorophyll Concentrations](https://data-stage.globalchange.gov/report/indicator-ocean-chlorophyll-concentrations)
- [ ] [Indicator: Sea Surface Temperatures](https://data-stage.globalchange.gov/report/indicator-sea-surface-temperature)
- [ ] [Indicator: Sea Surface Temperatures-2016](https://data-stage.globalchange.gov/report/indicator-sea-surface-temperature-2016)
- [ ] [Indicator: Start of Spring](https://data-stage.globalchange.gov/report/indicator-start-of-spring)
- [ ] [Indicator: Start of Spring-2016](https://data-stage.globalchange.gov/report/indicator-start-of-spring-2016)
- [ ] [Indicator: Terrestrial Carbon Storage](https://data-stage.globalchange.gov/report/indicator-terrestrial-carbon-storage)
- [ ] [Indicator: U.S. Surface Temperatures](https://data-stage.globalchange.gov/report/indicator-us-surface-temperature)
- [ ] [Indicator: U.S. Surface Temperatures-2016](https://data-stage.globalchange.gov/report/indicator-us-surface-temperature-2016)

**Comment by amruelama** [comment]
@rasherman I have added array-dataset relationship for all the available indicators (listed above). Could you QA the list?

**Comment by amruelama** [comment]
Reviewed by @rasherman
