### ISSUE TITLE
Fix blank indicator page on stage

### ISSUE THREAD

**Issue by amruelama** [USGCRP/gcis#552]
Currently we can view the list of indicators only on prod and not on stage - https://data-stage.globalchange.gov/indicator. To be specific, the list shows up on stage when logged out, but shows just a blank page when logged in. This needs to be fixed for reference purposes.

**Comment by lomky** [comment]
I replicated the issue on Dev, and I believe I have fixed it. @amruelama can you confirm the indicators page now works properly on dev?

Also removed the non-functional favorite (♥) page

**Comment by amruelama** [comment]
Yes, the indicator page works now on dev.
