### ISSUE TITLE
Script to Inform Authors from ORCiD based on DOIs

### ISSUE THREAD

**Issue by lomky** [USGCRP/gcis#554]
- [x] Script to pull info from ORCiD
- [x] Research
- [x] Script to populate info into GCIS

Script will query the ORCiD Public API with a DOI, which returns a list of associated orcIDs

Input: `https://pub.orcid.org/v2.0/search?q=digital-object-ids%3A%252210.6084%2FM9.FIGSHARE.1115124%E2%80%99%2522`

Responds: 
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<search:search num-found="8995" xmlns:search="http://www.orcid.org/ns/search" xmlns:common="http://www.orcid.org/ns/common">
      <search:result>
            <common:orcid-identifier>
                  <common:uri>http://orcid.org/0000-0001-5109-3700</common:uri>
                  <common:path>0000-0001-5109-3700</common:path>
                  <common:host>orcid.org</common:host>
            </common:orcid-identifier>
      </search:result>
      <search:result>
            <common:orcid-identifier>
                  <common:uri>http://orcid.org/0000-0002-6363-0064</common:uri>
                  <common:path>0000-0002-6363-0064</common:path>
                  <common:host>orcid.org</common:host>
            </common:orcid-identifier>
      </search:result>
[SNIP]
</search:search>
```

Script should then offer some way for us to merge this data. More brainstorming needed.

**Comment by lomky** [comment]
Whiteboard Brainstorming Summary

## First Script - Data Gatherer
### Input
  - A list of `DOI`s
### Script Process
#### `ORCiD` Interactions
  - Query ORCiD API for the `ORCiD`s associated with each`DOI`s
  - Query ORCiD API for the information associated with each `ORCiD`
    - **ASSUMPTION:** we can always get first and last name
#### `GCIS` Interactions 
  - Query for a `GCIS Person` with matching `ORCiD`
  - Otherwise, Query for a `GCIS Person` with matching full name
  - Otherwise, Query for a `GCIS Person` with matching last name
  - Other match methods ?
#### Output CVS for Data Reviewing
  - CVS with the following columns:
    ``` DOI, ORCiD, First Name, Last Name, Person_ID, Match Certainty, Match Method, Confirm Match, Organization ID, Person URL```
    - `DOI` - the input `DOI`
    - `ORCiD` - the `ORCiD` returned from the ORCiD API
    - `First Name` - the first name returned from the ORCiD API
    - `Last Name`- the last name returned from the ORCiD API
    - `Person_ID` - the `Person` `id` returned from the GCIS matching
    - `Match Certainty` - our confidence level of the match, based on the match method.
    - `Match Method` - "ORCiD Match", "Full Name Match", "Last Name Match", "No Match", ...
    - `Confirm Match` - blank, meant to be filled `true` by Data Manager QA if the provided match is right.
    - `Organization ID` - blank, meant to be filled by Data Manager QA with the GCIS `organization` `id` for the `contributor` to be created
    - `Person URL`  - blank, meant to be filled by Data Manager QA if we are creating a new GCIS `Person`. Optional, but preferred.
    - TODO: organization data, for new orgs

## Middle step - Research

Given the output, the data manager needs to:

  - QA the matches, correcting the sheet as needed.
  - Find the organizations for the contributors
  - Find the person information, if new
  - Find the organization information, if new

## Second Script - Updates GCIS

### Input

The modified CVS from the first script

### Process

  - Creates the Person, if needed
  - Creates the Organization, if needed
  - Updates an existing Person with the ORCiD, if needed
  - Creates a Contributor between the Person, Organization, and Article

### Output

New GCIS objects.

## Future Work
  - Extend input to PubMed IDs
    - does ORCiD support them?
  - Script warns on name match but ORCiD differ
    - left to hand QA for now
  - second script should create organization, if needed?

The whiteboard itself:

![orcid api brainstorm](https://user-images.githubusercontent.com/6129479/29419696-c372a2be-833d-11e7-961c-1d7e7665657b.jpg)

**Comment by lomky** [comment]
First Script is complete. It can be found at [find-authors-from-orcid](https://github.com/USGCRP/gcis-scripts/blob/master/qa_scripts/find-authors-from-orcid.pl).

@amruelama is currently processing all DOIs [here](https://docs.google.com/a/usgcrp.gov/spreadsheets/d/12iIz-qAriujp6VzKEX9FB8CTyKygDLLzLaeiJYpn-vg/edit?usp=sharing)

**Comment by amruelama** [comment]
@lomky Can we run this script for CSSR articles' DOIs as well?

**Comment by amruelama** [comment]
Update: QA part of this spreadsheet is done. That is, populated 'confirm_match' column. @R-Aniekwu is working on populating the additional info needed for new contributors, or updating the existing contributors' info. 
@lomky I'm not sure if you're going to make this update in single pass or split them based on the 'confirm_match' categories. But just to let you know, the rows with filter 'yes' under 'confirm_match' column are good to go.

**Comment by lomky** [comment]
Working forward on the new scripts, now informed by how the spreadsheet was created

# Second Script - Updates GCIS with New Contributors, Updated Persons, New Persons/Organizations

## Input

The modified CVS from the first script

Columns - Expected Values & Behaviors

|Column Name | Auto Generated? | Expected Values | Expected Script Behavior |
|-|-|-|-|
| match_method             | Yes                   | how the person was matched in GCIS by prev script | ignored |
| first_name               | Yes, modified         | Auto-generated or corrected name value | used for new persons or on update name, otherwise ignored |
| last_name                | Yes, modified         | Auto-generated or corrected name value | used for new persons or on update name, otherwise ignored |
| doi                      | Yes                   | ORCid provided doi | used to ID the contributor publication |
| DOI (linked)             | No                    | DOI with link | ignored |
| Article in GCIS          | Yes                   | GCIS link | ignored |
| orcid                    | Yes                   | Auto-generated orcid | updated on the person, always |
| person_id                | Yes, modified         | autogenerated or filled in person_id. | Used to ID the contributor person. If N/A, person to be created |
| confirm_match            | No                    | Yes, Ignore, Update Name in GCIS, Update URL in GCIS, Update Name & URL in GCIS | Yes-Update ORCid on person & make contributor if needed, Ignore-skip line, Update * in GCIS - Update the noted value on Person (Name, URL, or both) |
| organization_id          | No                    | An existing organization Id or blank | Use this organization for the contributor. Blank means new org |
| Org in GCIS              | No                    | a link to the existing gcis org | ignored |
| person_url               | No                    | a url for the Person, or blank | used for new persons or on update name, otherwise ignored |
| org_name                 | No                    | the new orgs name | used for new orgs only |
| org_type                 | No                    | the new orgs type | used for new orgs only |
| org_url                  | No                    | the new orgs url | used for new orgs only |
| org_country_code         | No                    | the new orgs country code | used for new orgs only |
| org_international_flag   | No                    | the new orgs internaltion flag | used for new orgs only |
| related_org              | No                    | the new orgs parent org | ignored in first pass |
| related_org_relationship | No                    | the new orgs parent relationship | ignored in first pass |
| Sort Key                 | No                    | the contributor sort_key value | optional, used for contributor |
| contributor_role         | No                    | the contributor role, or blank | the contributor role. Blank defaults to author |
| Alternate name           | No                    | organization alternate name | ignored in first pass |
| Language code            | No                    | organization alternate name language | ignored in first pass |
| Reuben Notes             | No                    | notes from Rueben | ignored |
| Amrutha Notes            | No                    | notes from Amrutha | ignored | 

## Process

<img width="1120" alt="screen shot 2017-12-14 at 11 52 15 am" src="https://user-images.githubusercontent.com/6129479/34004202-43812982-e0c5-11e7-8138-06018b224238.png">

## Output

New Contributors, Persons, Organizations

**Comment by lomky** [comment]
@amruelama @R-Aniekwu The QA needs to be continued on the spreadsheet - Where column A says `Matched on ORCid` only indicates the Person in GCIS exists & has that ORCid. 

They still need to be QA'd for:

  - The Person info is correct:
    + The Person name is correct
    + The Person url is correct
  - The Contributor record exists for this Person/Article/Role
    + If no contributor record, the Organization for the new Contributor record is filled in
      * Either the existing Organization's ID placed in the org_id field or the org_* fields filled in

**Comment by lomky** [comment]
To determine: how to handle in the script the case of a new person with multiple roles. They will be a new person the first row, and an existing person the second. Match on processed ORCids?

If new person, if ORCid already seen?

**Comment by lomky** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [OrcID DOI Script](https://trello.com/c/h7jp8IKd/23-orcid-doi-script)

**Comment by lomky** [comment]
DOI has decommisioned the API we interface with on the first script, so I will need to update that....

**Comment by lomky** [comment]
@amruelama I've emailed you the sample output and post-run QA sheet. Please spotcheck the various cases and let me know if this is good to go!

**Comment by amruelama** [comment]
Working on this now.

**Comment by amruelama** [comment]
Spot checked and added notes for article that needs manual update on stage. Everything looks good! @lomky

**Comment by lomky** [comment]
Updates have been applied to stage. @amruelama is reviewing the ~300 of the 2600 that required a second look.

Follow-on work:
  - new organizations alternate names
  - new organizations relationship

**Comment by amruelama** [comment]
- [ ] Review, QA and update missing data
- [ ] QA and resolve the list of errors
- [ ] Add new organizations' relationship. Create new org if required
- [ ] Add alternate names for new organizations.

**Comment by amruelama** [comment]
@rasherman Could you review and spot check few cases from the above updates and comment on the working sheet. Once reviewed, I will push the content to prod friday morning.

**Comment by amruelama** [comment]
Some URLs are missing. This may have happened due to filter. @lomky Once updated, I will push the content to prod next wednesday.

**Comment by lomky** [comment]
URLs have been corrected! Closing~
