### ISSUE TITLE
Update info on Arctic Glacier Mass Balance Indicator

### ISSUE THREAD

**Issue by rasherman** [USGCRP/gcis#561]
There's an altered image and some changed wording for the Arctic Glacier indicator. This needs to be updated with the info from the files attached to this ticket. Priority low until after CSSR release, but can always be updated on review and then it will just be eventually pushed along with CSSR content.

![arcticglaciers_8_23_17](https://user-images.githubusercontent.com/21958420/31242540-5be3e112-a9d5-11e7-8796-4608abb31afc.jpg)
[Arctic Glaciers indicator 10-03-17 clean.docx](https://github.com/USGCRP/gcis/files/1360364/Arctic.Glaciers.indicator.10-03-17.clean.docx)

**Comment by amruelama** [comment]
https://data.globalchange.gov/report/indicator-arctic-glacier-mass-balance-2016
Updated on stage and pushed to prod by @lomky.
Reviewed by @rasherman.
