### ISSUE TITLE
Add countries to organizations

### ISSUE THREAD

**Issue by amruelama** [USGCRP/gcis#562]
- [x] Research countries for organizations
- [x] Update in this [spreadsheet](https://docs.google.com/spreadsheets/d/1W1nRCjKilhO1EeMWjrjB3BEHHogQwv63FQWk8kHzSYc/edit#gid=0)
- [x] Review
- [x] Update on stage
- [x] Review on stage before pushing to prod

**Comment by amruelama** [comment]
@lomky Could you update these countries on stage?

**Comment by lomky** [comment]
@amruelama working on this today

**Comment by lomky** [comment]
Done.

Script input & output attached as record.

[gcis_562.tar.gz](https://github.com/USGCRP/gcis/files/1600825/gcis_562.tar.gz)

**Comment by amruelama** [comment]
@lomky Thanks! 
Review done. Good to go to prod!

**Comment by amruelama** [comment]
Updates are now on prod.
