### ISSUE TITLE
CSSR publication/references QA

### ISSUE THREAD

**Issue by rasherman** [USGCRP/gcis#564]
This ticket is for collecting issues with the references and child publications for CSSR here. They'll be listed in a task list so anyone who does a fix can check it off, so we don't duplicate effort.

- [x] Confused about [this reference](https://data-stage.globalchange.gov/reference/3bae2310-7572-47e2-99a4-9e4276764934). It looks like CSSR is referencing a CSSR chapter? This doesn't seem correct.
- [x] References to [this publication](https://data-stage.globalchange.gov/article/10.1175/BAMS-D-13-00085.1) and [this publication](https://data-stage.globalchange.gov/article/10.1175/bams-d-13-00085.1) should be consolidated and the record describing the full report, not a section within.
- [x] Reference to [this publication](https://data-stage.globalchange.gov/article/10.1175/2015BAMSStateoftheClimate.1) should instead go to the [full parent report](https://data-stage.globalchange.gov/report/bams-state-of-the-climate-2014).

**Comment by amruelama** [comment]
[Here](https://docs.google.com/spreadsheets/d/1ACYZwAZ-k42aGVJ5mdnfTs841Mv6I7oAH3RVnkUtZGs/edit#gid=0) is the list of child publications that had title mismatches with references generated by @lomky . We can resolve this issue by either keeping the chapter (article) of the report with its reference and link all other chapters to it's parent report or delete all the chapter articles and link all the references to their parent report. @rasherman Let me know what you think.
For the CSSR references that's referencing CSSR chapters, we will remove or unlink the child publications but keep the references for future.

**Comment by amruelama** [comment]
Child Publications referenced to their own chapters have been unlinked.

**Comment by rasherman** [comment]
There were actually not that many mis-identified child publications. Most title mismatches were just difference in capitalization or other formatting. I re-assigned the ones that were to a section of a report to link to the full report, as you can see in the above spreadsheet.

I believe all references are done in GCIS, unless there are new changes.
