### ISSUE TITLE
Breakout IPCC Reports by Chapter

### ISSUE THREAD

**Issue by lomky** [USGCRP/gcis#565]
While we normally reserver chapter breakdown for our USGCRP reports, the IPCC reports are so often cited by chapter in our USGCRP reports that it would be helpful to have the chapters available.

We should process this based on the most cited reports first.

Chapters PDFs can be found on the IPCC site. [AR5](http://ipcc.ch/report/ar5/index.shtml)

**Comment by lomky** [comment]
I believe the process here looks like:

 - Create chapters under a given report
 - Check each reference that has the given report as its child report
    - if it should point to a chapter, change the child publication to the appropriate chapter
    - if it should point to the report, leave it be

**Comment by amruelama** [comment]
[Working sheet](https://docs.google.com/spreadsheets/d/1p9zWPlWF8BB5dD9FLsxCHfgNydX8Gu-eSvFEmQsUHSs/edit#gid=0) - List of IPCC Reports in GCIS

**Comment by amruelama** [comment]
@rasherman For some of these reports, there are more appendices than chapters. Since we are adding IPCC chapters for reference purpose, do we still need to add front matter, appendices, annexes? Do you think, anything except chapters of these reports will have references?

**Comment by amruelama** [comment]
@lomky is currently moving Part B chapters from [IPCC AR5 WG2 Part A](https://data-stage.globalchange.gov/report/ipcc-ar5-wg2-parta) to [IPCC AR5 WG2 Part B](https://data-stage.globalchange.gov/report/ipcc-ar5-wg2-partb). Refer to issue #580

**Comment by amruelama** [comment]
Created chapters and linked with references. Could you review this @rasherman?

**Comment by amruelama** [comment]
The chapters are already pushed to prod. Can we close this issue @rasherman?

**Comment by rasherman** [comment]
Whoops. I QA'd this and neglected to close the ticket (didn't find any errors). Thanks for doing this and for the nudge.
