### ISSUE TITLE
Add contributors for CSSR child publications

### ISSUE THREAD

**Issue by amruelama** [USGCRP/gcis#566]
- [x] QA [CSSR reference child publications](https://docs.google.com/spreadsheets/d/1Fl3zbIkp22YQtieMFcnCSTblY-DDwsipdXCAEKc7nfw/edit#gid=0)
- [x] Populate it with contributors. If required add new person and organizations with their info in GCIS.

**Comment by R-Aniekwu** [comment]
Hey Amrutha,

I have carefully looked through issue #566 that you assigned to me on
Github and I have a faint idea of what I am supposed to do. However, I
would still require some clarification on the variables. In one of the
examples you left for me, you indicated that the publication did not
require contributors. But the publication had authors. Do authors and
contributors mean the same thing? Do you want me to start on #566 right
away?

I hope you enjoy your trip to Australia.

Best regards,
Reuben.

**Comment by amruelama** [comment]
@lomky Can you please give stage access to @R-Aniekwu? He will be adding contributors directly on stage going forward.

**Comment by amruelama** [comment]
Completed except for ones that are low priority (129 articles). Populated both manually and by [script](https://github.com/USGCRP/gcis-scripts/tree/master/populating_scripts/by_resource/contributors/bulk-create-contributors)
