### ISSUE TITLE
Add CSSR Activities

### ISSUE THREAD

**Issue by lomky** [USGCRP/gcis#571]
Create `Activities` for the CSSR Figures, Tables, etc.

**Comment by amruelama** [comment]
- [ ] Get data from 'Resources' and create a working sheet.
- [ ] Map metadata fields
- [ ] Add and relate activities on stage.
- [ ] Push to prod

**Comment by amruelama** [comment]
[Working sheet](https://docs.google.com/spreadsheets/d/1iKCsK8GOSFEaK6j8McITiD9iOWnkLC58gw8aLUnkgnQ/edit#gid=1556185414)
Currently, there are 78 activities for 29 figures in CSSR.

**Comment by amruelama** [comment]
Completed and pushed to data-prod
