### ISSUE TITLE
Add Metadata to CSSR Generic Publications

### ISSUE THREAD

**Issue by lomky** [USGCRP/gcis#572]

**Comment by amruelama** [comment]
Here are the two generic type CSSR references:
1. [reference : Methane hydrates and contemporary climate change](https://data-stage.globalchange.gov/reference/2c02216d-911a-4cd2-ad19-71ed167979c9) (Electronic Article)
2. [ reference : Decoupling of global emissions and economic growth confirmed](https://data-stage.globalchange.gov/reference/2d0ddf02-9d2a-4eb9-8e29-3985db93c5ca) (Press Release)

@lomky Is it possible for us to add new fields as required (like you created for editable reference attributes #431)? Or can you make that happen? I'm note sure how they added fields for other generics added previously. Ex: https://data-stage.globalchange.gov/generic/1407e88b-fc71-4226-beff-71b0ea34f078

**Comment by lomky** [comment]
@amruelama I'm a bit confused. Are we talking about the `generic` objects or the `reference` objects?

**Comment by amruelama** [comment]
@lomky I wanted to copy the 'bibliographic fields' of a reference to the 'fields' of a generic (if editable).

**Comment by lomky** [comment]
Understood! I can make editable `generic` `attr`s happen for the next release.

**Comment by amruelama** [comment]
Updated the above two generic items with its fields and metadata as 'generic' type resources are now editable.
