### ISSUE TITLE
Figure Population for the Multi-Model Framework for Quantitative Sectoral Impacts Analysis Report

### ISSUE THREAD

**Issue by lomky** [USGCRP/gcis#577]
Populating the Figure data for the Multi-Model Framework for Quantitative Sectoral Impacts Analysis report in GCIS

[Working sheet](https://docs.google.com/a/usgcrp.gov/spreadsheets/d/1J-ef8GColtEVi0zWwC9DE3YWPjmC2YFz2U6XdH75peY/edit?usp=sharing)

**Comment by lomky** [comment]
Data populated in stage. Ready for QA by @rasherman

**Comment by lomky** [comment]
Removed the PDF from GCIS directly.

@rasherman let me know when the report is otherwise ready to go and I'll update the identifier.

**Comment by amruelama** [comment]
Figures are now on prod. Is this completely done @lomky

**Comment by rasherman** [comment]
Yep, closing this ticket. Good work, team!
