### ISSUE TITLE
Display chapter references cited by other publications on chapter page of the report

### ISSUE THREAD

**Issue by amruelama** [USGCRP/gcis#579]
Currently GCIS doesn't display the publications that cites chapters on 'chapter' page.
Ex: [Chapter 2](https://data.globalchange.gov/report/ipcc-ar5-wg1/chapter/wg1-ar5-chapter02-final) of [Climate Change 2013: The Physical Science Basis](https://data.globalchange.gov/report/ipcc-ar5-wg1) report is cited by [9 publications](https://data-stage.globalchange.gov/report/ipcc-ar5-wg1/chapter/form/update_prov/wg1-ar5-chapter02-final) that doesn't show up in the chapter front page. Displaying the 'cited by' publication references would be useful.

**Comment by lomky** [comment]
@amruelama Done! See data-review: https://data-review.globalchange.gov/report/nca3/chapter/our-changing-climate

**Comment by amruelama** [comment]
Looks good @lomky! Thanks. What is the current sort order for references? Can we sort this by chapter number and then ordinal? Is there a way to differentiate two different indicators by year since we have the same title for indicators of different years?

**Comment by lomky** [comment]
It is randomly sorted (reference a couple times and you'll see it). The sub-references sort Chapter->Figure->Finding->Table.

Looking into how hard the differentiation would be

**Comment by lomky** [comment]
@amruelama it's not easy to get at the year in this location.

**Comment by amruelama** [comment]
@lomky No problem. This looks fine!
