### ISSUE TITLE
Watch Page - Allow Selections by To/From Dates

### ISSUE THREAD

**Issue by lomky** [USGCRP/gcis#584]
The watch details & watch summary pages only allow queries relative to now or the last x queries. It would be useful to be able to specify the Start & Stop dates.

**Comment by lomky** [comment]
@amruelama @R-Aniekwu  how does this look?

<img width="1038" alt="screen shot 2018-04-20 at 9 50 02 am" src="https://user-images.githubusercontent.com/6129479/39054664-3b69e378-4480-11e8-91a1-b436542de573.png">

**Comment by lomky** [comment]
@amruelama would it be good if we replaced all of the free text date fields with these date or datetime selector types?

**Comment by amruelama** [comment]
This is awesome! 

What are the examples of other free text date fields?

**Comment by lomky** [comment]
@amruelama anywhere we have the "created" "submitted" or "updated" on objects that expect a datetime. I don't plan on doing it immediately but I can file another ticket for that if it'd be helpful

**Comment by lomky** [comment]
@amruelama you can see this live on data-review now!

Try it out in various browsers to see how it looks in each (the screenshot is firefox, but it looks different in chrome, safari, etc)

**Comment by lomky** [comment]
Filed #609 for that followup.

**Comment by amruelama** [comment]
Calendar option works in Firefox. I had to update the browser.

**Comment by lomky** [comment]
It looks to me like it works:

  - Date Fields:  
    - Firefox
    - Chrome
  - Datetime Fields:
    - Chrome
  - Falls back to Text (no worse than today) 
    - Safari
    - IE
    - Firefox (datetime only)
