### ISSUE TITLE
Handle special characters

### ISSUE THREAD

**Issue by amruelama** [USGCRP/gcis#586]
Example 1 : When an organization with special character(s) is added as an org title, the automatically generated identifier ignores the special characters.
Example 2: Person name with special character(s) is currently hard to find using the search query unless the last name or first name doesn't have special characters in it. 

We should either teach the system to handle special characters or ignore using them to avoid redundancy.

**Comment by amruelama** [comment]
@lomky Can you look into this?

**Comment by lomky** [comment]
@amruelama Can you link me a couple examples for these two cases?

**Comment by amruelama** [comment]
Case 1 : https://data.globalchange.gov/organization/universite-de-montral 
Case 2 : https://data.globalchange.gov/person/15690

**Comment by lomky** [comment]
For Case 1: Organization Identifiers:

I think this is the right way to go, long term, with regards to identifiers, but we should probably make the change to all title-based identifiers rather than just organization. We should discuss the affected objects and any implications on automated scripts, and then move forward with it.

**Comment by lomky** [comment]
For Case 2: Person Accent Insensitive Search

This is possible, but we would need to extend our PostgreSQL database with a module and then propogate that through search & autocomplete functionality in GCIS. https://stackoverflow.com/questions/11005036/does-postgresql-support-accent-insensitive-collations

**Comment by amruelama** [comment]
- [ ] Organization search issue resolved [#99](https://github.com/USGCRP/gcis_rails/issues/99) 
- [ ] Name search is still an issue.

**Comment by zacharylandes** [comment]
@amruelama can you give an example of name search still being an issue? Thanks

**Comment by amruelama** [comment]
@zacharylandes Type **Gutiérrez** here - https://data.globalchange.gov/person
![image](https://user-images.githubusercontent.com/18075324/182904475-ae6cad04-2a65-4f9a-882c-db2c23600d75.png)
and 
https://data.globalchange.gov/search?query=Guti%C3%A9rrez
![image](https://user-images.githubusercontent.com/18075324/182904625-5db8d1a4-84be-4e62-8caf-8c3267ceeafe.png)

**Comment by zacharylandes** [comment]
<img width="257" alt="Screen Shot 2022-08-15 at 9 12 51 AM" src="https://user-images.githubusercontent.com/13617379/184673028-271fd20e-3852-40a3-b374-415097f63f66.png">
@amruelama please verify updates thanks

**Comment by amruelama** [comment]
@zacharylandes Autocomplete works. Still having issues with search. Please see above 
https://data-dev.globalchange.gov/search?query=Guti%C3%A9rrez

**Comment by zacharylandes** [comment]
@amruelama please verify updates on the above link ^ thanks

**Comment by amruelama** [comment]
Looks good on dev
