### ISSUE TITLE
2018 indicators

### ISSUE THREAD

**Issue by amruelama** [USGCRP/gcis#587]
Indicators list:

- [x] [Frost free season](https://data.globalchange.gov/report/indicator-frost-free-season-2018) 
- [x] [Heavy Precipitation](https://data.globalchange.gov/report/indicator-heavy-precipitation-2018)
- [x] [Arctic Sea Ice Extent](https://data.globalchange.gov/report/indicator-arctic-sea-ice-extent-2018)

**Comment by amruelama** [comment]
@rasherman Feel free to edit the above list as we receive updated indicators for this year.

**Comment by amruelama** [comment]
@lomky Could you review 'Arctic Sea Ice Extent 2018' on stage please?

**Comment by amruelama** [comment]
Indicators tracking sheet - https://docs.google.com/spreadsheets/d/1FOzQckt0nIV-9OpKvvtrs4yp1oLdyhOzFmh08sN5cjM

**Comment by lomky** [comment]
Looks good to me! 🎉

**Comment by amruelama** [comment]
- [ ] 1. [Annual Greenhouse Gas Index](https://data.globalchange.gov/report/indicator-annual-greenhouse-gas-index-2018)
- [ ] 2. [Sea Surface Temperature ](https://data.globalchange.gov/report/indicator-sea-surface-temperature-2018)
- [ ] 3. [Global Surface Temperatures](https://data.globalchange.gov/report/indicator-global-surface-temperature-2018) 
- [ ] 4. [Atmospheric Carbon Dioxide](https://data.globalchange.gov/report/indicator-atmospheric-carbon-dioxide-2018) 
- [ ] 5. [Heating and Cooling Degree Days](https://data.globalchange.gov/report/indicator-heating-and-cooling-degree-days-2018) 
- [ ] 6. [Start of Spring](https://data.globalchange.gov/report/indicator-start-of-spring-2018) 
- [ ] 7. [U.S. Surface Temperatures](https://data.globalchange.gov/report/indicator-us-surface-temperature-2018) 
- [ ] 8. [Sea Level Rise](https://data.globalchange.gov/report/indicator-sea-level-rise) 
- [ ] 9. [Ocean Chlorophyll Concentrations](https://data.globalchange.gov/report/indicator-ocean-chlorophyll-concentrations-2018) 
- [ ] 10. [Terrestrial Carbon Storage ](https://data.globalchange.gov/report/indicator-terrestrial-carbon-storage-2018)

**Comment by amruelama** [comment]
Done and pushed to production
