### ISSUE TITLE
Add 2018 filter on indicators page

### ISSUE THREAD

**Issue by amruelama** [USGCRP/gcis#588]
As we've started adding indicators for this year (#587), create '2018' filter button on indicators page - https://data.globalchange.gov/indicator

**Comment by lomky** [comment]
This is a good time to make this update dynamically based on the actual available publication years.

**Comment by amruelama** [comment]
Sounds good!

**Comment by lomky** [comment]
Done! Please review on data-review @amruelama. I created fake indicators as follows in the data-review db for testing purposes:

```
gcis=# INSERT INTO report
(identifier,title,report_type_identifier,publication_year)
VALUES
('test1999','Indicator for 1999','indicator',1999),
('test2018','Indicator for 2018','indicator',2018);
INSERT 0 2
```
```
gcis=# select * from report where report_type_identifier = 'indicator' and publication_year=2018;
 identifier |       title        | url | doi | _public | report_type_identifier | summary | frequency | publication_year | topic | in_library | contact_note | contact_email
------------+--------------------+-----+-----+---------+------------------------+---------+-----------+------------------+-------+------------+--------------+---------------
 test2018   | Indicator for 2018 |     |     | t       | indicator              |         |           |             2018 |       |            |              |
(1 row)
```

So now it looks like this on first navigation:
![screen shot 2018-02-07 at 11 07 49 am](https://user-images.githubusercontent.com/6129479/35926916-63a31290-0bf7-11e8-8c72-a61e9b7141ed.png)
And if you select `1999`:
![screen shot 2018-02-07 at 11 08 00 am](https://user-images.githubusercontent.com/6129479/35926917-63ad690c-0bf7-11e8-9fc9-8799439e87f8.png)

**Comment by amruelama** [comment]
Looks good @lomky
