### ISSUE TITLE
Enable One Author -> Multiple Orgs & Roles on Creation of Contributors

### ISSUE THREAD

**Issue by lomky** [USGCRP/gcis#594]
Allow to add up to five affiliations for an author at the same time. 
Currently we can add only one organization to a contributor. 

This way we don't have to add the same author 'n' times for 'n' affiliations of the same article or report. Make sure there's sort key option for each affiliation added for the author.

**Comment by amruelama** [comment]
Resolved by different method - option to create [many-many author-affiliation connection](https://data-stage.globalchange.gov/article/10.1007/s10584-015-1357-7/edit) under contributor page - [#99](https://github.com/USGCRP/gcis_rails/issues/99) by adding 5 rows at a time.
