### ISSUE TITLE
Create tool to assign GCMD keywords

### ISSUE THREAD

**Issue by rasherman** [USGCRP/gcis#596]
The NCA team has said that it doesn't matter if we do a GUI vs. spreadsheet for assigning keywords, so let's do whichever is easier (I'm assuming that's a spreadsheet template we can import by script).

Let's make a sample ready to show and demo it to the NCA staff in ~late April.

**Comment by lomky** [comment]
@rasherman which level are we going to work to? Topic?

```
Keyword Level       | Example
--                  | --
Category            | Earth Science
Topic               | Atmosphere
Term                | Weather Events
Variable Level 1    | Subtropical Cyclones
Variable Level 2    | Subtropical Depression
Variable Level 3    | Subtropical Depression Track
Detailed Variable   | (Uncontrolled Keyword)

 ```

**Comment by lomky** [comment]
This ticket has been broken into two parts, one in #604 for creating the CSV intake process, and #605 for creating a spreadsheet template the NCA staff can use. Closing this for those two work tickets.
