### ISSUE TITLE
Clean up formatting of GCIS front page

### ISSUE THREAD

**Issue by rasherman** [USGCRP/gcis#598]
The content on data.globalchange.gov is not cleanly displayed. The text block from "Featured USGCRP reports" through "API reference" appears to be offset to the right from the rest of the content on the page.

The formatting of the page should be checked and make sure things are centered or justified properly.

**Comment by lomky** [comment]
Formatting fixed for centering the Featured Reports. 

Also looking into fixing the responsiveness of the front page graphic (falls to the side when resized) and bringing the color scheme in line with USGCRP NCO Standards.

**Comment by lomky** [comment]
@rasherman I am considering adding a 'well' to the featured reports section for aesthetics. Which of these do you prefer?

**Plain**:
<img width="1050" alt="screen shot 2018-03-20 at 8 55 26 am" src="https://user-images.githubusercontent.com/6129479/37655755-86a9e3b4-2c1c-11e8-975e-db8b322114f6.png">

**Well**:
<img width="1102" alt="screen shot 2018-03-20 at 8 56 39 am" src="https://user-images.githubusercontent.com/6129479/37655795-9f87b4ba-2c1c-11e8-86df-f86e9570c5f9.png">

**Comment by rasherman** [comment]
The well is good, put that in there. Thanks!

**Comment by lomky** [comment]
SVG is solidly responsive at the moment at all sizes, it only weirds out on browser resize. Fixing it is more d3 intensive than I expected, so going to leave it be for now.

**Comment by lomky** [comment]
@rasherman can you prod data-review and tell me if the issues you ID'd are solved?

**Comment by rasherman** [comment]
Much better. Thanks so much!
