### ISSUE TITLE
Book QA Tasks

### ISSUE THREAD

**Issue by lomky** [USGCRP/gcis#600]
Followup from Conventions discussion: USGCRP/gcis-conventions#20

  - [x] Review Book entities to find things that would be better classified as another object. 
    - Namely Reports miscategorized as Books. Others are possible.
  - [x] Migrate Book `publisher` field to a Contributor with `publisher` role
    - Similar to previous process on Journals in #548

**Comment by lomky** [comment]
@R-Aniekwu Can you write here what has been done and what is the current status. Or link the ticket you did the work in?

**Comment by R-Aniekwu** [comment]
I reviewed 220 GCIS resources previously classified as "books", and reclassified them as, "Book"; "Report"; or "Unsure". This issue has been moved to review.
https://docs.google.com/spreadsheets/d/105jK10qTEtxqVXBxV9_Z_63HmPw1Q_zSyxpiR--Bpmc/edit#gid=689434811

**Comment by amruelama** [comment]
Needs QA for CSSR, NCA4 and SOCCR2

**Comment by R-Aniekwu** [comment]
Reviewed all 409 Books in GCIS, adding contributors (Authors, Editors, and Publishers) to more than 300 of them, as well as revising ISBNs and adding URLs when possible.
https://docs.google.com/spreadsheets/d/105jK10qTEtxqVXBxV9_Z_63HmPw1Q_zSyxpiR--Bpmc/edit#gid=850866345.
