### ISSUE TITLE
Offer CSV download for tables & arrays

### ISSUE THREAD

**Issue by lomky** [USGCRP/gcis#601]
Suggested to GCIS from feedback.

**Comment by lomky** [comment]
Looks like we want this functionality to uspport the NCA4 website as well. Tagging in @kjrhody

**Comment by lomky** [comment]
Arrays now offer a CSV option.

<img width="725" alt="screen shot 2018-04-27 at 3 10 52 pm" src="https://user-images.githubusercontent.com/6129479/39380626-3f4196fa-4a2d-11e8-9354-f3cc0b3bf078.png">

<img width="921" alt="screen shot 2018-04-27 at 3 11 35 pm" src="https://user-images.githubusercontent.com/6129479/39380649-4f56a580-4a2d-11e8-9ca0-8daf180f48cd.png">

@amruelama could you check this looks okay to you?

@kjrhody does this meet your needs for NCA4?

**Comment by amruelama** [comment]
@lomky Looks good to me!
