### ISSUE TITLE
GCMD Ingestion Template

### ISSUE THREAD

**Issue by lomky** [USGCRP/gcis#605]
We will be asking the NCA team to identify proper GCMD keywords for entities inside of the NCA4.  
To ensure consistency, we'd like to create a template spreadsheet to hand them to fill out.

### Outstanding Prior Questions:

  - What level of depth will we use from the GCMD keyword?
  - Which entities will we label inside of the NCA4?

### Fields:

  - The input script to GCIS will require the fields:
    - GCIS URI
      - probably added later by GCIS team based on NCA provided report id+chapter id+entity id
    - GCMD Keyword UUID
      - probably added later via lookup on NCA provided GCMD Keyword name
    - Entity Type
      - provided by NCA team
  - The NCA4 Team will need to fill in the fields:
    - Chapter ID
    - Entity ID
    - Entity Type
    - GCMD Keyword Name

### Extra Thoughts:
  - Having a dropdown selection for the NCA4 team fields would be nice

**Comment by lomky** [comment]
Setting this ticket aside as a good intro task for the NCA intern.

**Comment by lomky** [comment]
The script that will ingest this spreadsheet was developed in #604, see [README](https://github.com/USGCRP/gcis-scripts/tree/master/populating_scripts/by_data/associate_resources_with_gcmd_keywords)

**Comment by lomky** [comment]
Might be worth exploring the CSSR and seeing which level of keywords applying makes sense. Our current thought is two levels below Earth Science.

**Comment by lomky** [comment]
@vjoleary could you please link the finished template here and we'll close this out as complete! 👍

**Comment by vjoleary** [comment]
The template is found in Google Drive and linked here https://drive.google.com/file/d/0Bzme6qGkaz54SzZXM0hJV2VHRlRobjdWSkNpdFpYQ2lUNDQw/view?usp=sharing
