### ISSUE TITLE
Clean up organization types

### ISSUE THREAD

**Issue by amruelama** [USGCRP/gcis#606]
[Working sheet](https://docs.google.com/spreadsheets/d/1c-tvNHdBM52WA-EgGedV36Ug24_l7DHRN7R5T4AMn7I)

**Comment by amruelama** [comment]
@rasherman Could you review this?

**Comment by rasherman** [comment]
Current plan:

We will stay up to date on progress of CrossRef and ROR on classifying and registering organizations. If they develop a schema or lexicon for organization types that GCIS should copy, then we can adopt and reference external metadata.

In the meantime, we will reduce our organization types to six for future tagging:
-Government
-Academic/Research
-Intergovernmental
-Commercial
-Non-profit
-Academic/federal (cooperative agreement)

**Comment by amruelama** [comment]
Updated types. [#99 ](https://github.com/USGCRP/gcis_rails/issues/99)
