### ISSUE TITLE
Return all GCMD keywords in single page option

### ISSUE THREAD

**Issue by amruelama** [USGCRP/gcis#611]
This URL should return all 3000+ GCMD keywords available - https://data-stage.globalchange.gov/gcmd_keyword?all=1
But currently it returns only 20+. Please fix this.

**Comment by lomky** [comment]
Is it sufficient to ask for a per_page large enough to get all?

warning, slow load: https://data-stage.globalchange.gov/gcmd_keyword?per_page=3000

**Comment by amruelama** [comment]
This is good. Thanks @lomky
