### ISSUE TITLE
[NCA4] Release: Chapter Creation

### ISSUE THREAD

**Issue by lomky** [USGCRP/gcis#616]
Initial `Chapter` creations will be done via the sync system. Further data should be done by hand.

### Process

  - Add Chapter data (final)
  - Add Contributors
  - Add Chapter pdf
  - DOI Minting

### Chapters

  - Overview [Executive Summary]
  - Our Changing Climate [NCA4 Vol. I summary]
  - Topic: Water
  - Topic: Energy Supply, Delivery, & Demand
  - Topic: Land Cover & Land Use Change
  - Topic: Forests
  - Topic: Ecosystems, Ecosystem Services, & Biodiversity
  - Topic: Coastal Effects
  - Topic: Oceans & Marine Resources
  - Topic: Agriculture & Rural Communities
  - Topic: Built Environment, Urban Systems, & Cities
  - Topic: Transportation
  - Topic: Air Quality
  - Topic: Human Health
  - Topic: Tribes & Indigenous Peoples
  - Topic: Climate Effects on US International Interests
  - Topic: Sector Interactions, Multiple Stressors, and Complex Systems
  - Region: Northeast
  - Region: Southeast
  - Region: US Caribbean
  - Region: Midwest
  - Region: Northern Great Plains
  - Region: Southern Great Plains
  - Region: Northwest
  - Region: Southwest
  - Region: Alaska
  - Region: Hawai`i & Pacific Islands
  - Response: Near-term Adaptation Needs & Increased Resiliency
  - Response: Reducing Risks through Emissions Mitigation
  - Appendix: Process
  - Appendix: Information Quality Act
  - Appendix: Data Tools & Scenario Products
  - Appendix: International Context
  - Appendix: Frequently Asked Questions

TSU Partner Ticket: N/A
Related CSSR Ticket: N/A

**Comment by lomky** [comment]
All the chapters exist!
https://docs.google.com/spreadsheets/d/1-zHQdD-ZWUJeupdE0l-XQ8uwdwi9ljlwIM2HO6pnf_0/edit#gid=0

**Comment by amruelama** [comment]
- [ ] DOI Minting
- [ ] Report and Chapter contributors (In progress)

**Comment by amruelama** [comment]
@rasherman or @lomky Can you QA report and chapter contributors when you get a chance?

**Comment by lomky** [comment]
DOI QA'd with one URL question. 

I QA'd chapter 1's contributors. Feel free to tag me in the sheet as chapters are completed!

**Comment by lomky** [comment]
Marking complete. PDF will be handled in #676
