### ISSUE TITLE
[NCA4] Prep: Diff References 

### ISSUE THREAD

**Issue by lomky** [USGCRP/gcis#623]
After the 4OD references are finalized, run the endnote import and meet with TSU to resolve any differences between existing GCIS references and their counter-parts in the EndNote.

TSU Partner Ticket: N/A
Related CSSR Ticket: #500

**Comment by lomky** [comment]
[Working Sheet](https://docs.google.com/spreadsheets/d/1DQyblAfz0eLDy--VkLbWYtDuScU1kJN2YHpvp73qE0c/edit?pli=1#gid=1337081332)

Moving forward, work is divvied up accoridng to column M

TSU:  
  - Update EndNote
  - Mismatch UUID
  - Update Both

Amrutha:  
  - Update GCIS
  - Update Both

Kat:  
  - Script Issue
  - Update GCIS via Script

**Comment by amruelama** [comment]
Updates done in GCIS!

**Comment by lomky** [comment]
TSU reports their differences are also done!
