### ISSUE TITLE
[NCA4] Post Release: References Child Publication Creation - Manual

### ISSUE THREAD

**Issue by lomky** [USGCRP/gcis#626]
Once the References have been populated  #622 and the automated Child Publication generated  #625, manually populate the child publications for those that remain.

TSU Partner Ticket: N/A
Related CSSR Ticket: #501

**Comment by amruelama** [comment]
[Working sheet](https://docs.google.com/spreadsheets/d/1N4ADhK8cf9MSTrcmVMe2b2V5i1ZbNvPSs5UqeuppY8s)

**Comment by amruelama** [comment]
All the references of NCA4 (5608) should now have child publications
