### ISSUE TITLE
[NCA4] Post Release: Activity QA & Linking

### ISSUE THREAD

**Issue by lomky** [USGCRP/gcis#629]
Note: Depending on progress we make with improving the GDAS<->GCIS sync system, these might come in automatically with the Figure sync. This ticket is in case that does not happen.

Create `Activity`s for the NCA4 `Figure`s, `Table`s, etc.

TSU Partner Ticket: N/A
Related CSSR Ticket: #571

**Comment by lomky** [comment]
This looks like it will now consist of two steps:

  1. For Created & Autolinked activities 
     - QA
  1. For Created orphan activities:
    - Find / Create source publication based on Activity Note
    - Connect activity to source publication
    - Clear Activity Note

**Comment by R-Aniekwu** [comment]
Link: https://docs.google.com/spreadsheets/d/195xb8I7nRXdtNu8kmxHaPBbQcHiC9p2iL47x96Hj98Q/edit#gid=0

**Comment by R-Aniekwu** [comment]
Only 10 auto-linked activities (with images).

**Comment by lomky** [comment]
We realized some of this work is best to do after Figures are final-sync'd from TSU. Otherwise we end up working with Image UUIDs that are replaced.

**Comment by amruelama** [comment]
Completed and pushed to data-prod. See sheet 'Consolidated activities'
