### ISSUE TITLE
URL checker response codes and redirection 

### ISSUE THREAD

**Issue by amruelama** [USGCRP/gcis#637]
Here are the list of changes to be done in URL checker to improve the QA process. 

- [ ] Redirect URLs for some 301s gives 404 or 'page not found' response- https://data-stage.globalchange.gov/report/nycpanelonclimch-cri2013
- [ ] Check the response of URLs redirected from a DOI URL.

**Comment by lomky** [comment]
Work can be done under #635 Thanks!
