### ISSUE TITLE
Planning: 2018 Summer Metrics Work

### ISSUE THREAD

**Issue by lomky** [USGCRP/gcis#640]
We know we want to do some improvements to the GCIS Metrics. TBD

**Comment by rasherman** [comment]
We need to move the GCIS metrics forward this summer on three fronts:

1. Run the existing script to score more chapters of NCA3, CSSR, and CHA to build some statistics and analyze how we've improved on reports and where the weaknesses still are.
2. Develop a scoring scheme for connection metrics (that is, is a record connected to things that enhance provenance information).
3. Determine how we should incorporate these scores into the public GCIS records, if at all.

Task 1 needs some set-up from Kat, but should largely be done by Amrutha and Reuben. Task 2 should be done by Amrutha, with support from the rest of the team. Task 3 is a job for Kat and I to discuss first and bring to others.

Would it be easier if I separate these into three tickets?

**Comment by R-Aniekwu** [comment]
It will not be a bad idea to compartmentalize a bit, since it is somewhat
of a bulky project.

**Comment by lomky** [comment]
> Would it be easier if I separate these into three tickets?

That sounds good to me! Let's finish any other work we have to refine the tasks here (if any), then create the three new tickets and close this as a completed planning task?

**Comment by rasherman** [comment]
Ok, I'll handle the refining and writing of the new tickets, so I'll un-assign you guys, and then re-assign to the new tickets when I do that later today.

**Comment by rasherman** [comment]
This ticket has been expanded into ticket #643 #644 and #645
