### ISSUE TITLE
Add missing publishers for journals

### ISSUE THREAD

**Issue by amruelama** [USGCRP/gcis#641]
[Working sheet](https://docs.google.com/spreadsheets/d/16aUzOnIuncxEAD7zieaBGpxf2GK9UW4lZ3836XamK0k)

**Comment by R-Aniekwu** [comment]
Created publisher roles for journals without publishers. Created new publishers (new organizations) for journals already in GCIS in the case that these publishers did not exist prior - including affiliations with other organizations where needed.
https://docs.google.com/spreadsheets/d/16aUzOnIuncxEAD7zieaBGpxf2GK9UW4lZ3836XamK0k/edit#gid=0
