### ISSUE TITLE
Add Existing DOI Metadata into CrossRef

### ISSUE THREAD

**Issue by lomky** [USGCRP/gcis#649]
We are moving our DOI management over to CrossRef from EZID. 

Process:
  - [ ] Migrate the existing DOIs
    - [ ] Confirm the DOIs resolve properly via CrossRef
  - [ ] Migrate the existing DOI Metadata 
    - [x] Download the EZID data as [Datacite XML format](https://schema.datacite.org/).
    - [ ] Convert into the [CrossRef XML format](https://support.crossref.org/hc/en-us/articles/214169586-Metadata-deposit-schema) for depositing DOI metadata.
    - [ ] Upload to [CrossRef](https://support.crossref.org/hc/en-us/articles/214960123)

**Comment by lomky** [comment]
So my suggestion for approaching this project would be:

 - decide on your language for the script (python? 2 or 3?)
 - find Python modules for Datacite & CrossRef (these modules' compatibility may affect your python 2 vs 3 version choice) 
 - write out a skeleton script for reading in, translating, and uploading the changes
 - flesh out the reading in section using the Datacite module to convert the data into python objects
 - flesh out the translation section to get things formatted for CrossRef
 - flesh out the upload section for adding the info to CrossRef using the CrossRef module.

**Comment by lomky** [comment]
Due to time limitations, we are just doing this manually rather than scripting it.

**Comment by amruelama** [comment]
[Working sheet](https://docs.google.com/spreadsheets/d/1fPhzmwV0du3OSFzS2eBxaN2tEto6QXBqh8uQG_f-uoA/edit#gid=203965672)

**Comment by amruelama** [comment]
Re-registration done.
