### ISSUE TITLE
QA FFRDCs in GCIS

### ISSUE THREAD

**Issue by amruelama** [USGCRP/gcis#653]
- [x] Create a list of FFRDCs in GCIS 
- [x] Compare the list with the available FFRDCs in the U.S. - https://www.nsf.gov/statistics/ffrdclist/
- [x] Update and edit the organization types in GCIS of these organizations accordingly. 
- [x] Push the updates to prod

Process:
Downloaded the entire list of FFRDCs originally in GCIS and compared it to the U.S. Master list of FFRDCs. "Organization type" for U.S. and foreign organizations in the GCIS FFRDC list was updated accordingly.
https://docs.google.com/spreadsheets/d/11EsysBYh4CIkJ3JvlP28P3FNPpgcNtOgW9B0tvZqgSc/edit#gid=1577373072

**Comment by R-Aniekwu** [comment]
Process:
Downloaded the entire list of FFRDCs originally in GCIS and compared it to the U.S. Master list of FFRDCs. "Organization type" for U.S. and foreign organizations in the GCIS FFRDC list was updated accordingly.
https://docs.google.com/spreadsheets/d/11EsysBYh4CIkJ3JvlP28P3FNPpgcNtOgW9B0tvZqgSc/edit#gid=1577373072
