### ISSUE TITLE
Display automatically generated id for 'activity'

### ISSUE THREAD

**Issue by amruelama** [USGCRP/gcis#658]
Display the automatically generated identifier by default before creating an activity, in order to edit and update the identifier according to activity convention. The current process is to create an activity first and then edit/update the identifier to match the convention.

**Comment by lomky** [comment]
To get a UUID before submitting the activity you can query https://data.globalchange.gov/uuid?count=50 with the count set to whatever number you need. I'd rather not set the fill with UUID as the default since that is our last preference for the name of an activity
