### ISSUE TITLE
References for manually created publications in GCIS

### ISSUE THREAD

**Issue by amruelama** [USGCRP/gcis#669]
Currently references are either synced or added by script. In very rare cases, we might be adding reference by hand. Should we think about the cases where we create these reference types (child publications) manually and adding their references while doing so? The best example would be indicators. Do we need references for indicators assuming that they might be referenced in future reports? Another example would be external reports in GCIS like CIRA, Multi-Model Framework for Quantitative Sectoral Impacts Analysis and any other technical report we create in GCIS. 

This could be a part of 'reference' convention in GCIS

Thoughts? @rasherman @lomky

**Comment by lomky** [comment]
I would want to seek TSU's input in creating the reference, to maximize our ability to match what will appear in future reports. Definitely would want some sort of unique identifier (DOI, PMCID, ISBN, etc).
