### ISSUE TITLE
[NCA4 Release] New Regions

### ISSUE THREAD

**Issue by lomky** [USGCRP/gcis#670]
## New Regions

 - `Southeast`
   - Consists of Alabama, Arkansas, Florida, Georgia, Kentucky, Louisiana, Mississippi, North Carolina, South Carolina, Tennessee, and Virginia
 - `U.S. Caribbean`
   - Consists of Puerto Rico and the U.S. Virgin Islands
 - `Northern Great Plains`
   - Consists of Montana, Nebraska, North Dakota, South Dakota, and Wyoming
 - `Southern Great Plains`
   - Consists of Kansas, Oklahoma, and Texas

**Comment by amruelama** [comment]
1. [Southeast](https://data-stage.globalchange.gov/region/southeast)
2. [U.S. Caribbean](https://data-stage.globalchange.gov/region/us-caribbean)
3. [Northern Great Plains](https://data-stage.globalchange.gov/region/northern-great-plains)
4. [Southern Great Plains](https://data-stage.globalchange.gov/region/southern-great-plains)

**Comment by amruelama** [comment]
Added 10 NCA4 regions here - https://data-stage.globalchange.gov/report/nca4. Needs review and a bug fix #671

**Comment by lomky** [comment]
Looks good!
