### ISSUE TITLE
List of regions listed under a report linked to only one region on stage

### ISSUE THREAD

**Issue by amruelama** [USGCRP/gcis#671]
*This bug is just on stage. Prod works fine.*

Click "10 regions" under [nca1](https://data-stage.globalchange.gov/report/nca1) report page and it redirects to northeast-us instead of all available regions. This needs to be QAed and fixed for all reports. 

@lomky I wonder why stage is different from prod. Is this a recent implementation?

**Comment by lomky** [comment]
Great catch! I'll investigate as soon as I'm back on my feet.
