### ISSUE TITLE
500 error on 'nca4-tribal_lands_northerngreatplains_v2-process' activity

### ISSUE THREAD

**Issue by amruelama** [USGCRP/gcis#681]
Internal server error to access activity page - [nca4-tribal_lands_northerngreatplains_v2-process](https://data.globalchange.gov/activity/nca4-tribal_lands_northerngreatplains_v2-process)

**Comment by lomky** [comment]
It had a bad value stored in the `spatial_extent` field. I removed it and now it works. Next content push will fix prod.
