### ISSUE TITLE
Generic type improvements

### ISSUE THREAD

**Issue by amruelama** [USGCRP/gcis#689]
- [ ] Finding generic duplicates
- [x] Create URL hyperlink
- [x] Display contributors
- [ ] ~Adding multiple fields while creating new generic~

**Comment by lomky** [comment]
Going to *not* implement multiple fields on new generic for now. It's a relatively large lift. Our use case for Generics creates them exclusively for References as child publication, which has an [automated script](https://github.com/USGCRP/gcis-scripts/tree/master/populating_scripts/by_resource/generics/create_generic_from_reference). 

If we ever need to create a large group of Generics outside of Reference child publications, we should revisit this task.
