### ISSUE TITLE
Have Report Automatically Add URL as a Remote File

### ISSUE THREAD

**Issue by amruelama** [USGCRP/gcis#690]
Improve report creation script to automatically add a remote file if a URL is given or updated, which will create thumbnails in report front page.

**Comment by lomky** [comment]
@amruelama is it important that this is for the automated process, or would it be good to have for any report created? I'm thinking the process looks like:

 1. create a Report that has a URL
 1. automatically add the remote file

**Comment by amruelama** [comment]
@lomky I was thinking we can automatically create thumbnails from the URL that has .pdf, .jpg/.jpeg. .gif extensions.
