### ISSUE TITLE
Unable to create table from chapter table page

### ISSUE THREAD

**Issue by amruelama** [USGCRP/gcis#694]
Table can be created  via "report/table/form/create" but not from "report/chapter/2/table/form/create"

ERROR: insert or update on table "table" violates foreign key constraint "table_chapter_identifier_fkey" DETAIL: Key (chapter_identifier, report_identifier)=(2, second-state-carbon-cycle-report-soccr2-sustained-assessment-report) is not present in table "chapter". at /home/gcisops/perl5/perlbrew/perls/perl-5.20.3/lib/site_perl/5.20.3/Rose/DB/Object.pm line 1182.

**Comment by lomky** [comment]
@amruelama that's because `/chapter/2` is a shortcut to the real chapter, `/chapter/the-north-american-carbon-budget`. You need to go to the real address to create subobjects.
