### ISSUE TITLE
Content quick fixes

### ISSUE THREAD

**Issue by rasherman** [USGCRP/gcis#697]
We received an e-mail with some possible errors on GCIS resources. See attached table.

[gcis_resource_updates.pdf](https://github.com/USGCRP/gcis/files/2980454/gcis_resource_updates.pdf)

**Comment by lomky** [comment]
We probably need to alert folks before changing the CSSR figure, as its published on the web report. It might need to be put into an errata?

**Comment by R-Aniekwu** [comment]
The thumbnail for the NAS book could not be retrieved remotely. I had to download the book and upload it to the GCIS, and when I did so, the thumbnail was different from the one on the NAS website.
<img width="930" alt="GCIS_697" src="https://user-images.githubusercontent.com/32877335/54613386-fde46480-4a30-11e9-9383-597a0713d09b.PNG">

**Comment by R-Aniekwu** [comment]
...I have deleted the file.

**Comment by amruelama** [comment]
We should not download and re-upload a file from an external source. Alternatively, we can retrieve a file from remote location using their URL that directs to the location of the PDF file.

**Comment by R-Aniekwu** [comment]
Understood. I tried that, but it did not work both issues concerned with thumbnails. 
<img width="916" alt="gcis_679_2" src="https://user-images.githubusercontent.com/32877335/54614086-35074580-4a32-11e9-9d07-0edc3f398710.PNG">

**Comment by amruelama** [comment]
Here is the thumbnail link for book [Climate Intervention: Reflecting Sunlight to Cool Earth](https://data.globalchange.gov/book/6d3eb0d6-568a-40d3-9b10-393f943038da) - https://www.nap.edu/cover/18805/450.jpg

**Comment by R-Aniekwu** [comment]
All the corrections have been made.

**Comment by amruelama** [comment]
Changes pushed to prod.
