### ISSUE TITLE
Extensive GCIS Activity QA

### ISSUE THREAD

**Issue by R-Aniekwu** [USGCRP/gcis#698]
Research, review and hopefully, relate orphaned activities to other GCIS publications. https://docs.google.com/spreadsheets/d/152hIwMC1BX3obF1g2oQLMaUWEYFRTn8_fVmTbA_vA0U/edit#gid=0

**Comment by R-Aniekwu** [comment]
A total of 1324 GCIS activities have been downloaded onto a google sheet (https://docs.google.com/spreadsheets/d/152hIwMC1BX3obF1g2oQLMaUWEYFRTn8_fVmTbA_vA0U/edit#gid=0). This task is on-going.

Observed issues:
- Many orphaned activities are duplicates - for almost every "related" nca3 activity, there are about 2 duplicates.

- The history of some nca3 activities, particularly the duplicates, can not be viewed.

**Comment by amruelama** [comment]
Priority order:

- [ ] NCA4
- [ ] CSSR
- [ ] NCA3
- [ ] SOCCR2
- [ ] Indicators
- [ ] State Summaries 2019
- [ ] State Summaries 2017
- [ ] Other

**Comment by amruelama** [comment]
- Good - 885
- Created publication and linked - 6
- Linked with publication - 183
- Missing publication - 1 (Haven't created new because we still have to sync more activities)
- Delete duplicates - 240
- Merge and delete - 9   

Also created 204 new activities
