### ISSUE TITLE
Deduplicating Generic Publications

### ISSUE THREAD

**Issue by lomky** [USGCRP/gcis#699]
- [x] Update the generic publication scripts to find and avoid creating duplicate pubs
  - [x] Process existing generic publications to find duplicates (scripted or otherwise)
  - [x] work with the data manager to remove dups

Originally in #689

**Comment by amruelama** [comment]
[Worksheet](https://docs.google.com/spreadsheets/d/1lpsGGLIijEuOKFAoain3VnqUAEPOwhZsakFGU0_2KkA/edit#gid=0)
