### ISSUE TITLE
Linking Activities to Figures

### ISSUE THREAD

**Issue by R-Aniekwu** [USGCRP/gcis#702]
I tried associating a 'Figure' with yet another 'Activity', but was unable to. 

Case: Linking NCA3's Figure 2.28 (https://data-stage.globalchange.gov/report/nca3/chapter/our-changing-climate/figure/decline-in-arctic-sea-ice-extent) with this activity (https://data-stage.globalchange.gov/activity/nca3-decline-in-arctic-sea-ice-extent-activity-2).

This is not because this type of relationship is not permissible in GCIS -- GCIS is capable of linking multiple activities with a publication ('Image', for example) and vice versa. It is unclear if we need to contact TSU to resolve this issue.

**Comment by zacharylandes** [comment]
With the current database schema, that link is unfortunately not allowed, marking as on hold so that this functionality will be addressed in the rebuild
