### ISSUE TITLE
Enhance lexicons

### ISSUE THREAD

**Issue by amruelama** [USGCRP/gcis#704]
Fix issues with lexicons and update db as required.

Lexicon page - https://data.globalchange.gov/lexicon
[Working sheet
](https://docs.google.com/spreadsheets/d/1YqVYeyxGKmLHVQjCusfJMC8mquZunH_XwbF9KHQe0Vg/edit#gid=1408603768
)
Related issues: 
#291, #337, #460 

Things to do:

- [x] URL check current lexicons
- [x] URL check individual items under each lexicons
- [x] Deprecate or update lexicons if necessary 
- [x] Research and add any new related lexicons if necessary

**Comment by zacharylandes** [comment]
we will update the lexicon resource as a part of the Rails rebuild

**Comment by hdgh369** [comment]
- [ ] Archive ceos: https://data.globalchange.gov/lexicon/ceos
- [ ] Archive cmip3: https://data.globalchange.gov/lexicon/cmip3
- [ ] Archive dbpedia: https://data.globalchange.gov/lexicon/dbpedia
- [ ] This lexicon (echo) is empty: https://data.globalchange.gov/lexicon/echo
- [ ] Archive esg: https://data.globalchange.gov/lexicon/esg
- [ ] Archive gcmd: https://data.globalchange.gov/lexicon/gcmd
- [ ] Archive nsidc: https://data.globalchange.gov/lexicon/nsidc
- [ ] Archive ornl: https://data.globalchange.gov/lexicon/ornl
- [ ] Archive podaac: https://data.globalchange.gov/lexicon/podaac
- [ ] These two items under [datagov](https://data.globalchange.gov/lexicon/datagov) lexicon seem to be duplicate: "Centers for Disease Control and Prevention, Department of Health and Human Services" and "Centers for Disease Control and Prevention, Department of Health & Human Services".
- [ ] These two items under [datagov](https://data.globalchange.gov/lexicon/datagov) lexicon seem to be duplicate: "Centers for Medicare and Medicaid Services, Department of Health and Human Services" and "Centers for Medicare & Medicaid Services".
- [ ] These two items under [datagov](https://data.globalchange.gov/lexicon/datagov) lexicon seem to be duplicate: "Department of Commerce (DOC), National Oceanic and Atmospheric Administration (NOAA), Ocean and Coastal Resource Management (OCRM), National Marine Protected Areas Center (MPAC)" and "Department of Commerce (DOC), National Oceanic and Atmospheric Administration (NOAA), Office of Ocean and Coastal Resource Management (OCRM), National Marine Protected Areas Center (MPAC)".
- [ ] These two items under [datagov](https://data.globalchange.gov/lexicon/datagov) lexicon seem to be duplicate: "DOC/NOAA/NESDIS/NGDC > National Geophysical Data Center" and "DOC/NOAA/NESDIS/NGDC > National Geophysical Data Center, NESDIS, NOAA, U.S. Department of Commerce".

**Comment by zacharylandes** [comment]
@amruelama I added an archive: true/false field on the lexicon. Please verify on either env.

https://data-dev.globalchange.gov/lexicon/cmip3/edit

Thanks!

**Comment by amruelama** [comment]
@zacharylandes Looks good. Can we add 'GCIS Archive' filter in the lexicon show page? When clicked, it should display all hidden GCIS Archive lexicons.
