### ISSUE TITLE
GCIS Data Model & Conventions Document

### ISSUE THREAD

**Issue by R-Aniekwu** [USGCRP/gcis#714]
Formal documentation of the GCIS data model, the GCIS resource conventions, and the resource-specific research methods used.

The draft of version 1.0 -- https://docs.google.com/document/d/1qQ5RZzk045mcjxS7NB8UOoWUbTV2DV8-rSwEx0Ffqj4/edit?pli=1#

**Comment by amruelama** [comment]
Moved to [gcis-conventions](https://github.com/USGCRP/gcis-conventions/) repo [#37](https://github.com/USGCRP/gcis-conventions/issues/37)
