### ISSUE TITLE
Organization URL redirects to data.globalchange.gov/organization/URL

### ISSUE THREAD

**Issue by amruelama** [USGCRP/gcis#717]
If an organization is being redirected to a different page, it is redirected to `https://data-stage.globalchange.gov/organization/www.uni-oldenburg.de`. 

Reference - https://data-stage.globalchange.gov/organization/carl-von-ossietzky-university-oldenberg

@zacharylandes Any thoughts?

**Comment by zacharylandes** [comment]
@amruelama it's because the url has no https:// at the beginning. I'm now adding the https if it's not there. Check on dev
https://data-dev.globalchange.gov/organization/carl-von-ossietzky-university-oldenberg

**Comment by amruelama** [comment]
Looks good on dev
