### ISSUE TITLE
Duplicate Organizations

### ISSUE THREAD

**Issue by alainafroh** [USGCRP/gcis#718]
These appear to be the same organization. We have already listed the University of East Anglia as an affiliation for "The Tyndall Centre for Climate Change Research"
https://data-stage.globalchange.gov/organization/university-east-anglia-tyndall-centre
https://data-stage.globalchange.gov/organization/tyndall-centre-climate-change-research

These also appear to be the same organization, but I'm not entirely sure
https://data-stage.globalchange.gov/organization/imperial-college-london-grantham-institute-climate-change-environment
https://data-stage.globalchange.gov/organization/grantham-research-institute-climate-change-environment

**Comment by amruelama** [comment]
@alainafroh Thank you. 
Merged **The Tyndall Centre for Climate Change Research**
_Grantham Institute - Climate Change and Environment_ and _Grantham Research Institute on Climate Change and the Environment_ are two different organizations affiliated with each other
